obsidian-tasks-group/obsidian-tasks

- src/File.ts
The file cache that the metadata cache returns can be undefined. We
retry to see if it is set at a later stage. Retrying fixes a reported
bug.
See https://github.com/schemar/obsidian-tasks/issues/87 for details.
Fixes #87
> Retrying to get the file cache if it is undefined

- src/Commands/index.ts
Command palette options now appear when "task" at the end of the command search, ie:
- "Create task"
- "toggle task"
Per #185
> Added support for "task" at the end of command palette options

- .gitignore
- README.md
- src/LayoutOptions.ts
- src/Query.ts
- src/QueryRenderer.ts
- src/Task.ts
Hello,
I added the ability to use layout options with task queries. Currently, it only supports "Hide Task Count" and "Hide Backlinks". I think it's a useful feature since for all but one Query I can hide both. This covers parts of #81.
I decided to add it to the query syntax via "layoutOptions:" and a comma separated list. I think like that it should be clear to the user, that it's not part of the filter.
```tasks
not done
path includes Arbeit
layoutOptions: hideTaskcount, hideBacklinks
```
The possibilities are endless and if more layout options will be added maybe it would make sense to refactor it into its own class to use within the query.
Let me know if this is something you would want in your project and/or if needs any changes.
Thanks!
Phil
Fixes #81
> Added layout options

- README.md
- src/QueryRenderer.ts
I want to be able to style/replace the backlink as needed, on my summary pages I just want to restyle it with a icon like the edit button that takes you to the page it was created on but without all the space taken by the text. This is the most straight forward way I could think of as well as allowing others to style the content.
> Wrap whole backlink with a class

- README.md
- src/Query.ts
Commit 35494cde82bb38c902b9eb4d30dee161e18a1ef0 introduces a bug, where filtering by path does not work if the file path contains capital letters.
The filter statement is converted into lowercase, but comparing the path with the query is case sensitive.
If the goal is to make filtering by path case-insensitive, this tiny pull request should do it.
> Fix case-insensitive path filter

- docs/getting-started/recurring-tasks.md
the 'and-pattern' is not presented in the documentary currently. i think it could be useful to some users.
> recurring-tasks.md -- small typo fix; added an example for the 'and-pattern' in the recurrence rules

- src/QueryRenderer.ts
Using only the basename to identify a markdown document creates confusion on what document should be shown, as it is possible in obsidian to have multiple documents with the same basename. Instead, using a full path could uniquely identify the document. This partially solves #396
> Using full path for backlinks

- docs/getting-started/dates.md
- docs/getting-started/index.md
Tried to fix #484 with examples of order of tags, dates and priorities.
> Docs about parsing of dates and metadata

- src/QueryRenderer.ts
- styles.css
I am loving the new short mode and wanted it to also handle making the backlink shorter. This change modifies the query render so the link is rendered as a link icon when `short mode` is specified. 
I am using this on my local copy of the plugin at the moment and it is looking good.
> feat: Add short version of backlinks when in short mode

- docs/queries/comments.md
- docs/queries/examples.md
- src/Query.ts
- tests/Query.test.ts
I've added a test, and confirmed that it failed before I added the code to ignore comments.
And I've added brief docs, with an example.
As discussed in:
https://github.com/schemar/obsidian-tasks/discussions/531
> Add support for 'comment' instruction
> Add support for comments inside task blocks

- docs/getting-started/index.md
Proposed text to clarify rendering of multi-line tasks and checklist items. Fix for https://github.com/schemar/obsidian-tasks/issues/469
> Clarify multi-line tasks rendering

- src/Query.ts
It's a new query string, which searchs for all the date types: _starting, scheduled, due_ and outputs it. 
Currently you can't query just by date, due, starting and scheduled are all seperated, so you need multiple tasks queries. I think it will be helpful to just see what is coming tomorrow from all sorts of date types set to that date.
```tasks
not done
happens on tomorrow
```
It support the "after" and "before" query as well and it will respect start dates first, in case of multiple date types added to the task.
```tasks
not done
happens before today
```
If you don't want a certain date time shown, you can use the default filter:
`no scheduled date`
```tasks
not done
no scheduled date
happens after today
happens before in 1 week
```
> Add happens query for tasks

- src/Recurrence.ts
- tests/Task.test.ts
A recurring task without a reference date should recur based on today. The code wrongly assumed that `moment(null)` defaults to today, but that is actually not the case. `moment(undefined)` must be used instead.
Fixes #595
> Fix: No longer crash when toggling a recurring task without any date

- docs/queries/filters.md
- src/Query.ts
- tests/Query.test.ts
Added support for filtering by date presence using the format `has <start|scheduled|due> date`. I've been using the start date presence filter specifically in my vault for a little while now to enable a "tickler" system which has been quite helpful; adding support for scheduled and due at the same time was simple enough to do.
I also revisited my strategy for testing slightly with the tests introduced by this PR around recent discussions we have had in the various issues. cc @claremacrae
> Add `has <start|scheduled|due> date` filters

- .editorconfig
- CONTRIBUTING.md
- src/Commands/CreateOrEdit.ts
- src/Query.ts
- src/Sort.ts
- src/Task.ts
- tests/Query.test.ts
- tests/Sort.test.ts
- tests/Task.test.ts
Add the collection of tags as a property of a Task, this allows for running a query against the tags directly. Long term I want to look at adding group by tags. Makes the GTD process simpler.
Changes:
- Add dev setup to contributing
- Add tags as a property of task
- Add query by tag in query language
- Add sort by tag
- Added unit tests for coverage
- Markdown lint fixes
> Add tags as property of task

- tests/Query.test.ts
This:
1. refactors the `'should support filtering %s'` tests so that their code can be re-used in other tests in `Query.test.ts`
2. refactors the tag filtering tests to re-use the above. 
Effectively, this reuses the pattern that @mauleb invented in #629, so that it's easier to see the input and output of filtering tests, and easier to add further tests in future.
> Simplify tag filter tests

- tests/Query.test.ts
3 more tests now use `shouldSupportFiltering(filters, tasks, expectedResult);` to remove some more repetitious code.
> Simplify more tests of Query

- src/Query.ts
Fix 3 warnings in Query.ts that kept interrupting code inspections in WebStorm whenever committing any changes to that file:
- Fix 'Local variable 'limit' is redundant' warning
- Fix 'Method can be static' warning for parseDate()
- Fix 'Method can be static' warning for stringIncludesCaseInsensitive()
All changes made programmatically using WebStorm's 'quick fix'-type capability.
@schemar Code review requested in case there are any language-specific reasons for the 2 methods being non-static.
> Fix 3 warnings in Query.ts

- CONTRIBUTING.md
- Dockerfile
- docker-compose.yml
- docs/README.md
1. Implement testing of documentation locally in a Docker container
2. Document docs-testing process in `docs/README.md`
3. `CONTRIBUTING.md` now links to `docs/README.md`
> Enable viewing of docs in Docker container

- Dockerfile
- docker-compose.yml
- docs/Dockerfile
- docs/README.md
- docs/docker_start
> Docker: Move docker setup into docs

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
To make the pull requests more consistent add a pull request template. This is taken from one of the examples in GitHub
Increased consistency in the Pull Request details. Resolves issue #662 
Followed GitHub documentation and will be validated in next PR.
NA.
> chore: add a pull request template

- .github/workflows/verify.yml
To make it simpler for people to test a build, they can go to a verified build and get the output made by the build system and validated.
Allow users to test a build in PR along with the developers
Via this PR. 
> build: add action to upload verified build to artifacts

- .gitattributes
Control the line endings for *.ts and *.js files to ensure they are always LF. This will override any local settings and make mergers cleaner as the local IDE will not pick these up as issues nor will lint continually reformat them on fix. 
Reduce noise on different operating systems and changes made by the lint process that will just go away when git does a commit anyway.
Validated in multiple PRs
NA
> chore: make *.ts and *.js files LF for all operating systems

- src/Query.ts
- src/Query/Filter/DateField.ts
- src/Query/Filter/DoneDateField.ts
- src/Query/Filter/DueDateField.ts
- src/Query/Filter/Field.ts
- src/Query/Filter/Filter.ts
- src/Query/Filter/HappensDateField.ts
- src/Query/Filter/ScheduledDateField.ts
- src/Query/Filter/StartDateField.ts
- tests/Query.test.ts
(_Interesting that the PR template didn't appear for me_)
Hi @schemar @sytone,
I've mentioned recently that I could see ways to make simple changes to the `Query` code to greatly simplify the creation of filters and the maintenance of the `Query` class.
This PR started as an experiment to try this on one or two of the date filters, and it went well enough that I decided to pursue it and pull out the code for all the date filters (the ones with `before`, `after`, `on`).
I'm moving code out of `Query` and into much smaller classes with single responsibilities, such as `DueDateField`. A ton of boiler plate code has disappeared as a result.
This is done for the date filters, and I will soon do it for the other filters.
`Query.test.ts` is still very big. I will soon divide up its tests to …
> Create date filter classes

- src/Query.ts
- src/Query/DateParser.ts
- src/Query/Filter/DateField.ts
- src/Query/Filter/HappensDateField.ts
- tests/Query.test.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/TaskBuilder.ts
- tests/TestingTools/TaskBuilder.ts
Creating tests that use due date, start date etc involves a lot of emojis, and setting of data that doesn't matter, like task descriptions.
Also, the tests that take a list of task strings, and then return only the tasks that match a filter, have turned out to contain duplicated text (for tasks that match the filter) and require some careful examination to establish which tasks missed the filter, and why.
I wanted to:
1. see if the Builder Pattern would be helpful for writing tests of particular task properties.
2. see if I can make it more explicit which tasks matched a filter and which not in small tests.
Some example code using `TaskBuilder`:
```typescript
const builder = new TaskBuilder();
const task = builder
.description('hello world')
.priority(Priority.High)
.path('root/dir 1/dir …
```
> Add TaskBuilder class for writing small tests

- src/Query.ts
- src/Query/Filter/DescriptionField.ts
- src/Query/Filter/HeadingField.ts
- src/Query/Filter/PathField.ts
- src/Query/Filter/TextField.ts
- tests/Query.test.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/HeadingField.test.ts
- tests/Query/Filter/PathField.test.ts
- tests/TestingTools/FilterTestHelpers.ts
- tests/TestingTools/TaskBuilder.ts
Refactor to divide up the filtering code for description, path and heading in to separate classes.
Add new classes:
- `DescriptionField`
- `HeadingField`
- `PathField`
- and `TextField`, which is an abstract base class for all the above
This is part of addressing #664: 'refactor the Query class to be more modular'.
As with #690:
- remove duplicated code in Query class
- make it easy to add new types of filter in future
- make the code easier to understand
- Done in small refactoring steps, to guarantee behaviour unchanged.
- Created a new test file for each of the new tasks
- Where tests for these features were in Query.test.ts and easy to move, I moved those to the new test files.
- Introduced new testing helper function `testTaskFilter()`
- this really streamlines testing of filters, as …
> refactor: Create text filter classes

- src/Query.ts
- src/Query/Filter/PriorityField.ts
- tests/Query/Filter/PriorityField.test.ts
- tests/TestingTools/FilterTestHelpers.ts
Refactor code for priority instruction out from Query
Part of addressing #664
- Added tests of priority instruction via the Query code
- Then converted Query to use PriorityField, and ran tests whilst still running searches via Query - this confirmed behaviour was unchanged.
- Then simplified tests to use PriorityField directly.
- The tests revealed a typo in an error message, which I'll fix in a later commit.
> refactor: Create priority filter class

- src/Query/Filter/PriorityField.ts
- tests/Query/Filter/PriorityField.test.ts
A tiny change: This error message:
`'do not understand query filter (priority date)'`
Is now:
`'do not understand query filter (priority)'`
Only noticed when writing a test for the error handling - fixed because it was easy to do so.
By updating the existing test code.
> fix: Fix typo in error message for priority instruction.

- README.md
@claremacrae the redirect _should_ work for all documentation links. Though I only tested briefly.
> Docs now redirect correctly

- CONTRIBUTING.md
Some of the text in CONTRIBUTING was hard to read, due to numbers being interpreted as ordered lists.
By rendering the Markdown in WebStorm and GitHub site.
> docs: Fix 'How does Tasks handle status changes?' formatting

- CONTRIBUTING.md
- docs/advanced/styling.md
- docs/queries/filters.md
- docs/queries/grouping.md
- docs/queries/sorting.md
- Edit CONTRIBUTING.md to document a new still of comment in the documentation to indicate when features, or parts of features, were added.
- Apply this style to the docs of features released in 1.6.0.
There was a bit of support traffic after the 1.6.0 release, when users tried using newly-released features, and had not known they needed to update their Tasks plugin.
This may help a little.
Unfortunately I am unable to build the documentation on a Mac, as I get:
> + docker run --rm -it --volume /Users/clare/Documents/develop/Obsidian/schemar/obsidian-tasks/docs:/docs:Z --publish 4000:4000 obsidian-tasks-docs:latest
> Could not find nokogiri-1.13.6-x86_64-linux in any of the sources
_Logged in #732._
~~So I've previewed the changes in a Markdown editor, and am merging this to the …
> docs: Indicate when 1.6.0 features were released

- docs/queries/grouping.md
- src/Query.ts
- src/Query/Group.ts
- tests/Group.test.ts
Add new options to the `group by` command: `start`, `scheduled`, `due` and `done`
Requested in #693
- via new unit tests
- it's been in use in my fork for some months
- downloaded the build from this PR and tested it in the [theme-dev-vault](https://github.com/obsidian-community/theme-dev-vault) to create a screenshot
> feat: Add 'group by <start|scheduled|due|done>'

- docs/queries/filters.md
- src/Query/Filter/DoneDateField.ts
- src/Query/Filter/HappensDateField.ts
- tests/Query.test.ts
- tests/Query/Filter/DoneDateField.test.ts
- tests/Query/Filter/HappensDateField.test.ts
Add:
- `has done date`
- `no done date`
- `has happens date`
- `no happens date`
This change was partly an experiment to see if I could easily represent the `has done date`/`no done date` filters in the `Field` class hierarchy.
My conclusion was that I can, and so in a later PR I will refactor a lot of the remaining presence/absence filters from Query out to use the recently-added Field classes.
So please don't worry about the temporary duplication of code created in this PR. It will go away soon.
This completes the implementation of https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/618
Via new unit tests
By creating a Pull Request you agree to our [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md). For further guidance …
> feat: Add 'has done date', 'has happens date', 'no done date', 'no happens date'

- .github/ISSUE_TEMPLATE/issue-template.md
There is a character limit of 200, for the 'about' section
> chore: Shorten 'about' to fix the issue template

- src/Abbrev.ts
- src/ui/EditTask.svelte
Adds a quicker way to insert dates in the GUI with abbreviations
Best way would probably to extend chrono, but a small table with Regex replacements does the job easily:
```js
{
td: 'today',
tm: 'tomorrow',
yd: 'yesterday',
tw: 'this week',
nw: 'next week',
weekend: 'sat',
we: 'sat',
}
```
Additionally I refactored the date parsing into its own function.
> feat: Add date abbreviations to 'Create or edit Task' modal

- docs/Gemfile.lock
Fixes Integer overflow in cmark-gfm table parsing extension leads to heap memory corruption
> chore: Update commonmarker to 0.23.4

- package.json
- yarn.lock
Downgrade esbuild from 0.14.43 to 0.13.15.
[esbuild 0.14.0](https://github.com/evanw/esbuild/releases/tag/v0.14.0) was a breaking change, so go for the last release on 0.13.x for now.
Fixes #764: Clicking 'Apply' in 'Create or edit Task' fails with console error.
1. Edit the rebuild version
1. Delete `node_modules`
1. `yarn install`
1. `yarn dev`
1. Copy the created files to my test vault
1. Restart Obsidian
1. Confirm that the Apply button now works as expected
> fix: 'Apply' in 'Create or edit Task' started failing earlier today

- docs/queries/index.md
Update the link that's used to explain why sub-tasks are not nested in query results.
The old one was #50, which got converted to #60. The latter has much more discussion and information.
> docs: Use newer link for discussion on non-indenting of sub-tasks

- src/DateAbbreviations.ts
- src/ui/EditTask.svelte
- tests/DateAbbreviations.test.ts
1. Move the date abbreviation expansion code out of .svelte file to allow it to be tested
2. Write passing tests for existing date abbreviation expansion code
3. Write failing tests for expansion of abbreviations with capitals
4. Make the regular expression for date abbreviation expansion code case-insensitive
Fixes #768 - so that the feature is useful on devices that capitalise the first letter typed in text boxes, such as on my iPad.
1. By writing unit tests
2. By testing it on a Mac
> feat: Allow capital letters in abbreviations for dates in Create or edit Task modal

- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/DoneDateField.test.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/HappensDateField.test.ts
- tests/Query/Filter/HeadingField.test.ts
- tests/Query/Filter/PathField.test.ts
- tests/Query/Filter/PriorityField.test.ts
- tests/TestingTools/FilterTestHelpers.ts
I noticed that there was a growing number of tests that use `TaskBuilder` and look like this:
```typescript
const builder = new TaskBuilder();
testTaskFilter(
filter,
builder.precedingHeader(precedingHeader).build(),
expected,
);
```
The `.build()` call was repeated in numerous places, and was unnecessary repetition.
So I've added a new test function:
```typescript
export function testFilter(
filter: FilterOrErrorMessage,
taskBuilder: TaskBuilder,
expected: boolean,
}
```
So the tests can now look like this:
```typescript
const builder = new TaskBuilder();
testFilter(filter, builder.precedingHeader(precedingHeader), expected);
```
The original `testTaskFilter()` that takes a `Task` remains unchanged, to avoid breaking any new tests on existing branches.
Goals: 
- To simplify writing tests …
> test: Add test helper testFilter() that takes a TaskBuilder

- src/Query.ts
- src/Query/Filter/DateField.ts
- src/Query/Filter/DoneDateField.ts
Teach `DateField` to do these searches:
-  `has [due|start|scheduled|done] date`
-  `no [due|start|scheduled|done] date`
This removes the need for some text from Query that implemented the presence/absence tests for Due, Start and Scheduled dates.
Note: There was error in one commit message. I'll fix it during the merge.
This moves more responsibility to the `DateField` class, and will make it easier to add filtering for any new date types in future.
Via the pre-existing tests.
> refactor: The date fields do their own presence/absence searches

- src/QueryRenderer.ts
Remove tags from backlink's `href` and `data-href` to resolve #654. As discussed in the issue, Obsidian expects links to sections with tags to have `#` symbols removed, this change fixes rendered task's links.
Bug fix tested locally using the Tasks-Demo vault.
Tag added to heading in ACME note and backlink tested for tasks rendered in the Tasks note.
> fix: Unable to find section, when title has tag inside (#654)

- .github/workflows/codeql-analysis.yml
Updating the codeql config file to use v2 of the codeql-action APIs.
Current CodeQL runs show deprecation warnings for the v1 codeql-action uses and suggest using v2. This API bump was a backend change to CodeQL that should not affect the analysis. This PR updates the codeql config file to use v2, which gets rid of the deprecation warnings.
Proposed in #809 
Ran CodeQL in my fork on this change. Run completes successfully and deprecation warnings are gone.
I agree to the [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md).
> chore: Use v2 of codeql-action

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
Hi @claremacrae - I'm using the GitHub web editor for all this and it does not seem to rebase upstream pulls or squash commit messages. This, the "3" commits here are my first PR, this PR, and then pulling upstream (after you merged my first PR) respectively. If you have a button to rebase and/or squash while accepting this PR, please do!
Use dependabot to update github-actions such as codeQL.
GitHub sometimes updates and then deprecates their github-actions APIs. We saw deprecation warnings on codeql, for example, fixed in #811. This PR has dependabot find and fix these for us automatically. Proposed in #809 
Verify commit and CodeQL actions both pass on my fork. Dependabot should run after merge; as sort of a post-hoc test you could check whether it finds that `checkout@v3` is available …
> chore: Use dependabot to update github-actions

- .gitignore
- resources/sample_vaults/Tasks-Demo/.obsidian/core-plugins.json
1. Obsidian has removed the core plugin "open-with-default-app", so commit the updated `core-plugins.json` in the Tasks-Demo sample vault.
2. Tell git to ignore `.hotreload`, to enable use of the hot reload plugin when testing new versions of Tasks in the Tasks-Demo sample vault.
Just minor house-keeping, to streamline testing the Tasks plugin manually.
By editing the sample vault in Obsidian 0.15.2.
> chore: Make git happy with the resources/sample_vaults/Tasks-Demo/ sample vault

- docs/queries/filters.md
Changes made:
- Add 'days ago' to filter date examples.
- Based on feedback in #819.
- Also make yyyy-mm-dd example unambiguous.
- And add 'yesterday', for completion.
- Divide filters list logically & note OR workaround
- The list of available filters had become long and a little hard to read and find patterns in.
- This groups related filters together, for readability and structure.
- Make 'done' and 'not done' more prominent in docs
- They were previously only listed under 'done date' which was useful, but not entirely accurate.
- Sort sub-headings alphabetically, for readability
- Add brief intros to the new sections
This was prompted by feedback in #819 that `days ago` was not documented.
I had been feeling for some time that the list of all filters had become quite long and …
> docs: Overhaul the Filters documentation

- docs/quick-reference/index.md
I found that by separating Sort and Group in to different columns, it is easier to spot the gaps in functionality Filter, Sort and Group functionality.
This required combing the Filter and Presence/Absence columns instead in to a single Filters column.
I want to be able to see the gaps in features, so I can fill some of them in.
By generating and viewing the docs locally.
> docs: Improve readability of columns in Quick Reference

- tests/Task.test.ts
Simplify some tests in `Task.test.ts` By using `fromLine()` in `TestHelpers`, instead of `Task.fromLine()` as the former is simpler to call, when we don't care about file and section names.
To try to steer future Pull Requests towards simpler code when writing tests of the parsing of task lines,
By running the existing tests.
> test: Simplify some tests in Task.test.ts

- tests/Task.test.ts
Just some minor house-keeping to move a new test added in #850 in to the correct section.
Fixed a couple of other minor things also in Task.test.ts, to stop WebStorm warning about them.
See commits for details.
By running the tests
> test: move a parsing test to correct section

- src/Query/Filter/BooleanField.ts
- tests/Query/Filter/BooleanField.test.ts
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/866.
Fixes an issue with spaces inside the sub-queries in a boolean field.
A test was added and the existing tests were run.
> fix: Boolean searches with spaces around sub-queries now work

- docs/queries/filters.md
Minor documentation change: I forgot one location to note release version of boolean combinations.
> docs: Note that Boolean combinations were introduced in Tasks 1.9.0

- src/Cache.ts
This is a serious of safe refactorings, all but one of which were totally automated in WebStorm.
The core change is to extract the majority of code in `Cache.indexFile()` out in to a separate static method `Cache.getTasksFromFileContent()`.
By making that new method static, I can be confident that it is not changing any state in the Cache, and I can later compare the tasks it read from the edited file, to see if they are different from the tasks last read from the same file.
It is in preparation for fixing #886 - so that the eventual fix will be a smaller commit that is easier to review.
By editing some tasks In a test vault. with the new changes, and confirming that tasks blocks are still updated.
By creating a Pull Request you agree to our [Code of …
> refactor: Preparation for only redrawing tasks blocks if edits change any tasks

- src/Cache.ts
- src/QueryRenderer.ts
- src/Recurrence.ts
- src/Sort.ts
- src/Task.ts
- tests/Recurrence.test.ts
- tests/Task.test.ts
- tests/TestingTools/RecurrenceBuilder.test.ts
- tests/TestingTools/RecurrenceBuilder.ts
- `Cache` changed to only trigger a refresh of active tasks blocks if the edit made changed any tasks, or their parent headings
- Intended benefit: When editing, there will be far fewer refreshes
- Unintended benefit: When starting up tasks, and every file is read to find tasks, only the files with tasks in trigger the refreshing of tasks blocks, not every file. (I will look at making that more efficient in future)
- Debug logging added to help users understand what is triggering refresh
- `QueryRenderer` now prints out console information, including file name, so users can see which files are taking most time to render. 
Behind the scenes:
- Very thorough mechanism added to detect changes between tasks and their recurrences. Lots of tests added for that.
- Added …
> perf: Stop many non-task edits triggering a redraw of all active tasks blocks

- docs/getting-started/auto-suggest.md
- src/Task.ts
- tests/Task.test.ts
- Allow more than 1 space between date emojis and their dates when parsing task lines
This fixes #898.
- By adding new tests.
- By building the plugin and testing it with the instructions in #898.
> fix: Allow multiple spaces after date emojis, when reading task lines

- src/Task.ts
- src/ui/EditTask.svelte
- tests/Task.test.ts
This PR is a pure refactor (no change in functionality) of the simple logic in `EditTask.svelte` that removes a task's global filter before it is displayed in the edit window.
It just moves those 5 lines into a new method `Task.getDescriptionWithoutGlobalFilter` and covers this with multiple new tests.
This is a result of the discussion in [this](https://github.com/obsidian-tasks-group/obsidian-tasks/pull/869) bug fix.
Wanting to do a more comprehensive fix for this logic, which is a source for multiple bugs, we wanted to cover it with tests first.
Multiple automated tests.
By creating a Pull Request you agree to our [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md). For further guidance on contributing please see [contributing …
> refactor: Moved the logic of removing the global filter in Task and covered it with tests

- docs/queries/grouping.md
- src/Query.ts
- src/Query/Group.ts
- src/Query/GroupingTreeNode.ts
- src/Query/IntermediateTaskGroups.ts
- src/Query/TaskGroups.ts
- tests/Group.test.ts
- tests/GroupingTreeNode.test.ts
- tests/Query.test.ts
This PR adds support for grouping tasks by tags. Given that a single task can have multiple tags, this PR also refactors the grouping logic to be more generic and support having the same task under multiple groups.
The approach I went with is building a tree of each grouping layer, and at the end traversing this tree to get the final task groups to render. The logic is documented in code with examples.
> Side Note: I'm very impressed with the code/documentation quality of the plugin. Reading and contributing to the codebase was extremely smooth.
I personally categorize my tasks with tags, and I'd like to have a single dashboard with all my tasks grouped by the specified tag.
Seems like a popular request as well:
https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/620 …
> Add support for grouping by tags

- docs/queries/grouping.md
- docs/quick-reference/index.md
Also, note that 'group by tags' was added in 1.10.0
> docs: Add 'group by tags' to Quick Ref docs

- docs/queries/grouping.md
- docs/quick-reference/index.md
- src/Query.ts
- src/Query/Group.ts
- tests/Group.test.ts
- tests/Query.test.ts
Add two new grouping commands:
- `group by recurrence`
- `group by recurring`
- update the Grouping docs page
- update the Quick Reference docs page
From the new docs:
1. `recurring`
* Whether the task is recurring: either `Recurring` or `Not Recurring`.
1. `recurrence`
* The recurrence rule of the task, for example `every week on Sunday`, or `None` for non-recurring tasks.
* Note that the text displayed is generated programmatically and standardised, and so may not exactly match the text in any manually typed tasks. For example, a task with `🔁 every Sunday` is grouped in `every week on Sunday`.
I have found these useful in my fork of this project, so am making them available to others.
- Via new unit tests
- At length in my main vault
By creating a Pull Request you agree to our [Code of …
> feat: Add 'group by recurrence' & 'group by recurring'

- docs/queries/grouping.md
- docs/quick-reference/index.md
- src/Query.ts
- src/Query/Group.ts
- src/Task.ts
- tests/Group.test.ts
- tests/Query.test.ts
Add new priority  grouping command:
- `group by priority`
- update the Grouping docs page
- update the Quick Reference docs page
From the new docs, the group names will be one of:
* `Priority 1: High`
* `Priority 2: Medium`
* `Priority 3: None`
* `Priority 4: Low`
I have found this useful in my fork of this project, so am making it available to others.
- Via new unit tests
- At length in my main vault
> feat: Add 'group by priority'

- docs/queries/grouping.md
- docs/quick-reference/index.md
- src/Query.ts
- src/Query/Filter/HappensDateField.ts
- src/Query/Group.ts
- tests/Group.test.ts
- tests/Query.test.ts
- tests/Query/Filter/HappensDateField.test.ts
Add `HappensDateField.earliestDate()`
Add new happens  grouping command:
- `group by happens `
- update the Grouping docs page
- update the Quick Reference docs page
This groups by the earliest of `start` date, `scheduled` date, and `due` date, including the week-day, or `No happens date` if none of those are set.
I have found this useful in my fork of this project, so am making it available to others.
This is also part way to implementing #616 - 'Sort By Happens'.
- Via new unit tests
- At length in my main vault
By creating a Pull Request you agree to our [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md). For further guidance on contributing please see [contributing guide](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/mai …
> feat: Add 'group by happens'

- package.json
- src/lib/logging.ts
- yarn.lock
Add logging library to be used to centralize log output and levels in logging. No updates to any other files or main have happened to configure or use this. If this is done this PR will be more than one file as all instances of the console call will be replaced.
Logging output is inconsistent and there is no central way to change the logging level. 
Heavily used in SQL fork.
> chore: add logging library for more consistent logging output

- docs/getting-started/index.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
- src/Cache.ts
- src/Commands/CreateOrEdit.ts
- src/Commands/ToggleDone.ts
- src/Events.ts
- src/LivePreviewExtension.ts
- src/Query/Filter/ExcludeSubItemsField.ts
- src/Task.ts
- src/main.ts
- tests/Query.test.ts
- tests/Query/Filter/ExcludeSubItemsField.test.ts
- tests/Task.test.ts
Now that I am familiar with the dataview codebase, I found their regex for parsing list items, which works with Obsidian callouts, and it turns out the fix is super easy to add to Tasks! Blockquote/callout indicators are now stored along with spaces and tabs in the `indentation` field of the Task, so they are preserved when the task is rendered out to string.
Fixes #656 including nested blockquotes/callouts
Added unit tests for parsing the task, parsing tags out of the task, and toString. Something mentioned in the issue thread is testing specifically that the `indentation` is preserved when a new instance of a recurring task is generated - I could not figure out where in the tests to put that, if you still think it is needed, could you give me a pointer please to where in the tests it …
> fix: find tasks in blockquotes and Obsidian callouts

- .github/ISSUE_TEMPLATE/config.yml
It turns out that Markdown is not rendered in 'about' descriptions, so remove it
Still trying to help users find existing discussions.
Can't be tested until merged.
> chore: Remove markdown from issue descriptions

- docs/getting-started/index.md
This essentially copies in @AnnaKornfeldSimpson's text from the popup warning about issues with completing tasks that are in callouts when in Live Preview mode.
It also breaks up a long-ish paragraph a bit.
Just to make it a little easier to see what the issue is with tasks in callouts in Live Preview.
By viewing the rendered docs locally in docker.
This is what the changed docs look like now:
> docs: Refine explanation of callouts in Live Preview

- docs/getting-started/index.md
Note that version 1.11.1 reads (or will read) tasks in callouts & blockquotes
> docs: 1.11.1 reads tasks in callouts & blockquotes

- docs/README.md
- docs/advanced/notifications.md
- docs/getting-started/auto-suggest.md
**Note**: I am putting this as a PR to `main` since GitHub was confused otherwise, but the docs changes can go to `gh-pages` also; they do not need to wait for another Tasks release.
* docs: Fix "Notifications" page to warn about recent issues - fixes #927 
* docs: Add FAQ entry to "Auto-Suggest" page about combining with auto-suggest features from other plugins - fixes #928 
* docs(internal): Add section to the README in "/docs" about dependency management and a note about running Docker+Jekyll from Windows - fixes #979 
Now that I can finally run the docs locally, working on my backlog of documentation.
Issues: #927 #928 #979
Tested by running docs locally.
> docs: fix notifications, update auto-suggest

- src/Cache.ts
fix: Use header cache instead of section cache to find headings for shorter loop and greater code readability
fix: Only read and parse the file for tasks if there are listItems in Obsidian cache
refactor: Match arguments of getSection and getPrecedingHeader for greater code readability
This PR contains the re-written `getPrecedingHeader` that I removed from my callout and blockquote PR. It uses the Obsidian-provided heading cache to both shorten the loop (perf) and simplify the extraction of the header text (readability, maintenance).
Also contains a couple other small fixes:
Fixes #959 
Readability improvement to have `getSection` args match `getPrecedingHeader` args. **Note:** If there is some reason that I do not know of to keep using the lengthier "pass all args as JS object then add …
> fix: Trim trailing white-space from headings

- tests/CustomMatchers/CustomMatchersForFilters.ts
- tests/Query/Filter/CustomMatchersForFilters.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/PathField.test.ts
When the regex searching code was added, @elight showed me how to write custom Jest matches for more expressive tests.
We added the first matcher in the path tests, then more were added in description.
Now I would like to re-use them in other locations, so I've moved them out to a new file:
`tests/CustomMatchers/CustomMatchersForFilters.ts`
I suspect that there may be more idiomatic ways of doing this, like maybe added interface files, but for now I'm happy enough that it's going to be possible to re-use these matches in other places.
To enable me to re-use some valuable testing code.
By re-running the changed tests.
> test: Move custom Jest matchers to separate file

- tests/CustomMatchers/CustomMatchersForFilters.ts
- tests/Query/Filter/DescriptionField.test.ts
I realised that `toMatchTaskWithDescription()` was actually more general than it sounded, so have renamed it to 
`toMatchTaskFromLine()`, as it not at all specific to descriptions.
More readable tests, and more obvious that a custom matcher can be re-used.
By running existing tests
> test: Rename custom matcher and add motivating docs

- .github/ISSUE_TEMPLATE/bug-report.yaml
Reinstate 'Possible solution' section at the end of the bug report template.
I lost it by accident when converting from markdown to yaml in #985
Syntax is valid according to WebStorm.
I can only test it after merge.
> chore: Reinstate 'Possible solution' section in bug template

- src/Query/Filter/TextField.ts
This was code review feedback from #790.
To resolve a conversation from review of #790, and prevent WebStorm from warning that `maybeNegate()` may be static on every commit.
By running exiting tests
> refactor: Move TextField.maybeNegate() to end and make static

- tests/CustomMatchers/CustomMatchersForFilters.ts
- tests/Query/Filter/HeadingField.test.ts
- Add missing tests for filtering headings with regex
- Add Jest custom  matcher `toMatchTaskWithHeading()`
- Refactor out duplicated code in the custom matchers by adding `toMatchTask()`
Fill gap in test coverage for regex searches
Simplify the jest custom matcher implementations.
Running all existing tests, and adding new ones
> test: Test heading with regex, add 2 custom matchers

- docs/queries/examples.md
- docs/queries/filters.md
- docs/queries/regular-expressions.md
- resources/sample_vaults/Tasks-Demo/Filters/Regular Expression Searches.md
- src/Query/Filter/DescriptionField.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/HeadingField.test.ts
- tests/Query/Filter/PathField.test.ts
Many improvements to documentation of regex searches, and some tests added, in order to understand behaviour before writing the docs.
Too many steps to list. Please see individual commits.
Resolves all remaining conversations in #1015.
- By adding and running tests
- By viewing the docs locally
> docs: Finish docs and tests for regex searches

- src/Query/Filter/TextField.ts
- src/Query/Matchers/IStringMatcher.ts
- src/Query/Matchers/RegexMatcher.ts
- src/Query/Matchers/StringMatcher.ts
- src/Query/Matchers/SubstringMatcher.ts
- tests/Query/Matchers/RegexMatcher.test.ts
- tests/Query/Matchers/SubstringMatcher.test.ts
Extract 3 classes out of `TextField`:
- `IStringMatcher`
- `SubstringMatcher`
- `RegexMatcher`
These hide away the details of how the `includes` and `regex matches` searches are constructed and executed, which will allow for re-use in the `TagsField` class later.
All steps were done as small, safe refactorings, mostly done automatically via WebStorm's 'Refactor this' feature.
**Note that there is scope for more simplification of the code in a future PR**
There are now two identical copies of this code:
```ts
result.filter = (task: Task) => {
return TextField.maybeNegate(
matcher.matches(this.value(task)),
filterMethod,
);
};
```
In other words, the new interface means that `TextSearch` now doesn't care whether it is doing a substring search or a regex search - the resulting filtering code …
> refactor: Extract text searching out of TextField

- src/Query/Filter/TagsField.ts
- src/Query/Filter/TextField.ts
- src/Query/Matchers/IStringMatcher.ts
- src/Query/Matchers/RegexMatcher.ts
- src/Query/Matchers/SubstringMatcher.ts
- tests/Query/Matchers/SubstringMatcher.test.ts
- `IStringMatcher` is now an abstract class
- Added `IStringMatcher.matchesAnyOf(stringsToSearch: string[])`
- TagsField is now implemented using `SubstringMatcher`
This will make it really easy to add regex searching in a later step
> refactor: Tags search now implemented with SubstringMatcher

- src/Query/Filter/Filter.ts
- src/Query/Filter/TextField.ts
This looks like a rather scary refactoring, that has changed large amounts of code in `TextField.createFilterOrErrorMessage()`.
In fact, it's a series of almost entirely automated refactorings, done with WebStorm.
I tried multiple times to find a way to make the diff clear in the GitHub API, but because it doesn't have a way to temporarily ignore differences in indentation only in diffs, it was never going to be very clear in this view.
The two goals were:
1. Replace 3 levels of nested if/else blocks with early return statements.
2. Elimate the duplicate code for creating `result.filter`
For details of the refactorings, see the commits.
But basically, the bulk of it was a series of:
- Flip if/else - so that the error-check comes before the implementation
- Unwrap 'else' - so that because …
> refactor: Simplify TextField

- package.json
- yarn.lock
* rename lefthook as instructed by warning from yarn
When installing packages from scratch, yarn gives a warning that `lefthook` has been renamed. This PR does the rename and gets rid of the warning.
Also the lefthook output on Windows is now clearer!
Hooks run for commit and push locally and via GitHub Actions.
> chore: lefthook was renamed

- docs/how-to/get-tasks-in-current-file.md
- docs/other-plugins/dataview.md
I have finally written up how to use dataview to create a list of tasks in the current file that does not get broken when the file is renamed.
Commits made:
- docs: Add 'How to get tasks in current file'  
- docs: Add links between dataview-related pages  
- docs: Add table of contents to dataview page
This and related searches are a common request, e.g. the discussion in #444
By generating the docs locally.
> docs: Add 'How to get tasks in current file'

- docs/installation/index.md
When you enter "tasks" on [plugins page](https://obsidian.md/plugins?search=tasks) this plugin is actually at the bottom making it hard to find...
With this link it will be easier to find and install this plugin.
> docs: Make it easier to find and install this plugin

- src/config/Settings.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/TagsField.test.ts
- tests/Sort.test.ts
- tests/Task.test.ts
This adds a new function resetSettings() and updates all existing tests that used to save originalSettings, so that they now just call resetSettings() on completion.
This ensures that **passing** tests that fiddle with global settings definitely return them to the default state on completion.
Unlike the fix proposed in #1046, this does not reset the global settings after any failing tests.
This is related to #1046.
By running the existing tests.
> test: Simplify the resetting of settings in tests

- docs/queries/filters.md
- src/Query/Filter/TagsField.ts
- tests/Query/Filter/TagsField.test.ts
In `tag` and `tags` searches, if the instruction contains a `#`, it is now honoured.
This means that a search for `tags include #home` no longer matches `- [ ] stuff #location/home`.
If there were any existing searches for `partial_tag_string` like the '#'...
`tag includes #partial_tag_string`
that were intended to match:
`- [ ] some text #blah/partial_tag_string`
Then this change would mean that the above task is no longer found as `#partial_tag_string` is not actually present in the task.
The fix would be to remove the `#` from the query.
I'm taking the view that if the user included a `#` in the query, they intended the `#` to be present.
Fixes #1106
By adding new tests, and confirming that none of the existing tests failed.
> fix!!: Tag searches now honour any # character

- resources/sample_vaults/Tasks-Demo/.obsidian/hotkeys.json
- resources/sample_vaults/Tasks-Demo/Manual Testing/Toggle Done Cursor Fixes.md
- src/Commands/ToggleDone.ts
Rewrite of the logic in ToggleDone.ts to replacing the cursor correctly. Should fix #449 #460 and maybe others. This took me a really long time to think through and make sure I was testing all corner cases. I am pretty confident of its correctness, but it is not as polished as I might hope and I might always have missed a corner case. Sadly I am out of time to polish. I can try to answer any questions, but I do not have time to fix and test changes, so if additional work is needed, someone else will have to pick it up.
The Tasks: Toggle Done command uses `editor.setLine` which deletes and then replaces a line. This causes the cursor position to get lost and it needs to be explicitly reset. The existing code to do this was based on a no-longer-correct assumption. (Actual behavior explained …
> fix: Correct cursor position after 'Toggle task done' command

- src/Commands/ToggleDone.ts
- tests/Commands/ToggleDone.test.ts
Adds some automated tests for some of the behaviours of the  'Toggle task done' command.
This captures some of the improvements in behaviour made in #1103.
- to avoid needing to manually test the  'Toggle task done' command so often
- to confirm the behaviour of many of the fixes in #1103.
By running the tests I added.
> test: Add initial tests for 'Toggle task done' command

- CONTRIBUTING.md
- Adds new content to CONTRIBUTING documenting process for thinking through whether dependency upgrades need a smoke test.
- Re-arrange CONTRIBUTING so useful information on local setup is higher in the document
- A number of typo and clarity fixes to CONTRIBUTING including mentioning Discussions as an alternative to Issues for discussing proposed changes.
Fixes #1086 
Viewed locally and on GitHub
> chore: Reformat CONTRIBUTING, add dependency upgrade info, fix typos

- docs/how-to/find-tasks-for-coming-7-days.md
- docs/how-to/get-tasks-in-current-file.md
- docs/how-to/style-backlinks.md
Add How-to page 'Find tasks for coming 7 days'
This is an answer for https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1129
> Tasks for the coming week
By viewing the docs locally.
> docs: Add How-to page 'Find tasks for coming 7 days'

- src/Query/Filter/BooleanField.ts
- tests/Query/Filter/BooleanField.test.ts
- tests/TestingTools/TaskBuilder.test.ts
- tests/TestingTools/TaskBuilder.ts
- This makes `( any valid filter )` be equivalent to `any valid filter`
- Also fixed a few limitations of TaskBuilder which I discovered whilst writing a failing test for this issue.
This fixes #975.
See the description in #975 for why this helps.
- Tested the modified regex in https://regex101.com before adding it to the code
- By running existing tests
- By adding a failing test for the problem
- And by strengthening the existing tests for BooleanFilter to make sure that it tests `canCreateFilterForLine()` as well as `createFilterOrErrorMessage()`
> fix: Support single filters surrounded by parentheses

- docs/getting-started/create-or-edit-task.md
- src/ui/EditTask.svelte
- styles.css
This PR adds a new checkbox labelled "Force future dates" to the "Edit task" dialog.
This checkbox is checked by default. If you uncheck it, relative dates entered in the date fields are no longer enforced to be in the future, but you can also specify dates in the past.
Assume it is Sunday and you enter "last Saturday" in the "Due" field. Then this is interpreted as *next* Saturday (in 6 days) by default, because all dates are assumed to be in the future (using the "forwardDate" option of chrono which is set by default).
But sometimes, you may actually want to enter a date in the past, like if you missed a deadline something last Saturday but still want to work on the task and have it shown as "overdue". Another reason to disable the "fowardDate" feature is to experiment with how natural …
> feat: Add checkbox to disable forwardDate in Task editor

- docs/getting-started/create-or-edit-task.md
Note that `Only future dates` was introduced in Tasks 1.15.0.
Omitted by mistake in reviewing the relevant PR.
Previewed in WebStorm.
> docs: Note release version of 'Only future dates'

- src/Query/Filter/Filter.ts
- tests/Query/Filter/Filter.test.ts
- Add new (unused) `Filter` class
- Encapsulate `filterFunction` in `FilterOrErrorMessage`
- `FilterOrErrorMessage` now stores a `Filter`
This is in preparation for adding new features to the Filter class
Running existing tests.
Adding a new test for `Filter`
> refactor: Reimplement FilterOrErrorMessage using new Filter class

- src/Query/Filter/BooleanField.ts
- src/Query/Filter/DateField.ts
- src/Query/Filter/Filter.ts
- src/Query/Filter/FilterInstruction.ts
- src/Query/Filter/FilterInstructions.ts
- src/Query/Filter/HappensDateField.ts
- src/Query/Filter/PriorityField.ts
- src/Query/Filter/TextField.ts
- tests/Query/Filter/Filter.test.ts
I've called this a refactoring, as it does not yet change the externally visible behaviour.
`Filter` & `FilterOrErrorMessage` now have a field called `instruction` which is the line supplied by the user.
This will be useful later for providing an explain facility, showing how the user's filters get converted to actual searches.
Running existing tests.
> refactor: Add instruction field to Filter & FilterOrErrorMessage

- src/Query/Sort.ts
- tests/Sort.test.ts
Fixes an error that valid and invalid dates were considered to be identical when sorting, which meant that if a user edited a task to change its due date from invalid to valid, no tasks blocks were updated to show the new data.
This fixes #1227:
"Failure to redraw Tasks block results when signifier dates change from valid to invalid - and the reverse"
- Manually testing a new build of the plugin, to confirm that the bug is fixed
> fix: Redraw Tasks results when dates change from valid to invalid 

- docs/getting-started/create-or-edit-task.md
Document the iPhone scrollbar issue in Create/edit task modal.
See #1238.
If it helps a few iPhone users know that they can scroll, it was worthwhile.
By viewing the docs locally.
Changes to contents list:
The new words:
> docs: Document iPhone scrollbar issue in Create/edit task.

- .markdownlint.jsonc
- CODE_OF_CONDUCT.md
- docs/queries/grouping.md
- Configure markdownlint to use hyphens for unordered lists
- And run it, to standardise bullets in a couple of files
I am going to be using [markdownlint](https://github.com/simonCropp/MarkdownSnippets) to add tables of contents to a few markdown files used by maintainers.
This puts `*` in as the first UL in the file, meaning that the previous setting of 'consistent' would have converted all later bullets to `*` instead of `-`.
I want to standardise on `-`. because Obsidian's habit of putting in 2 `*` - for bold - when starting new lists with that setting is irritating. 
As one of the files changed is in the user docs (grouping), I generated the docs locally, and compared them side by side with the published copy. They were identical.
Two markdown files were changed, but there were no …
> docs: Use hyphen for unordered lists

- CONTRIBUTING.md
Some of our developer docs on GitHub have machine-generated tables of contents. This documents how to update them.
Update `CONTRIBUTING.md` with:
- notes on creating screenshots, and 
- how to update the tables of contents in that file, and some others written for contributors.
- So I am no longer the only person knowing how to do these things
- Running them locally.
Not applicable
> chore: Document screenshot and ToC creation in developer docs

- CONTRIBUTING.md
Assorted improvements  to `CONTRIBUTING.md`
- Add 'Linking to other pages in the docs' section
- Add links to docs and tests instructions, for those interested in adding a PR
- Fix the `mdsnippets` command line
To make it easier to add internal links between pages in the user docs
Reviewed in WebStorm preview.
Not applicable
> chore: add 'Linking to other pages in the docs' section

- docs/getting-started/priority.md
- docs/queries/filters.md
- docs/queries/sorting.md
Add cross-linking between multiple references to priority in the documentation.
See the list of commits for details.
I forgot the following comment by @Cito in https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1250#issuecomment-1288781587 - so this PR deals with it, and makes other improvements too:
> Maybe we should mention this also [here](https://obsidian-tasks-group.github.io/obsidian-tasks/queries/filters/#priority) because it's not obvious (although the syntax already shows the order)?
By viewing the docs locally.
> docs: Better cross-linking of info on priority

- src/TaskModal.ts
- src/ui/EditTask.svelte
- styles.css
With this PR I try to arrange the "Create or edit Task" dialog more clearly and nicely.
This is done by:
- Using [whitespace](https://medium.com/successivetech/importance-of-whitespace-in-good-design-de03ea0ab4db) instead of horizontal lines
- Using a grid layout with labels on the left side
This emphasizes the similarity in purpose and function of the date fields. Also, even though whitespace is used to separate the fields, the whole dialog is much smaller and easier to grasp at a glance. And the date fields are not so large that they need the whole horizontal space (contrary to the task description).
For small screen sizes, the layout automatically switches back to a single column.
This PR also enlarges the "Apply" button and adds a "Cancel" button. This makes the apply button abit …
> feat: More clearly arranged layout of the task edit dialog

- src/Config/SettingsTab.ts
The settings dialog has become long and a bit hard to see the structure.
The same is true of the code.
Changes:
- Add some headings in the settings to show the groups of options
- Move the fallback-date settings next to completion-date settings
- Add some comments in code to delimit the sections in settings
Wanting to make the settings easier to understand at a glance
Running locally
> ui: Group related settings together, with headings

- src/Commands/CreateOrEdit.ts
- src/DateFallback.ts
- src/QueryRenderer.ts
- tests/DateFallback.test.ts
Allows a scheduled date that was set automatically to be modified using the edit icon.
Fixes #1300 
- Added unit tests for the logic. 
- Verified that the scheduled date can be modified using the edit button
- Verified that there are no regressions when modifying a task using the edit dialog
> fix: Editing via Pencil can now change auto-scheduled date

- docs/queries/regular-expressions.md
Remove inaccurate statement:
> - Note that tags searches do not yet support regex searches.
>     - As a workaround, search description instead.
Fixes #1310
Previewing edited file locally
> docs: Remove obsolete warning from regex docs - tags now supported

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
Remove some unnecessary all-caps in 2 issue templates
Makes the resultant issues a little easier on the eyes
Can't be tested until merge
> chore: Make issue templates less shouty

- CONTRIBUTING.md
- README.md
This is the next step on #1287, towards removing screenshots from the old location.
- The README file now shows images from `docs/images`, not `resources/screenshots`
- Also removed a missed reference to `resources/screenshots` in CONTRIBUTING
See #1287 for details.
By previewing on WebStorm
> docs: README now uses images in docs/images

- CONTRIBUTING.md
- Edited CONTRIBUTING.md to list the steps to remember when adding a new field to the Task class
- To save me and others have to work it out
- The need to update `Task.identicalTo()` when adding new fields was requested in code review feedback in https://github.com/obsidian-tasks-group/obsidian-tasks/pull/894#discussion_r923406689
By viewing in WebStorm
> chore: Document developer steps to add a new field to Task

- CONTRIBUTING.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
This updates CONTRIBUTING and the Smoke Tests for the improvements made in  #1193.
Share the knowledge that smoke-testing is a lot easier now.
By previewing the edits in WebStorm.
not applicable.
> docs: How to download Tasks-Demo vault with plugin build installed

- docs/how-to/find-tasks-for-coming-7-days.md
- docs/quick-reference/index.md
- Better grouping of instructions in the Quick Reference page
- Also fixed a typo in `find-tasks-for-coming-7-days.md`
For readability of Quick Reference page, and ease of navigation to the Boolean filters docs from there.
Viewing the docs built locally.
Not applicable
> docs: Add row headings to divide up Quick Reference page

- docs/queries/regular-expressions.md
- Document using regex to find empty fields
- Also remove another out-of-date reference to tags and regex searches
The was prompted by the support question in https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1339
Viewing the docs locally.
> docs: Document using regex to find empty fields

- docs/advanced/styling.md
Fix a formatting error in the published docs - 2 lines in a block quote ran together.
> docs: Prevent 2 lines running together in the published docs.

- tests/TestingTools/TaskBuilder.test.ts
- tests/TestingTools/TaskBuilder.ts
This is purely changing helper code in the unit tests.
Now, calling `TaskBuilder.status()`also sets the `TaskBuilder.originalStatusCharacter()`.
I found when writing some tests that used `TaskBuilder.originalStatusCharacter()` and `TaskBuilder.status()` that I was having to call both methods in order to get to a consistent state.
This was tedious and error-prone.
By adding new tests - and running all the existing ones.
> test: Make TaskBuilder handle status consistently

- src/Task.ts
- tests/Task.test.ts
This PR addresses the following discussion topic: https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1011
Added support for numbered checkboxes in obsidian-tasks
Expand the list marker regex to recognize either a - or * as it did before, in addition to a numeric identifier (such as 1.).
There are times when it's useful to create a numbered list of steps that must be followed in a particular sequence that also qualify as tasks that should be checked off when completed. Obsidian already supports numbered checkboxes, this change allows them to also be registered by obsidian-tasks.
Two new tests have been added to Task.tests.ts and both are passing. I've also built obsidian-tasks locally and verified that the change works as intended. To verify I built and installed …
> feat: Add support for numbered checkboxes

- src/Query/Filter/PriorityField.ts
- tests/Query/Filter/PriorityField.test.ts
Improve the parsing of the `priority` instruction
1. **parsing is more precise**: lines such as the following were accepted previously, and now are not:
- `priority is abovemedium`
- `priority is above medium-with-nonsense-at-end` (user may have thought that could add something meaningful after `medium` here)
1. **parsing is more forgiving**: words in `priority` filters may be separated by multiple spaces, and tab characters are recognised as whitespace too.
Responding to really helpful code review feedback from @cito in #1365, which turned out to apply to the existing code, so I decided to put it in a separate PR.
Each individual change to the regular expression in `PriorityField` was made after a failing test was added, to be sure that each …
> fix: make parsing of priority filter more precise and more forgiving

- src/Commands/CreateOrEditTaskParser.ts
- src/Commands/ToggleDone.ts
- src/Task.ts
- tests/Commands/CreateOrEditTaskParser.test.ts
- tests/Commands/ToggleDone.test.ts
- tests/Task.test.ts
When parsing task lines, the code now retains the list marker, which will be one of:
- a hyphen: `-`
- an asterisk: `*`
- a number with a full-stop: `5.`, for example
Changes in behaviour:
- This fixes all the example problems in #1371
- toggling tasks on lines beginning `*` retains the `*`
- toggling tasks on lines beginning `1.` retains the `1.`
- Editing tasks with any of the above list markers retains the marker, instead of converting it to `-`
Fixes #1371 - Tasks should retain knowledge of whether the task line starts with hyphen or asterisk.
And also improves the behaviour of #1363 - Add support for numbered checkboxes.
- Extensive test added, both here and in previous PRs.
- Manually test in Obsidian, including testing the samples in #1371.
Internal …
> fix: Editing & toggling task starting * or 1. reverted them to -

- src/Query/Filter/StatusField.ts
- src/Query/Query.ts
- src/Query/Sort.ts
- tests/Query.test.ts
- tests/Query/Filter/StatusField.test.ts
- tests/Sort.test.ts
- StatusField now implements 'sort by status'
- Lots of comments added to show where I'm going with this series of refactorings.
- Removed a test of parsing of sort instructions which was totally focused on implementation details, and was fragile when Sorting's fields changed. This will be replaced by later individual tests of each sort function in each Field.
This is step 2 in splitting out all the sort functions to the relevant fields, to make it easier to add new sort instructions, and to be able to re-use the sort code to sort groups in reverse order.
- By running existing tests
> refactor: StatusField now implements 'sort by status'

- src/Query/Filter/DueDateField.ts
- src/Query/Filter/StatusField.ts
- src/Query/Query.ts
- src/Query/Sort.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/StatusField.test.ts
- tests/Sort.test.ts
- `DueDateField` now implements `sort by due`
- There is a lot of duplication of code now, which will be removed in a later step.
This is step 3 in splitting out all the sort functions to the relevant fields, to make it easier to add new sort instructions, and to be able to re-use the sort code to sort groups in reverse order.
- By running existing tests
> refactor: DueDateField now implements 'sort by due'

- src/Query/Filter/DueDateField.ts
- src/Query/Filter/Field.ts
- src/Query/Filter/StatusField.ts
- src/Query/FilterParser.ts
- src/Query/Query.ts
- src/Query/Sort.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/PriorityField.test.ts
- tests/Query/Filter/StatusField.test.ts
- Add Sorting interface and implementations to `Field`
- Most of Sorting-related methods in `DueDateField` and `StatusField` now not needed
- `FilterParser` code for parsing a sort instruction is now a lot simpler
The next stage will be breaking cyclic links between files, as this is presently a lot of the next refactoring stages.
This is step 4 in splitting out all the sort functions to the relevant fields, to make it easier to add new sort instructions, and to be able to re-use the sort code to sort groups in reverse order.
- By running existing tests
> refactor: Reduce repetition in new sorting code

- tests/CustomMatchers/CustomMatchersForSorting.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/StatusField.test.ts
- tests/Sort.test.ts
The focus of this PR is to make it easier to write expressive tests for testing sorting of Task  and date objects.
- Create `tests/CustomMatchers/CustomMatchersForSorting.ts`
- This has the following for testing sorting of date values - based on functions that were previously in `tests/Sort.test.ts`
- `expectDateComparesBefore()`
- `expectDateComparesEqual()`
- `expectDateComparesAfter()`
- And this for testing sorting via `Sorting` objects
- `expectTaskComparesBefore()`
- `expectTaskComparesEqual()`
- `expectTaskComparesAfter()`
- `tests/Query/Filter/DueDateField.test.ts`
- reworked to use these new functions
- `tests/Query/Filter/StatusField.test.ts`
- More tests added
This is step 6 in splitting out all the sort functions to the relevant fields, to make it easier to add new sort …
> test: Add Jest support for easier testing of sorting

- src/Query/Filter/DateField.ts
- src/Query/Filter/DescriptionField.ts
- src/Query/Filter/DueDateField.ts
- src/Query/Filter/PathField.ts
- src/Query/Filter/PriorityField.ts
- src/Query/Filter/UrgencyField.ts
- src/Query/FilterParser.ts
- src/Query/Query.ts
- src/Query/Sort.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/DoneDateField.test.ts
- tests/Query/Filter/PathField.test.ts
- tests/Query/Filter/PriorityField.test.ts
- tests/Query/Filter/ScheduledDateField.test.ts
- tests/Query/Filter/StartDateField.test.ts
- tests/Query/Filter/UrgencyField.test.ts
- tests/Sort.test.ts
**This PR**
- Each step of this PR involved:
- Picking a symbol from `Query.SortingProperty`
- Making sure test coverage of the corresponding `Field` implementation was good enough
- Moving the corresponding `Sort.compare...` implementation (and any associated helper functions) to new sort methods in the `Field` implementation
- Remove the field name from `Query.SortingProperty` and `Query.sortByRegexp`
- Removing all traces of the field name from `Sort`
- Updating any tests that used the old `Sort.makeLegacySorting(...)` to `new PathField().createNormalSorter()` or similar.
- All remaining `sort by` instructions except `sort by tag` are now implemented in classes derived from `Field.`
- The only remaining legacy sort function is `sort by tag`
- This involved adding `UrgencyField` - which …
> refactor: Field classes do all 'sort by' options except 'tag'

- src/Query/Filter/Field.ts
- src/Query/Sort.ts
- src/Query/Sorting.ts
- tests/Query/Filter/TagsField.test.ts
- tests/Sort.test.ts
- Added test which proved the bug existed
- Each `sort by tag` comparator stores its own tag number
- instead of them all using a single global tag number - which was stored in `Sort.tagPropertyInstance`
- Removed the `propertyInstance` field from `Sorting`, as no longer used
This fixes #1407
"Multiple 'sort by tag' lines ignore all but last one"
- By adding a failing test and then showing that it now gives the right answer
- Checking the existing tests still pass
> fix: Multiple 'sort by tag' lines ignore all but last one

- src/Query/Filter/Field.ts
- src/Query/Filter/TagsField.ts
- src/Query/FilterParser.ts
- src/Query/Query.ts
- src/Query/Sort.ts
- tests/Query/Filter/Field.test.ts
- tests/Query/Filter/TagsField.test.ts
**Bigger changes**
- `TagsField` now implements sorting
- All original code for sorting individual fields now removed from `Query` and `Sort`
- `Sort`'s only responsibilities now are:
- Provide the list of default comparators
- Make a composite comparator
**Supporting changes**
- Add `Field.parseSortLine(line)` and a few supporting methods
- This allows things like `new TagsField().parseSortLine('sort by tag reverse 2')!`
- Add `Field.fieldNameSingular()`
- Needed because `TagsField.fieldName()` is `tag/tags`
- Unit tests of `Field` sort-related code added
- Unit tests of `TagsField` sort-related code added
This is step 9 in splitting out all the sort functions to the relevant fields, to make it easier to add new sort instructions, and to be able to re-use the sort code to sort groups in …
> refactor: TagsField now implements 'sort by tag'

- .github/ISSUE_TEMPLATE/feature-request.yaml
Fixed broken link to 'Ideas in Discussions' in the Feature Request template.
fixes #1410
> fix: Feature Request template link 'Ideas in Discussions' was broken

- .github/workflows/codeql-analysis.yml
This is part of fixing addressing #1415.
Enable manual running of codeql-analysis.yml CI.
If I can confirm that I can trigger it manually, then I can run it as release preparation, instead of waiting on every PR build, for something is very slow and almost never fails.
This is part of fixing addressing #1415, which explains the motivation and pain points behind this.
It will be tested after merge.
not applicable.
> chore: Enable manual running of codeql-analysis.yml CI

- .github/workflows/codeql-analysis.yml
- CONTRIBUTING.md
1. Turn off running of CodeQL on PRs and merges, to speed up PRs
2. Document running CodeQL before each release
/CC @schemar for info.
Fixes #1415, which explains the motivation. This will greatly increase my development turnaround, whilst still running these checks before each release.
In theory this will also run a weekly cron job - although that trigger has been there for some time and is not actually running.
Maybe this edit to the file will enable it???
By first adding a manual trigger to the CodeQL action (see #1416) and then using it to do a manual run of CodeQL to confirm that manual execution really does work.
> chore: Faster PRs by running CodeQL on release

- docs/_sass/custom/custom.scss
The Quick Reference table, especially, was quite hard to glance over quickly due to the inconsistent vertical alignment.
Made the text in all tables in the User Guide easier to read by top-aligning all content.
This especially makes the Quick Reference page more readable.
I'm filling in gaps in the quick reference - it was too hard to read quickly.
By building docs locally.
_Caption: Before on the left - After on the right_
Not applicable
> docs: Tables in docs now easier to read, as aligned

- docs/queries/grouping.md
- src/Query/Group.ts
- tests/Group.test.ts
_Copy paste from original pull request #1418, first part of the discussion is there_
Hello. First of all thanks a lot for your work on the plugin that I enjoy a lot. Please note I'm not an active programmer nowadays and JS is not my main competence, I just wish to contribute as much as I can and bring the functionalities I need myself instead of asking others to spend their time. If I have done something wrong please let me know how to fix that.
Add another option for group by - filelink = [[filename]]
When grouping by filename, the backlinks are redundant information, so they could/should be hidden by the user. However it would be good to have a link somewhere to the file, where the task is described. This mode permits to have this functionality
I did run the plugin in my Obsidian setup. …
> feat: 'group by filename' now links to the note

- src/Query/Query.ts
- src/Query/Sort.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/TagsField.test.ts
- tests/Sort.test.ts
Remove cyclic dependency between Query and Sort.
This simplifies the code for calling `Sort.by()`, by allowing a simple list of `Sorter` objects to be passed in, instead of requiring an object that contains a sorting that gives a list of `Sorter` objects.
Mainly I wanted to remove one of the 15 current cyclic dependencies in `src/`.
However, another benefit is that the code for calling `Sort.by()` is now a lot less opaque.
By running all the tests.
> refactor: Remove cyclic dependency between Query and Sort

- src/Query/Filter/PathField.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/PathField.test.ts
Make 'sort by path' ignore capitalisation
Also add more tests of 'sort by description' to show that it ignores case.
Fixes #1432.
Updating unit tests.
Once this PR has built the plugin, I will test it manually as well.
> fix: Make 'sort by path' sort ignoring capitalisation

- src/Query/Filter/DescriptionField.ts
- tests/Query/Filter/DescriptionField.test.ts
- fix: Prevent 'sort by description' from duplicating text
- This fixes the incorrect regex used when attempting to remove bold and italic formatting.
- fix: The removal of ** for bold no longer leaves a stray *
- fix: The removal of [[ for links no longer leaves a stray ]
- fix: Recognise `_italic_` and `__bold__` formatting
- fix: Don't allow formatting of empty strings
Also added multiple extra tests.
Note that this is not a perfect parsing of markdown.
For example with this:
`**hello * world**`
It would be nice for that to become:
`hello * world`
But it remains unchanged, because the search pattern does not allow any occurrences of the formatting character inside the formatted string.
This fixes #1431.
By adding new tests and running existing ones.
I will test manually once this PR …
> fix: Improve stripping of format chars in 'sort by description'

- src/Query/Filter/DescriptionField.ts
- src/Query/Filter/TagsField.ts
- src/Query/Filter/TextField.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/FilenameField.test.ts
- tests/Query/Filter/HeadingField.test.ts
- tests/Query/Filter/PathField.test.ts
- tests/Query/Filter/TagsField.test.ts
- fix: Sort numbers in filename, heading and path correctly
- fix: Sort numbers in description correctly
- fix: Sort numbers in tags correctly
Fixes #1429.
By adding and updating tests.
With these tasks:
```
```
And this tasks block:
````
```tasks
filename includes number sorting
sort by description
```
````
**Before**
**After**
> fix: Sorting by text fields now sorts numbers correctly

- resources/sample_vaults/Tasks-Demo/Manual Testing/Custom Task Statuses.md
- src/Query/Filter/StatusField.ts
- src/Query/Group.ts
- src/Status.ts
- tests/Status.test.ts
1. Add `StatusConfiguration` & `Status` and their tests from [obsidian-tasks-x](https://github.com/sytone/obsidian-tasks-x).
Behaviour is unchanged.
Credit: This is a copy of the code and tests in @sytone's fork https://github.com/sytone/obsidian-tasks-x on its `main-tasks-sql` branch.
Note: Initially only `Status.DONE` and `Status.TODO` have been copied over, to maintain parity with the existing behaviour in Tasks and keep this as a pure refactoring.
The revision copied from is:
https://github.com/sytone/obsidian-tasks-x/commit/2c0b659457cc80806ff18585c955496c76861b87
Co-Authored-By: Sytone <1399443+sytone@users.noreply.github.com>
2. Added `resources/sample_vaults/Tasks-Demo/Manual Testing/Custom Task Statuses.md`.
This is preparation for adding support for more task status types - …
> refactor: Add StatusConfiguration & Status from obsidian-tasks-x

- src/Status.ts
- src/StatusRegistry.ts
- src/Task.ts
- tests/StatusRegistry.test.ts
- tests/Task.test.ts
This is the first in a series of steps to adopt use of the `StatusRegistry` from obsidian-tasks-x.
The changes were:
- fix: Add support for task lines with unknown characters in []
- refactor: Add most of `StatusRegistry` from obsidian-tasks-x
- test: Make `Task.toggle()` tests check number of tasks returned
- refactor: `Task.fromLine()` and `Task.toggle()` now use `StatusRegistry`.
- refactor: Copy in most of remaining `StatusRegistry` tests
- comment: Update a comment that was out-of-date
- refactor: Remove optional status parameter from `Task.toggle()`
- Completion of `Todo`
- In obsidian-tasks-x, `Todo` goes to `In Progress`.
- In obsidian-tasks, `Todo` goes to `Done`, for consistency with the existing released behaviour. (Users will later have the option to adopt `In Progress` if …
> refactor: Partial adoption of StatusRegistry from obsidian-tasks-x

- src/Commands/ToggleDone.ts
- src/Task.ts
- tests/Commands/ToggleDone.test.ts
Update the 'Toggle task done' command to use StatusRegistry, and honour custom statuses.
This fixes a bug that existed in the obsidian-tasks-x code that:
- when there was a global filter,
- and there was a task that:
- used a custom status with a Capital letter,
- and did not match the global filter
- then when the task was toggled with 'Toggle task done':
- the original custom status character was lower-cased
- so the wrong next status was chosen.
Moving towards removing `Task.originalStatusCharacter`.
By adding new tests and running existing ones.
> refactor: Update 'Toggle task done' command to use StatusRegistry

- src/StatusRegistry.ts
- tests/StatusRegistry.test.ts
- tests/Task.test.ts
This fixes some confusing nested Status objects returned from StatusRegistry.
I have found equality tests on `Status` objects obtained from the `StatusRegistry` were failing confusingly because `Status` objects returned from `StatusRegistry` had a duplicate nested `configuration` field, and I didn't understand why.
It turned out that the code in obsidian-tasks-x was offering the convenience of adding either `StatusConfiguration` or `Status` to the `StatusRegistry`, but was not checking the type passed in. This meant that if a Status was added, what was saved was `Status(Status(StatusConfiguration))`.
This is why the code from obsidian-tasks-x which I added in 3d67b00ceca17842a31c86e8a7f1db33d0bbba9d had to do all the converting from:
```ts
    …
```
> fix: Fix an unreleased error in StatusRegistry

- docs/getting-started/auto-suggest.md
- docs/getting-started/create-or-edit-task.md
- docs/getting-started/dates.md
- docs/getting-started/priority.md
- docs/getting-started/recurring-tasks.md
- docs/getting-started/statuses.md
- docs/getting-started/use-filename-as-default-date.md
This is an evolving page for:
- documenting statuses and custom statuses
- crediting @sytone for the work that enabled the capability
- letting 'Tasks SQL Powered' users know of any differences in 'Tasks'.
Start capturing user-focussed info on custom statuses as I discover things to mention...
Viewing docs locally.
> docs: Start documenting custom statuses

- docs/getting-started/statuses.md
- package.json
- src/Status.ts
- src/StatusRegistry.ts
- tests/DocsSamplesForStatuses.test.DefaultStatuses_markdown-table.approved.md
- tests/DocsSamplesForStatuses.test.ts
- tests/StatusRegistry.test.ts
This adds support and docs for 'In Progress' + 'Cancelled' statuses.
Notes:
- Users will need to install a Theme or Snippet for the new statuses to be visually distinguishable.
- The new documentation that has been added contains a machine-generated markdown table of supported statuses, created by using ApprovalTests.
- This process does need to be better documented for contributors, and automated (to avoid needing to run MarkdownSnippets by hand).
- For now, search for MarkdownSnippets in CONTRIBUTING.md 
Credit: Some of this PR is a copy of some code and tests in @sytone's fork https://github.com/sytone/obsidian-tasks-x on its `main-tasks-sql` branch.
The revision copied from is:
https://github.com/sytone/obsidian-tasks-x/commit/2c0b659457cc80806ff18585c955496c76861b87
Co-Authored-By: …
> feat: Add & document 'In Progress' + 'Cancelled'

- src/TaskModal.ts
- src/ui/EditTask.svelte
Fixed a few things I found when exploratory-testing the new Status dropdown in the Edit modal.
- Show the status character in dropdown list - for example, `In Progress [/]` instead of `In Progress`.
- Show '[X]' as completed, in addition to '[x]'
- Better behaviour in Edit modal with unknown status
- Previously, if editing a task with an unknown status (for example, [%]) the status dropdown would start empty, and if another status was selected, it would not be possible to return to the initial value.
- Now, unknown status is shown in the dropdown as 'Unknown [%]',
and is selectable.
Just improving usability, especially as people adopt this feature and before they have started (eventually) customising their statuses.
Extensive local testing in Obsidian.
> fix: Address minor usability issues when editing status

- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- src/Config/settingsConfiguration.json
- styles.css
The 'Tasks SQL Powered' fork of Tasks uses a JSON file to specify almost all of the content of its Settings pane.
This mechanism will be needed in order to port over its code for allowing users to customise the custom task statuses they wish to use.
In preparation for pulling in the task statuses settings, I have pulled in the code for populating settings from a JSON file.
In order to test this, I put in a temporary place-holder setting for where the statuses will be placed.
Notes:
- All the existing settings UI code is unchanged. It can be ported to the JSON mechanism separately in future.
- One advantage of doing this port is that it will then allow the existing settings sections to be collapsible, which is convenient.
Credit: Much of this code in this pull request is a derived copy of …
> feat: adopt tasks-x's JSON settings facility

- src/Config/CustomStatusModal.ts
- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- src/Config/settingsConfiguration.json
- src/main.ts
This adds a new section in settings to allow users to edit the available custom statuses.
It basically works really very well indeed. There are a few infelicities in the error-checking that will need fixing before release, but it it's a brilliant body of work - thank you @sytone 🙏 🎉 .
Credit: This is a partial copy of the code in @sytone's fork https://github.com/sytone/obsidian-tasks-x on the `main-tasks-sql` branch.
The revision copied from:
https://github.com/sytone/obsidian-tasks-x/commit/2c0b659457cc80806ff18585c955496c76861b87
Co-Authored-By: Sytone <1399443+sytone@users.noreply.github.com>
Essential new feature for support of custom task status types.
It has been requested many times, including:
- https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/312
- …
> feat: Enable adding & editing of custom statuses

- tests/Query/Filter/DateField.test.ts
- tests/Sort.test.ts
I'd been meaning to pick up these TODOs in Sort.test.ts that were left over from:
- 747e5d9ac9e2121c99e573f1c59ec305211dee1a
- 1eee0d66df0a61bf608b16a68641bf78d10ce8e0
Just trying to make the code a little bit better.
By running the tests, and confirming that the removed tests did have equivalents elsewhere in the project.
> test: Address 5 TODOs in Sort.test.ts

- src/Config/SettingsTab.ts
Extract function `createRowForTaskStatus()`, so it can be re-used later on.
- Partly to shorten `SettingsTab.insertTaskStatusSettings()` further
- Mainly because I want to allow users to edit the `TODO` status, to have the ability to turn on `TODO` -> `IN_PROGRESS` -> `DONE` -> `TODO`
- And I think I will need the ability to re-use `createRowForTaskStatus()` for that.
Manually in Obsidian.
> Refactor status settings more

- src/Config/SettingsTab.ts
- src/Config/settingsConfiguration.json
I am trying to move towards enabling editing of the 'next symbol' for the core/standard statuses (TODO, IN_PROGRESS, DONE, CANCELLED).
As a first step, this replaces the previous HTML list of standard statuses with a new block in settings, that presents them in the same way as the custom ones are shown - but with no delete and edit buttons.
This also now initially shows the status settings blocks as open, for discoverability when it is first released.
See above
> feat: Show core statuses, read-only

- src/Config/CustomStatusModal.ts
- src/Config/StatusSettingsHelpers.ts
- src/Status.ts
The statuses UI provides an 'Available as command' feature, but that facility is not yet implemented in Tasks. (See #1486).
So this PR hides the 'Available as command' bits in the statuses UI.
This fixes #1487.
By running the plugin locally.
**The list of available statuses:**
**The modal for editing a status:**
**The list of available statuses:**
**The modal for editing a status:**
> fix: Hide UI for status commands

- src/StatusRegistry.ts
- tests/StatusRegistry.test.ts
Make StatusRegistry easier to test.
The constructor is now public, so that tests can be written without changing global state.
Docs and comments added to explain this in the code.
Fixes #1485.
By running the existing tests.
Helpfully, the one that tested toggling of non-standard statuses initially failed, showing that it should be adjusting the global StatusRegistry. Comments added to clarify this.
> refactor: Make StatusRegistry easier to test

- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- src/Config/StatusSettings.ts
- src/Config/StatusSettingsHelpers.ts
- src/Status.ts
- src/main.ts
- tests/Config/StatusSettings.test.StatusSettings_verify default status settings.approved.json
- tests/Config/StatusSettings.test.ts
Introduce new `StatusSettings` class to encapsulate the code for reading and using the settings for custom statuses.
The visible behaviour of the status settings is unchanged. But the name of the setting has had to change - from `statusTypes` to `statusSettings` - because of the changed storage.
> Important: In the unlikely event that anyone other than me is running this code, any custom statuses will need to be recreated.
> This can be done by copying-and-pasting within the plugin's `data.json` settings file.
> (At this development stage, it wasn't worth spending time worrying about implementing backwards compatibility)
This is encapsulation and testing is in preparation for fixing a number of the remaining bugs and inconsistencies in the code for editing statuses. …
> refactor!: Encapsulate & test custom status settings code

- src/Config/SettingsTab.ts
Status changes are now applied immediately.
Users no longer need to restart Obsidian to test out edits to custom statuses.
This has been driving me nuts!
Manually
> fix: Status changes now applied immediately!

- src/Status.ts
- src/Task.ts
- tests/Status.test.ts
- tests/StatusRegistry.test.ts
If toggling TO an unknown status, Tasks now honours the requested next character, instead of breaking the task with an empty `[]`.
Fixes #1499
- Adding unit test which failed before the bug was fixed
- Testing the new behaviour manually in Obsidian.
> fix: toggling to unknown status now gives valid task

- docs/_config.yml
- docs/getting-started/statuses.md
- docs/how-to/set-up-custom-statuses.md
- Enable callouts mechanism in the docs
- Add some info and warnings about many aspects of the custom statuses feature (and its documentation)
Part of #1497
By viewing the docs locally.
Some example callouts added:
> docs: Add info and warnings about custom status feature

- src/Query/Filter/StatusNameField.ts
- tests/Query/Filter/StatusNameField.test.ts
I realised that the parsing of `status.name` as a new field would accidentally match any character where the `.` is.
This makes the parsing stricter, to avoid accidentally ending up having to support mis-spellings in user vaults for ever more.
Make parsing more accurate. This is a not-yet-released feature.
Add and running tests.
> fix: No longer accept 'status-name' and similar instead of 'status.name'

- src/Query/FilterParser.ts
- tests/Query.test.ts
Fix a bug found in manual testing, that 'sort by status.name' was treated as 'sort by status' in queries.
Added an integration test to show the problem.
Bug in unreleased code.
Via integration test, and manual testing in demo vault.
> fix: 'sort by status.name' was treated as 'sort by status' in queries

- resources/sample_vaults/Tasks-Demo/Stress Test/.gitignore
- resources/sample_vaults/Tasks-Demo/Stress Test/Stress Test Readme.md
- scripts/stress_test_obsidian_tasks.py
Add `stress_test_obsidian_tasks.py`.
It generates a bunch of files with tasks in `resources/sample_vaults/Tasks-Demo/Stress Test`.
This is useful for quickly generating large numbers of tasks, for testing purposes.
I've been running this on my development machine, but it was useful for a bugfix, so I'm adding it to the vault.
For more info, see the new file `resources/sample_vaults/Tasks-Demo/Stress Test/Stress Test Readme.md`.
To help me explore the root cause of Queries stuck on "Loading Tasks ...": #829
By running it locally and experimenting with the parameters in the script.
> chore: Add stress_test_obsidian_tasks.py

- src/Config/CustomStatusModal.ts
- src/Status.ts
- styles.css
- tests/Status.test.ts
Essential fix for first release of custom statuses feature.
Fixes problem that if the status symbol was invalid, the modal removed the status symbol text field.
I was unable to prevent this, so now, colouring is used to indicate if there is an error.
Summary of changes:
- `StatusConfiguration` class now provides methods for validating individual fields and the whole object
- `CustomStatusModal` now:
- uses the above validating code to highlight any incorrect values in red as the user edits the status
- and when user clicks the checkbox, any errors are displayed in a notice.
Thanks to @Fevol for help with the red colours to show errors.
Fixes #1498
- Unit tests added for the actual validation messages for the status
- Extensive manual testing of the behaviour of the edit dialog
Changes …
> Fix edit status error validation

- src/Config/SettingsTab.ts
- src/Config/settingsConfiguration.json
- styles.css
Improve wording & fix styling in status settings
- Descriptions of 2 status sections - see red arrows in image below
- Explain how duplicate symbols are (not) handled
- Improve the styling of these two descriptions
- Remove excessive vertical height in the row for each status
- See the blue arrows in the image below.
To get it to the stage where I would be comfortable to release it.
By running the plugin locally.
> fix: Improve wording & fix styling in status settings

- src/Config/CustomStatusModal.ts
- src/Config/SettingsTab.ts
- src/Config/StatusSettingsHelpers.ts
- src/Status.ts
- src/StatusConfiguration.ts
- src/StatusRegistry.ts
- tests/Status.test.ts
- tests/StatusConfiguration.test.ts
- tests/StatusRegistry.test.ts
- Create static factory functions/named constrictors in StatusConfiguration for each of the static constants in Status
- Where easy to do so, update existing code to use the new functions
This is working toward making the core status somewhat modifiable.
- Using existing tests, and adding some more.
- Tested manually in Obsidian
> refactor: Add factory methods to StatusConfiguration

- src/Commands/CreateOrEditTaskParser.ts
- src/StatusRegistry.ts
- src/Task.ts
- tests/Commands/CreateOrEditTaskParser.test.ts
- tests/StatusRegistry.test.ts
- Fix a bug that any custom status was lost if the Edit task modal was used to add a global filter to a task that had a status symbol other than ` ` or `x`.
- Create `StatusRegistry.byIndicatorOrCreate()` and updated existing code to use it, to remove repetition in the bug fix
Fixes #1488
- By adding a failing test
- By testing manually in local Obsidian
> fix: with global filter, the modal was losing custom status symbols

- resources/sample_vaults/Tasks-Demo/Settings Files/data 1.22.0.json
- resources/sample_vaults/Tasks-Demo/Settings Files/data 1.23.0-pre-release-build-1.json
- src/Config/CustomStatusModal.ts
- src/Config/SettingsTab.ts
- src/Status.ts
- src/StatusConfiguration.ts
- src/StatusRegistry.ts
- src/StatusValidator.ts
- tests/Status.test.ts
- tests/StatusConfiguration.test.ts
- tests/StatusRegistry.test.ts
- tests/StatusValidator.test.ts
- See #1535 for details. In what I thought were safe refactorings, I had broken reading of status settings by putting some methods on `StatusConfiguration` that were missing when the custom statuses were read from data.json.
- Also added some saved settings files from different Tasks versions, to enable manual testing for backwards-compatibility of settings-reading.
Fixes #1535
By running in Obsidian
> bug: reading of status settings now works again

- docs/getting-started/statuses.md
- docs/how-to/set-up-custom-statuses.md
- src/Config/CustomStatusModal.ts
- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- src/Config/StatusSettings.ts
- src/Status.ts
- src/StatusConfiguration.ts
- tests/DocsSamplesForStatuses.test.DefaultStatuses_core-statuses.approved.md
- tests/DocsSamplesForStatuses.test.DefaultStatuses_important-cycle.approved.md
- tests/DocsSamplesForStatuses.test.DefaultStatuses_its-theme-supported-statuses.approved.md
- tests/DocsSamplesForStatuses.test.DefaultStatuses_minimal-supported-statuses.approved.md
- tests/DocsSamplesForStatuses.test.ts
- tests/Status.test.ts
- Add enum `StatusType`:
```js
export enum StatusType {
TODO = 'TODO',
DONE = 'DONE',
IN_PROGRESS = 'IN_PROGRESS',
CANCELLED = 'CANCELLED',
NON_TASK = 'NON_TASK',
EMPTY = 'EMPTY',
}
```
- Each status now has one StatusType value
- Edit Status modal now allows editing of type
In my own vault I have struggled to use the new statuses, because I have no control over which statuses are treated as Done. Some of my custom statuses represent tasks that are incomplete, and they are currently excluded by `not done` queries.
This is a partial attempt at giving users control over this.
- New tests
- Running in Obsidian
> feat: Add status categories/types to eventually control behaviour

- src/TaskLineRenderer.ts
Fix bug that unchecked tasks were rendered as checked in Reading view.
Fixes #1537
In my local vault.
Now fixed:
> fix: unchecked tasks are now correct in Reading view

- docs/getting-started/statuses.md
- docs/how-to/set-up-custom-statuses.md
- docs/queries/filters.md
- src/Query/Filter/StatusField.ts
- tests/CustomMatchers/CustomMatchersForFilters.ts
- tests/DocsSamplesForStatuses.test.Status_Transitions status-types.approved.md
- tests/Query/Filter/StatusField.test.ts
- `NON_TASK` no longer matches either `done` or `not done`
- `IN_PROGRESS` now matches `not done` instead of `done`
- `done` now matches `IN_PROGRESS` and `IN_PROGRESS `
- `not done` now matches `IN_PROGRESS` but does not match `NON_TASK`
Also, multiple documentation updates in this area.
I agonised for ages over whether to call this a breaking change.
Technically it is, as the results of `done` and `not done` change.
However, on reflection I genuinely feel that it is an improvement, and in-progress tasks will show up in the most common search, `not done`, which they did not previously.
In the unlikely event that users are concerned about this, I have documented how to restore the original behaviour by customising task statuses.
To smooth the adoption of custom statuses, so users can …
> feat: update 'done' and 'not done' for new status types

- src/StatusRegistry.ts
- tests/StatusRegistry.test.ts
Fix issue that 'Add All Unknown Status Types' was creating duplicates.
I thought that Set would prevent duplicates, if there were several tasks with an un-registered status symbol. It didn't.
See above.
With better tests.
And testing it manually in my main vault.
What the bug looked like. There should have been only 1 of each unique row.
> fix: 'Add All Unknown Status Types' was creating duplicates

- src/Commands/CreateOrEditTaskParser.ts
- src/Commands/ToggleDone.ts
- src/Config/CustomStatusModal.ts
- src/Config/Settings.ts
- src/Config/StatusSettings.ts
- src/Query/Filter/StatusField.ts
- src/Query/Group.ts
- src/Status.ts
- src/StatusCollection.ts
- src/StatusConfiguration.ts
- src/StatusRegistry.ts
- src/StatusValidator.ts
- src/Task.ts
- src/TaskLineRenderer.ts
- src/TaskModal.ts
- src/ui/EditTask.svelte
- tests/DocsSamplesForStatuses.test.ts
- tests/Status.test.ts
- tests/StatusRegistry.test.ts
- tests/StatusValidator.test.ts
- tests/Task.test.ts
- tests/TestingTools/TaskBuilder.ts
There has been a discrepancy in vocabulary between the status code - which talks about `indicator` characters - and the UI and docs - which talk about `symbol` characters.
This PR converts every use of `indicator` in the code and settings to `symbol`.
Users will need to recreate their custom statuses - or make a copy of `data.json` and apply some global edits.
I've documented this for testers in:
- https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1530#discussioncomment-4737556
- https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1530#discussioncomment-4737663
Fix #1558 - which describes the motivation.
- Manual testing in Obsidian
- For users who tested the earlier builds, this is a breaking change. But not for …
> refactor: Rename indicator to symbol throughout

- docs/getting-started/statuses.md
- docs/queries/filters.md
- src/Query/Filter/StatusField.ts
- tests/DocsSamplesForStatuses.test.Status_Transitions status-types.approved.md
- tests/Query/Filter/StatusField.test.ts
If the user has set up any statuses with type `NON_TASK`, tasks in this status will now match `done` filters.
This makes the current code behave more like previous releases.
Fixes #1562
- Unit tests
> fix: Make NON_TASK statuses match 'done'

- src/Config/CustomStatusModal.ts
- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- src/Config/StatusSettings.ts
- src/Config/settingsConfiguration.json
- src/StatusRegistry.ts
- tests/Commands/ToggleDone.test.ts
- tests/Config/StatusSettings.test.StatusSettings_verify default status settings.approved.json
- tests/Config/StatusSettings.test.ts
- tests/StatusRegistry.test.ts
- tests/Task.test.ts
This adds the ability to edit core statuses.
It's best understood by reviewing the individual commits, but basically:
- `StatusSettings`
- now has another array which it currently calls `coreStatusTypes` and is initialised to the 4 standard statuses.
- its 2 arrays are now readonly, because the callbacks on the status Edit and Delete buttons hold on to the appropriate status list from `StatusSettings`.
- many of its static methods had to be updated to pass in the appropriate list of statuses - core or custom.
- `StatusRegistry` needed a way to delete the 4 default statuses it previously always imposed.
- `CustomStatusModal` only allows the symbol to be modified for custom statuses, not core ones.
Some users want to be able to make `space` -> `/` -> `x`, and this makes that possible.
- …
> feat: Add ability to edit core statuses

- src/Config/SettingsTab.ts
- src/Config/StatusSettings.ts
- src/Config/settingsConfiguration.json
- tests/Config/StatusSettings.test.StatusSettings_verify default status settings.approved.json
- tests/Config/StatusSettings.test.ts
- Move '-' and '/' to custom statuses section
- Improve the wording on core and custom statuses sections
- The button for deleting custom statuses is now called reset instead, as it restores the two '-' and '/' buttons.
(This replaces #1568 which I closed because one of the commits had an incorrect message.)
This makes a clear separation between the buttons that need custom CSS and the ones that don;'t.
- Manually
- With unit tests
> feat: Move '-' and '/' to custom statuses

- src/Status.ts
- tests/Status.test.ts
I've been struggling to read the jagged words in statuses in settings, so this aligns the text better.
Specifically, the fixed-width text is shown first now.
In an ideal world, this would all be a table with inline editing, but that's a step too far right now.
An example of the difference:
Example before:
```
"- [ ] Todo, next status is 'x', type is 'TODO'. "
"- [-] Cancelled, next status is ' ', type is 'CANCELLED'. "
"- [/] In Progress, next status is 'x', type is 'IN_PROGRESS'. "
```
Example after:
```
"- [ ] => [x], name: 'Todo', type: 'TODO'."
"- [-] => [ ], name: 'Cancelled', type: 'CANCELLED'."
"- [/] => [x], name: 'In Progress', type: 'IN_PROGRESS'."
```
See above
- Updating tests
- Running it on Mac
- Running it on iPhone
> feat: Make statuses more readable in settings

- resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
Update data.json to 1.23.0 format.
This will be useful in testing future changes, to make sure we can still read the 1.23.0 settings version, to check for backwards compatability.
In the demo vault.
> vault: Update data.json to 1.23.0 format

- src/Config/SettingsTab.ts
- src/StatusValidator.ts
- tests/DocsSamplesForStatuses.test.ts
- tests/StatusValidator.test.ts
There is a certain amount of manual editing involved in creating the data that goes in to the data behind each of the 'Add all Status Types for ... Theme' buttons in Custom Status Settings.
I was checking it by eye, but now the checks are built in to the tests that generate the per-theme files that get embedded in to the documentation, so any inconsistencies will be found before release.
- Adding more tests
- Running it on the un-released files for adding support for Ebullientworks theme. It found the errors very quickly, making the process much quicker.
These do not affect the validation that users see in the 'Edit status' modal - that is unchanged.
- [] **Infrastructure** (prefix: `chore` - examples include GitHub Actions, issue templates)
- Sort of... It adds checks …
> chore: Improve internal validation of theme status collections

- docs/reference/status-collections/aura-theme.md
- docs/reference/status-collections/ebullientworks-theme.md
- docs/reference/status-collections/its-theme.md
- docs/reference/status-collections/minimal-theme.md
- docs/reference/status-collections/slrvb-alternate-checkboxes-snippet.md
- docs/reference/status-collections/things-theme.md
- src/Config/Themes/AuraThemeCollection.ts
- src/Config/Themes/EbullientworksThemeCollection.ts
- src/Config/Themes/ITSThemeCollection.ts
- src/Config/Themes/MinimalThemeCollection.ts
- src/Config/Themes/ThingsThemeCollection.ts
- tests/DocsSamplesForStatuses.test.Theme_Aura Table.approved.md
- tests/DocsSamplesForStatuses.test.Theme_Ebullientworks Table.approved.md
- tests/DocsSamplesForStatuses.test.Theme_ITS Table.approved.md
- tests/DocsSamplesForStatuses.test.Theme_Minimal Table.approved.md
- tests/DocsSamplesForStatuses.test.Theme_Things Table.approved.md
- tests/DocsSamplesForStatuses.test.ts
Imported CANCELLED tasks for themes now toggle to TODO instead of DONE.
This makes them consistent with the default CANCELLED status in Tasks.
Fixes #1605
- By adding tests
- By running the new code inside Obsidian
> fix: imported CANCELLED tasks now toggle to TODO

- src/Config/SettingsTab.ts
A few small changes that make the buttons much easier to read
- The 'Add all Status types...' buttons are no longer calls-to-action - so now just plain colour
- The text at the right side is aligned, making the remainder easier to read
- The number of supported statuses in each is now displayed
- The name 'SlRvb Checkboxes' is now shown...
- Remove use of 'Status **types**' - which I missed out by mistake before the 1.23.0 release
- The order is better:
- Sorted by name, for things that work on dark and light
- Then sorted by name for dark-only
With the addition of more themes, the intensity of all the theme buttons was making my eyes hurt!
In the demo vault.
> feat: Clarify theme buttons in status settings

- src/File.ts
In essence, when a task is toggled by the Tasks plugin, the code reads the file that contains the task to find the line to update.
Under certain circumstances (listed below) it may find and update the wrong line, overwriting a different task.
This change makes Tasks check, **when in Reading mode and in Tasks results blocks**,  that the line it is about to overwrite actually contains the expected text. If it does not, the toggling action will halt, and a message will be written to the console.
Note: **This change does not affect Live Preview**. That is planned to be addressed in a separate pull request.
---
All of the detail needed should be in the commit messages.
Update: The key bit is:
> Currently, the unique identifier (UID) for tasks
> are a source file, a section, and an index into
> …
> fix: Prevent rare overwrite of wrong line in Reading mode & results blocks

- src/Query/DateParser.ts
- tests/Query/DateParser.test.ts
Add `DateParser.parseDateRange()` to parse filters with two dates.
This is a step on the way to implementing #1613.
By TDD.
This is a new feature in code, not yet visible to users.
All changes done by pairing with @ilandikov
> feat: Teach DateParser to read date ranges

- src/File.ts
- src/main.ts
1. Use `.originalMarkdown` in guard when replace task (discussed with @claremacrae already)
2. Adjust formatting of guard print when replace task
3. Fix reading stale file data when replacing task
Here, "stale file data" is defined as "not in sync with what the user is seeing on the screen", aka, "not in sync with the MarkdownView of the file that they have edited".
what happens is before reading the file, all open views that view the file that the task is contained in are forced to save.
**please note I am not in favour of this as a solution and am very open to alternatives. I open this PR for discussion**
To fix repro case discussed recently in #984 
Locally in my vault with the specific repro case and seeing it no longer repro.
> Fix reading stale file data when replacing task

- CONTRIBUTING.md
- resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
- src/Config/DebugSettings.ts
- src/Config/Settings.ts
- src/Query/Query.ts
- src/TaskLineRenderer.ts
- tests/Config/DebugSettings.test.ts
- tests/TaskLineRenderer.test.ts
Add two hidden settings to help developers understand what is going on behind the scenes in the plugin's code.
Note that if sorting is disabled manually in the settings, the `explain` instruction does report this.
From the additions to the CONTRIBUTING file:
---
> [!Released]
> Introduced in Tasks 1.26.0.
There are some hidden Tasks settings options to turn on some hidden facilities to aid visualising the behaviour of the plugin.
The default values are:
```json
"debugSettings": {
"ignoreSortInstructions": false,
"showTaskHiddenData": false
}
```
The `data.json` file needs to be edited manually to turn these on: The options are not exposed in the settings UI.
This is what these options do:
- `ignoreSortInstructions`:
- Turns off all sorting of tasks, that is, it disables both the default …
> feat: Add visual debugging aids for Tasks developers

- CONTRIBUTING.md
- src/Cache.ts
- src/InlineRenderer.ts
- src/Task.ts
- src/TaskLineRenderer.ts
- src/TaskLocation.ts
- tests/StatusRegistry.test.ts
- tests/Task.test.ts
- tests/TaskLineRenderer.test.ts
- tests/TaskLocation.test.ts
- tests/TestHelpers.ts
- tests/TestingTools/TaskBuilder.ts
Add line number to `TaskLocation`, and update the debug rendering of task data to display it.
This is a step on the way to removing the fragile and hard-to-reason-about  `task.sectionStart` and `task.sectionIndex`.
- Adding tests
- Testing in the demo vault
This is what the 2 lines of debug display look like now, where `null` is the heading not specified for rendering in Reading mode.
> refactor: Store task line numbers

- tests/Task.test.ts
- Add some missing assertions in `Task.test.ts`
- And fix the incorrect tests that then failed!
SonarLint in WebStorm reports:
- Assertions should be complete.
- CodeSmell typescript: S2970
- It is very easy to write incomplete assertions when using some test frameworks.
It turns out that 4 of the tests were actually incorrect, but seemed to be passing because they were not asserting on the result.
See above.
Running the tests. They failed :-)
n/a
> test: Fix assertions in Task tests & fix tests; thanks SonarLint

- src/Commands/ToggleDone.ts
- tests/Commands/ToggleDone.test.ts
Partially supercedes  #1703
This PR is one in a collection of PRs with the ultimate goal of providing an _option_ to write tasks using a plaintext version of this plugin's task format.
This PR's goal is to pave the way for implementing that plaintext task format, specifically by:
* fix: _Slightly_ reworking how the cursor is repositioned during the `ToggleDone` command. This to make it be agnostic to the task's format. 
Users should expect the following cursor behavior:
* When toggling a task, the cursor won't change columns. If toggling a task makes it shorter and leaves the cursor out of bounds, it is moved to the end of the line. This essentially was the previous behavior, except in a few edge cases.
* When toggling _an empty line_ or a line with _just_ a list marker (number, bullet, …
> fix: Simplify cursor repositioning during the 'ToggleDone' command

- src/QueryRenderer.ts
If Tasks query is written in a card in Canvas it is not rendered.
Inspired by same PR in dataview plugin: https://github.com/blacksmithgu/obsidian-dataview/pull/1661/
Solves #1732
Tested on my live vault - created a card with
````
```tasks
not done
```
````
Tasks 1.25.0 is not rendering anything. With this fix - a list of tasks appears.
Unfortunately I can't imagine how to unit test this.
> fix: render Tasks in canvas

- src/ui/EditTask.svelte
Add read only span of created date to EditTask modal. 
Closes #1742.
Only via manual testing, with switch on/off settings.
> feat: Add created date to EditTask modal

- contributing/Testing/Example Tests.md
- docs/queries/filters.md
- src/Query/DateParser.ts
- tests/Query/DateParser.test.ts
- tests/Query/Filter/DueDateField.test.ts
I found the original description of types of date in task queries to be a bit confusing:
> natural language or in formal notation (`YYYY-MM-DD`)
I've changed the vocabulary to:
> - absolute (points to a fixed date in the calendar)
> - relative (depends on today's date)
Note that these two types of date are independent of the format.
For example, both `2021-05-25` and `25th May 2023` are absolute dates.
I've also reviewed all the date documentation quite thoroughly.
I converted some H4 headings to H3 because int the current publishing mechanism, the H4 headings just do not stand out at all in the body of the page.
I've also updated the relevant test names for consistency.
Make it easier to write and read the docs.
Viewing in local docker build of docs.
Internal …
> docs: Adopt 'absolute' & 'relative' instead of 'formal & natural language'

- src/File.ts
- tests/File.test.replaceTaskWithTasks_issue 1680 - Cannot read properties of undefined correct behaviour.approved.txt
- tests/File.test.replaceTaskWithTasks_issue 1680 - Cannot read properties of undefined current incorrect behaviour.approved.txt
- tests/File.test.ts
- tests/__test_data__/MockDataForTogglingTasks/1680_task_line_number_past_end_of_file.json
This prevents an exception if toggling in unsaved file in Reading mode.
See the comment https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1680#issuecomment-1457826313.
If lines had been deleted from a file, and it was not yet saved when user then toggled a line near the end of the file in Reading mode, there could be an access of a non-existent line number.
The resultant output was:
```text
plugin:obsidian-tasks-plugin:17605 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
at eval (plugin:obsidian-tasks-plugin:17605:14)
at Generator.next (<anonymous>)
at fulfilled (plugin:obsidian-tasks-plugin:173:24)
```
Another step in fixing outlier conditions in toggling tasks in Reading view
By adding a test which showed the problem behaviour, …
> fix: Prevent exception if toggling in unsaved file in Reading mode

- .github/pull_request_template.md
It introduces the prefix `contrib: ` custom conventional commit prefix for changes to the [Contributing to Tasks](https://publish.obsidian.md/tasks-contributing/) docs.
This is a tiny remaining part of #1705.
> chore: Introduce 'contrib' Conventional Commit prefix for contributing docs

- resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
- src/Config/Settings.ts
Put setCreatedDate next to setDoneDate in the order in the default settings values.
This is so they appear in a logical order in data.json.
(The previous order was random, due to the order that two unrelated pull requests were merged recently.)
It's a tiny cosmetic change, but will help me with version-control in multiple vaults.
Manually.
> refactor: More logical order of default settings values

- docs/queries/filters.md
Add a detailed appendix in filters.md showing the changes in date filter search results since the previous release.
The table was populated by using text from the [DueDateField.test.due_date approval tests.approved.md](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/tests/Query/Filter/DueDateField.test.due_date%20approval%20tests.approved.md) approval test file, so guaranteed to be correct.
/CC @ilandikov 
I want to be clear to users what the changes in behaviour are in the upcoming release.
Viewing docs locally.
---
---
---
---
---
> docs: Add appendix showing date filter changes

- docs/queries/filters.md
- docs/queries/grouping.md
- docs/queries/layout.md
- docs/queries/sorting.md
Bump the next version to 2.0.0
Because the fixes to date range searches do change existing behaviour, even though they are definite improvements.
Viewing docs locally.
> docs: Bump the next version to 2.0.0

- docs/advanced/api.md
- docs/getting-started/create-or-edit-task.md
- docs/getting-started/dates.md
Because the fixes to date range searches do change existing behaviour, even though they are definite improvements.
This is the second half of #1785. I accidentally missed out some files in that.
Because the fixes to date range searches do change existing behaviour, even though they are definite improvements.
Viewing docs locally.
> docs: Bump the next version to 2.0.0 in more docs files

- docs/getting-started/index.md
- src/QueryRenderer.ts
Revert:
- #1733
This fixes #1800:
- #1800 
But unfortunately reopens:
- #1732
The fix for #1732 caused Tasks to start rendering every Tasks block twice, every time any tasks changed, instead of the usual once.
After a note with tasks query blocks in was closed, its blocks would still be redrawn once every time a task was edited, so in a session where lots of query blocks were opened and then closed, Tasks ended up chewing up more and more resources.
Also document that:
- Tasks cannot read task lines in Canvas cards
- Tasks cannot render task query blocks in Canvas cards
As above.
To satisfy myself that I going to be reverted the cause of the regression:
- Via git bisect, in my local build
- Via downloading many different post-1.25.0 builds and systematically testing their behaviour.
- …
> fix: Speed up drawing of Tasks blocks after 2.0.0 release

- src/Query/Group.ts
- tests/Group.test.ts
Fixes #1708 
In #1426 the filename was changed to a link. The former needed the characters to be escaped. The latter doesn't. This fixes this.
Unit tests modified accordingly.
Also tested on my local vault with a test file manually.
> fix: 'group by filename' links now work on filenames with underscores

- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- src/Suggestor/Suggestor.ts
- src/TaskSerializer/DataviewTaskSerializer.ts
- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/Suggestor/Suggestor.test.ts
- tests/TaskSerializer/DataviewTaskSerializer.test.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
This PR builds on work intiated in #1703, and adds a task format that is fully plaintext. Specifically, this PR adds a task format that strives to be compatible with Dataview's task format. Addresses #373 
I wanted to use this plugin to manage my tasks in Obsidian, but wanted to keep my notes in plaintext. 
Some existing tests could be reused (specifically `tests/Suggestor/Suggestor.test.ts`).
Added unit tests in `tests/TaskSerializer/DataviewTaskSerializer.test.ts`
> feat: Add support for either Dataview OR Tasks emoji task formats

- docs/Advanced/Daily Agenda.md
- docs/Advanced/Quickadd.md
Remove some leftover text from the old Jekyll-basde docs that I had not realised was being rendered by Obsidian:
- `{% raw %}`
- `{% endraw %}`
Fixes #1902
By publishing the new pages and confirming the display is now correct.
Before: 
After:
> docs: Remove leftover Jekyll {% raw %} and {% endraw %} text from new docs

- src/Query/FilterParser.ts
Fixed:
https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1852
This makes sure that `BooleanField` is always last in `FilterParser`.
If a field is added after `BooleanField`, it shows a TypeScript compilation error.
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1852
I tried the query described in the bug and it works as expected.
I also tried adding this to the tests, however this also caused the tests to catch #1500, which this PR does not fix, so I had to leave these tests out for now :(
> fix: Allow filename filters to contain parentheses

- docs/Getting Started/Auto-Suggest.md
- src/Suggestor/Suggestor.ts
- src/Suggestor/index.ts
- tests/Suggestor/Suggestor.test.ts
Prevents the "Created today" suggestions to appear when the user types "today", which was causing it to match too often.
Fixes #1893  
Tested in the sample vault, as shown in the screen cap. Tested with the new Dataview format as well. I don't believe the changes affect any other area of the code.
> fix: created date suggestion appearing too often

- jest.config.js
- tests/global-setup.js
This PR fixes an issue where the tests in `tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.ts` will fail if run in a timezone with a negative offset relative to UTC (i.e. if run on a machine in North America).
`DateFieldReference.test.ts` mocks the current date by setting it to `new Date('2023-04-19')` which corresponds to "'Wed, 19 Apr 2023 00:00:00 GMT'"
https://github.com/obsidian-tasks-group/obsidian-tasks/blob/88a519fa475b7ee672d3cfbf8aa64efe78b44a4b/tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.ts#L12-L15
The tests run in that file expect that the date is Wednesday April 19th 2023 as well 
https://github.com/obsidian-tasks-group/obsidian-tasks/blob/88a519fa475b7ee672d3cfbf8aa64efe78b44a4b/tests/Query/Filter/ReferenceDocs/FilterRefer …
> test: Normalize timezone for tests to UTC

- src/Config/SettingsTab.ts
I accidentally released the Task Formats feature with an out-of-date link to the documentation in the settings.
This fixes that.
Broken link:
https://publish.obsidian.md/tasks/Reference/Formats/About+Formats
Working link:
https://publish.obsidian.md/tasks/Reference/Task+Formats/About+Task+Formats
In a local build.
N/A
> fix: Documentation link in Task Format settings now works

- docs/Reference/Task Formats/About Task Formats.md
- docs/Reference/Task Formats/Dataview Format.md
- resources/sample_vaults/Tasks-Demo/Formats/Dataview Format.md
- src/TaskSerializer/DataviewTaskSerializer.ts
- tests/TaskSerializer/DataviewTaskSerializer.test.ts
Resolves #1913
This PR is a hotfix that adds better support for the workarounds suggested in #1913, that get around Obsidian rendering sequential inline fields (`[start::2023-04-25][priority::high]`) as [reference-style links](https://daringfireball.net/projects/markdown/syntax#link):
Specifically this PR:
* Relaxes some parsing rules to allow users to seperate inline fields with a comma (`,`).
* Makes Tasks always write Dataview tasks with 2 spaces in between fields.
* Updates the documentation to:
* Separate inline fields with commas in examples
* Warn about reference style links and describe the workarounds
Note: No work was done on suggestions since users are expected to manually insert brackets (and now spaces and/or commas) themselves.
Hotfix for #1913
* A test was added to validate …
> fix: Dataview: Enable workarounds to prevent Obsidian from rendering inline fields as reference style links

- src/Query/Filter/BacklinkField.ts
- tests/Query/Filter/BacklinkField.test.ts
- tests/Task.test.ts
- tests/TestHelpers.ts
- Add a passing test for #1927
- Add extensive tests for `Task.getLinkText()`
- Make the types used for `path` and `heading` in `BacklinkField` tests match those used in `Task`
- Simplify the implementation of `BacklinkField.value()` to re-use `Task.getLinkText()`
- This previously looked like it wouldn't work as strings like `filename > ` were being generated, but that turned out to be due to the tests using `undefined` where `Task` was using `null`)
- Simplify the implementation of `BacklinkField.grouper()` to remove `substring()` and do simple string joining
In investigating #1927 - and trying to figure out how it actually got fixed by f3c6a41e92b3e39a81f564b4287c3016318fb93b, I spent some time trying to understand how the refactoring in f3c6a41e92b3e39a81f564b4287c3016318fb93b could …
> refactor: Simplify BacklinkField & add test for #1927

- src/Query/Filter/Field.ts
- src/Query/FilterParser.ts
This applies some simplifications to the grouping code in the `Field` class.
These simplifications were spotted by @ilandikov when we were pairing recently, and I showed a diagram of the method calls in the grouping code.
Removed methods:
- `parseGroupLine`: Call `createGrouperFromLine` instead
- `canCreateGrouperForLine`: Call `createGrouperFromLine` instead
Remove clutter.
By running existing tests.
Here is a canvas diagram of the call hierarchy in `Field` **before** this PR:
Here is a canvas diagram of the call hierarchy in `Field` **after** this PR:
> refactor: Simplify grouping code in Field.ts

- src/Query/Filter/Field.ts
- src/Query/FilterParser.ts
- tests/Query/Filter/Field.test.ts
- tests/Query/Filter/RecurringField.test.ts
- tests/Query/Filter/TagsField.test.ts
This applies some simplifications to the **sorting** code in the `Field` class.
The simplifications mentioned in #1976, that were spotted by @ilandikov when we were pairing recently, apply equally to the sorting code (since the grouping code was a copy of the sorting code).
Removed methods:
- `parseSortLine`:
- Call `createSorterFromLine` instead
- `canCreateSorterForLine`:
- Call `createSorterFromLine` instead
Remove clutter.
By running existing tests.
See the images in #1976 for what the same change looks like when done for the grouping methods.
In those diagrams, `s/Group/Sort/g` to understand this change,
> refactor: Simplify sorting code in Field.ts

- tests/CustomMatchers/CustomMatchersForTaskBuilder.ts
- tests/CustomMatchers/CustomMatchersForTasks.ts
- tests/CustomMatchers/jest.custom_matchers.setup.ts
- tests/Task.test.ts
Added some more Jest custom matchers:
- `CustomMatchersForTaskBuilder.ts`
- `toBeIdenticalTo()`
- (moved from `tests/Task.test.ts`)
- `CustomMatchersForTasks.ts`
- `toToggleTo()`
- `toToggleWithRecurrenceInUsersOrderTo()`
- Removed about 100 lines from `Task.test.ts`
- Remove repetition in existing tests
- And make them more expressive
- Running existing and updated tests
> test: More custom matchers, for easier Task testing

- docs/Getting Started/Auto-Suggest.md
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.ts
Via auto-suggest I keep ending up with tasks of Highest priority accidentally. See #1995 for a write-up.
This PR reverts to the original order of priority items in the auto-suggest menu.
The order of priorities in auto suggestion is now:
1. high
2. medium
3. low
4. highest (new)
5. lowest (new)
Benefits:
- This retains the original order, for people's muscle memory. 
- And it means that the longer names are after the shorter ones, which also makes it possible to type both, 
- And it means that typing parts of names selects the same result as before highest and lowest were added.
Fixes #1943
- Via the unit tests
- In Obsidian (both with the default number of suggests (6) and the maximum (12)
With 6 suggestions:
With 12 suggestions:
> fix: Enable 'High priority' to be selected easily in Auto Suggest

- tests/CustomMatchers/CustomMatchersForGrouping.ts
- tests/CustomMatchers/jest.custom_matchers.setup.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/PriorityField.test.ts
- tests/Query/Filter/StatusNameField.test.ts
- Add custom matcher `groupHeadingsToBe()`
- Use it to test group headings for `DueDateField`, `PriorityField`, `StatusNameField`
- Prepare tests to make future changes in sorting of group order visible
Run all tests.
> test: add custom matcher to test group sort order

- tsconfig.json
Add `outDir` to compiler options in `tsconfig.json`.
Fixes #1986 
Error message disappeared in VSCode on macos.
> chore: Fix "Cannot write file '....../global-setup.js' errors'"

- src/Recurrence.ts
- src/Status.ts
- src/StatusConfiguration.ts
- src/Task.ts
- tests/Status.test.ts
- tests/StatusConfiguration.test.ts
- tests/Task.test.ts
- tests/TestingTools/TaskBuilder.test.ts
- tests/TestingTools/TaskBuilder.ts
**Main:**
- `TaskBuilder.createFullyPopulatedTask()` returns a `Task` object with a realistic value in every field.
- And its tests should ensure that when new fields are added to `Task`, new values will be added here too.
- `TaskBuilder.build()` now sets `Task.originalMarkdown`.
**Other:**
- `Status` and `StatusConfiguration` now have `identicalTo()` methods
- Fixed a bug in `Task.identicalTo()` that two tasks were considered different if they had different instances of `Status` that had identical values
- As far as I can see, from manual testing, this does not affect the released Tasks plugin, as statuses are obtained from the `StatusRegistry`, so the same `Status` instance is shared between tasks with the same status symbol.
- `Recurrence.fromText()` logs an error if there was an error …
> test: Add TaskBuilder.createFullyPopulatedTask()

- docs/Queries/Grouping.md
- docs/Scripting/Task Properties.md
- src/Query/Filter/HappensDateField.ts
- src/Scripting/TasksDate.ts
- src/Task.ts
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.created_docs.approved.md
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.created_results.approved.txt
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.done_docs.approved.md
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.done_results.approved.txt
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.due_docs.approved.md
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.due_results.approved.txt
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.happens_docs.approved.md
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.happens_results.approved.txt
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.scheduled_docs.approved.md
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.scheduled_results.approved.txt
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.start_docs.approved.md
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.custom_grouping_by_task.start_results.approved.txt
- tests/Query/Filter/ReferenceDocs/FilterReference/TaskPropertyExamples.test.ts
- tests/Scripting/ScriptingTestHelpers.ts
- tests/Scripting/TaskProperties.test.task_dates.approved.md
- tests/Scripting/TasksDate.test.ts
- tests/Task.test.ts
- Introduce `TasksDate` class as a wrapper around `Moment | null`
- The dates used by the scripting code (`Task.due`, `Task.happens` etc all now return a `TasksDate` object
- All `group by function` examples for date properties now updated
To not have to explain the [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator) for the normal case of formatting dates in group headings.
- By running the existing tests
> feat: Add TasksDate class for use in 'group by function'

- docs/Queries/Grouping.md
- src/Query/Filter/UrgencyField.ts
- tests/Query/Filter/UrgencyField.test.ts
`group by urgency` now sorts groups from most urgent to less urgency i.e. by decreasing urgency.
| Old instruction            | Use this instruction instead |
| -------------------------- | ---------------------------- |
| `group by urgency reverse` | `group by urgency`           |
| `group by urgency`         | `group by urgency reverse`   |
Sort group names in a meaningful order for Urgency field.
Unit tests (Fixed)
> fix!!: 'group by urgency' now puts most urgent tasks first, not last

- docs/Queries/Grouping.md
- src/Query/Filter/PriorityField.ts
- tests/Query/Filter/PriorityField.test.ts
Change group names from `Priority 1: Highest` to `Highest` (and all others too).
| Old name              | New name           |
| --------------------- | ------------------ |
| `Priority 0: Highest` | `Highest priority` |
| `Priority 1: High`    | `High priority`    |
| `Priority 2: Medium`  | `Medium priority`  |
| `Priority 3: None`    | `Normal priority`  |
| `Priority 4: Low`     | `Low priority`     |
| `Priority 5: Lowest`  | `Lowest priority`  |
Provide shorter group names with only meaningful data.
Fixes #1628
Unit tests (Fixed)
> feat: 'group by priority' names are now more readable

- docs/Queries/Grouping.md
- src/Query/Filter/StatusTypeField.ts
- tests/DocumentationSamples/DocsSamplesForStatuses.test.Status_Transitions_status-types.approved.md
- tests/Query/Filter/StatusTypeField.test.ts
- tests/TaskGroups.test.ts
Remove numbers in StatusType group names: `2 TODO` -> `TODO` by including the number in comments. This way the sort order of the StatusType is not changed.
| Old name        | New name      |
| --------------- | ------------- |
| `1 IN_PROGRESS` | `IN_PROGRESS` |
| `2 TODO`        | `TODO`        |
| `3 DONE`        | `DONE`        |
| `4 CANCELLED`   | `CANCELLED`   |
| `5 NON_TASK`    | `NON_TASK`    |
| `6 EMPTY`       | `EMPTY`       |
Provide shorter group names with only meaningful data.
Unit testing (with fixes).
> feat: 'group by status.type' names are now more readable

- tests/Scripting/TaskProperties.test.ts
use jest tools to fix the date for testing
One of the tests has urgency calculation. Time passed after the test has been added (https://github.com/obsidian-tasks-group/obsidian-tasks/commit/34ea4149a802da0d464343981157e03cd410f6bd), so the value of urgency has changed and now the test is always failing.
Unit test.
> test: set date in TaskProperties.test.ts to fix failing test

- src/ui/EditTask.svelte
Call the existing methods in `TasksDate` instead of manual calculation of format.
Prettier code.
Unit tests.
> refactor: use TasksDate to simplify EditTask.svelte

- src/Query/Filter/FilterOrErrorMessage.ts
- src/Query/ObjectOrErrorMessage.ts
- src/Query/QueryComponentOrError.ts
I want to start re-using the pattern of:
- store an instruction and one of:
- an object created from it
- or an error message, if the instruction was invalid in some way
For example, I want to be able to report syntax errors in JavaScript expressions, for `group by function` and soon `filter by function`.
- running the existing tests
- running the new code in Tasks-Demo vault and confirming that error messages for invalid filters are still displayed
> refactor: Extract generic class QueryComponentOrError 

- src/Commands/CreateOrEditTaskParser.ts
- src/Task.ts
- tests/Commands/CreateOrEditTaskParser.test.ts
- tests/EditTask.test.ts
- tests/Task.test.ts
Parse the task line for all the details including recurrence, scheduled, due & starts dates when opening the task edit modal.
Fix #2037 
Added unit tests + smoke test on my live vault on the following:
```
```
> fix: Make Edit modal use existing emojis if Global Filter missing

- src/QueryRenderer.ts
I'm going to be adding some error-checking in the task rendering code soon, to allow the imminent `filter by function` to throw exceptions during execution of searches.
The complexity of `QueryRenderChild.render()` was such that this was going to be quite messy to add, so this PR is just a preparatory extracting methods out of `QueryRenderChild.render()`, so there is one method for each of the different behaviours.
See the individual commits for the specific refactoring.
See above.
- By building and running the latest code and confirming the display of results is unchanged
> refactor: Reduce complexity in QueryRenderChild.render()

- src/IQuery.ts
- src/Query/Query.ts
- src/Query/QueryResult.ts
- src/QueryRenderer.ts
- tests/Config/DebugSettings.test.ts
- tests/Query.test.ts
- tests/Query/QueryResult.test.ts
A pure refactoring. Initially `QueryResult` is a thin wrapper around `TaskGroups` initially.
More behaviour (and more docs) will come soon.
This is a step towards adding error-checking during execution of Tasks queries, to display an error message if an exception is thrown during the search.
This is needed for the implementation for the forthcoming `filter by function` facility.
- Running tests
- Building and running the plugin and confirming that the rendering behaviour is unchanged.
> refactor: Introduce QueryResult class

- src/Urgency.ts
- tests/Query/Urgency.test.ts
Adjust the Urgency calculation code so that it no longer depends on the time of day.
Previously at mid-day a task due on today's date changed its score to be the value for `a task due yesterday`. See #2068.
The fix was identified by @schemar - thank you!
This fixes #2068.
- With a failing test that then passed after the bug fix
- Manually in the Demo vault.
> fix: Prevent date components of Urgency changing and midday

- docs/Advanced/Styling.md
- docs/Queries/Layout.md
- resources/sample_vaults/Tasks-Demo/.obsidian/snippets/tasks-plugin-highlight-specific-tag-green-glow.css
- resources/sample_vaults/Tasks-Demo/.obsidian/snippets/tasks-plugin-highlight-specific-tag-round-red-description.css
- resources/sample_vaults/Tasks-Demo/.obsidian/snippets/tasks-plugin-smoke-test-query-styling.css
- resources/sample_vaults/Tasks-Demo/Manual Testing/Styling of Queries.md
- src/TaskLayout.ts
- src/TaskLineRenderer.ts
- styles.css
- tests/TaskLineRenderer.test.ts
This reworks the `hide tags` instruction to now use CSS to hide tags, rather than actually remove the tags from the description.
Because the tags are now present in the rendered tasks, any CSS based upon tags will now continue to work after tags are hidden.
Credit: @esm7 for the suggestion to implement hiding of tags using CSS, and for the CSS to do it.
Note that now only tags recognised by Obsidian are hidden.
For example, in the previous implementation `#123` would have been hidden, but this is [not recognised a valid Obsidian tag](https://help.obsidian.md/Editing+and+formatting/Tags#Tag+format) and so is now not hidden.
This behaviour is documented.
Fixes #2083
- By manual testing
- By updating unit tests
- By adding new steps to the styling smoke test, to confirm the new behaviour - …
> fix: 'hide tags' now preserves styling of description for specific tags

- src/Query/Filter/FunctionField.ts
- src/Scripting/Expression.ts
- tests/Scripting/Expression.test.ts
- tests/Scripting/TaskProperties.test.ts
A series of refactorings to divide up the original `evaluateExpression()` function in to separate parsing and evaluating functions.
This is a step on the way to implementing `filter by function`.
- Testing `group by function` manually in the demo vault.
> refactor: Divide up evaluateExpression() for re-use

- src/Query/QueryComponentOrError.ts
- src/Scripting/Expression.ts
- src/Scripting/TaskExpression.ts
- tests/Scripting/Expression.test.ts
- tests/Scripting/TaskExpression.test.ts
I found when first trying to implement `filter by function` that I was writing a bunch of code repetitively in order to call the functions in `Expression.ts` on `Task` objects.
So I have created this class `TaskExpression` to hide all the details of the functions in `Expression.ts`.
This is a step on the way to implementing `filter by function`.
By writing new tests.
(It is not yet called by any code in `src/`, so no manual testing.
> refactor: Add TaskExpression to encapsulate Expression functions

- src/Query/Filter/FunctionField.ts
- src/Query/Query.ts
- src/Query/QueryResult.ts
- src/QueryRenderer.ts
- tests/Query.test.ts
- tests/Query/QueryResult.test.ts
Now if `filter by function` generates an error during searches, the error message is display in the Tasks code block, in Reading and Live Preview views.
A later change will include the instruction line in the error message.
This is necessary for users to detect any errors in their custom filter instructions.
There is also a small chance that this may solve some of the reported issues around task searches being stuck at 'Loading tasks'.
- By exploratory testing in the demo vault
> feat: Tasks code block now shows any error messages from searches

- src/ui/EditTask.svelte
Fix error message from newer svelte dependencies.
The error message was:
```
Error: Argument of type '{ "bind:value": string; id: string; type: string; class: string; placeholder: string; accesskey: string | null; "on:keydown": (e: KeyboardEvent) => void; "on:paste": () => void; "on:drop": () => void; }' is not assignable to parameter of type 'HTMLProps<"textarea", HTMLAttributes<any>>'.
Object literal may only specify known properties, and '"type"' does not exist in type 'HTMLProps<"textarea", HTMLAttributes<any>>'. (ts)
id="description"
type="text"
class="tasks-modal-description"
```
They are complaining about the 'type="text"' line.
When I delete that line and test the Create or edit task modal, the Description field still works fine.
I believe that this line was a hangover from an …
> chore: Fix error message from newer svelte dependencies.

- src/Query/FilterParser.ts
- tests/Query.test.ts
I noticed a few gaps in tests of ensuring that Query parses all filter, sort and group instructions.
And ended up adding tests to cross-check the data with the supported fields, to remove the need to manually check for missing instructions when reviewing PRs.
Some of the missing lines were down to me, and I didn't want to have to keep remembering to add them.
See above.
- Existing tests pass
- New tests added.
> test: Simplify code-review of filter, sort and group additions

- src/Query/Query.ts
- tests/Query.test.ts
All error messages from parsing task query blocks now include the actual problem line.
It was previously sometimes hard to figure out which line in a long query block was causing the problem.
- Manually, by testing it with various errors
- Adding new Jest tests
The text in red has been added:
> feat: query error messages now show problem line

- src/Query/Filter/TextField.ts
- src/Query/Matchers/RegexMatcher.ts
- tests/Query/Filter/TextField.test.ts
Prior to this change, any errors in regular expressions that made it past the checking in `RegexMatcher.validateAndConstruct()` resulted in a blank Tasks code block, with no information for the user at all about the nature of the problem.
Now, an error message is displayed, showing what the problem is.
For example:
```
Error: Parsing regular expression. The error message was: "SyntaxError: Invalid regular expression: /hello(/: Unterminated group"
description regex matches /hello(/
```
Fixes #2129.
- With new tests
- Manually in the sample vault
> fix: Display reason for any failure to read regex

- src/Query/Matchers/RegexMatcher.ts
- tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
- tests/Query/Matchers/RegexMatcher.test.ts
- Add support for the `u` regex flag (allow Unicode)
- As a by-product, detect and report errors due to use of duplicate regex flags.
I am not actually sure whether the `u` flag is required to enable searching for Unicode strings in tasks, since my own regex searches have been working. But it should be recognised anyway.
This simplifies `validateAndConstruct` in `RegexMatcher` - more simplification coming soon.
Having enabled `explain` to display regex flags, I noticed that `u` was not being recognised.
- Updating existing tests
- Testing manually in demo vault
One new failing test remains, which is that invalid match flags should be rejected. This will be fixed after #1037 is fixed.
> fix: Support 'u' flag (Unicode) & detect duplicate flags

- src/Query/Matchers/RegexMatcher.ts
- tests/Query/Filter/PathField.test.ts
- tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
- tests/Query/Matchers/RegexMatcher.test.ts
I finally worked out how to prevent `path regex matches /a/b/c/d/` from confusingly only searching `path regex matches /a/`
It turned out that when creating `RegExp` objects from strings, TypeScript automatically escapes un-escaped forward slashes (/).
But the previous validation code in `validateAndConstruct()` was wrongly truncating queries at the first unescaped forward slash.
By removing that validation, it is now possible to use unescaped paths in regular expressions (providing that they don't have any other unescaped special characters, of course).
And if the regular expression does have an error, the user will now get a meaningful error message via the exception thrown by the `RegExp` constructor.
Previous searches where '/' characters are escaped will still work, but this escaping …
> fix: prevent truncation of regex /a/b/c/d/ searching only /a/

- src/Query/Matchers/RegexMatcher.ts
- tests/Query/Matchers/RegexMatcher.test.ts
Report any invalid regex flags as errors in the query.
This might happen in the case where the final closing slash is missing from the filter.
I want to report any regex errors to the user, rather than ignoring them as previously, because they generally are caused by a missing backslash in the query.
- Running and updating existing tests
- Adding a new test
- Exploratory testing in the demo vault.
> fix: Report invalid regex flags - likely a missing slash

- src/Query/Filter/TextField.ts
- src/Query/Matchers/RegexMatcher.ts
- src/Query/Query.ts
- tests/Query.test.ts
Give a help message if a regular expression is invalid.
Documentation will be updated in a later PR.
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1038
This closes the last of the usability issues around regular expression searching.
The previous message of something like 'check your slashes' could have been clearer.
- Running and updating tests
- Repeated exploratory testing, until I was happy enough with the message.
> feat: Show help message for invalid regular expressions

- .github/FUNDING.yml
This currently goes to https://github.com/sponsors/claremacrae
Add a Sponsor button to the Tasks plugin GitHub repo.
In my other plugin.
> chore: Add Sponsor button to GitHub repo

- src/Query/Filter/DateField.ts
I stumbled on some if-else that could be simplified by reversing them and removing the else afterwards.
Remove nesting levels and make the code easier to read.
Unit tests.
> refactor: simplify if-elses in DateField

- docs/Getting Started/Auto-Suggest.md
- docs/Getting Started/Getting Started.md
- docs/Introduction.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
- src/Task.ts
- tests/Task.test.ts
- Adds support for `+` sign as a list marker
- Updates the docs
- Updates the smoke test, to ensure that this is tested periodically
For example:
```text
+ [ ] #task View this file in **Reading view** and confirm that the tasks in this section are listed
+ [ ] #task View this file in **Live Preview** and confirm that the tasks in this section are listed
+ [ ] #task **check**: Checked all above steps for **viewing task blocks** worked
```
Fixes #2192 - which contains background info
I learned that:
> `+` is in a very convenient spot on a German keyboard
- Running existing Jest tests
- Adding examples of `*` and `+` lines to the smoke tests
- Manual exploratory testing
> feat: Add + sign to supported list markers

- docs/Getting Started/Tags.md
- docs/Queries/Filters.md
- docs/Queries/Grouping.md
- docs/Queries/Layout.md
- docs/Queries/Sorting.md
- src/Task.ts
This adds new Tags page, in Getting Started, with info about using Tags in Tasks.
It also adds a few links to the new page, elsewhere in the docs.
It's a bit detailed for Getting Started, maybe, but contains info that is requested a lot.
- Viewing the edits in Obsidian
- Some proof-reading done by SonarLint and WebStorm
> docs: Add a Tags page, to help with FAQs

- resources/sample_vaults/Tasks-Demo/Manual Testing/Styling of Queries.md
Update the smoke test instructions which were inaccurate after the PR https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2047/ was merged.
Have the same result as the expected in the smoke tests =)
Smoke tests! =)
> vault: update smoke test for recent code changes

- docs/Getting Started/Auto-Suggest.md
- docs/Reference/Task Formats/Dataview Format.md
- src/Config/Settings.ts
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.ts
This PR updates the behavior of the Suggestor for the Dataview Task Format to only present suggestions when there is an open bracket pair (Either `[`, or `(`)
The default suggestion strategy used by Tasks is to always present a list of suggestions that a user can use to autocomplete task fields as they are typing on a task line. This is _desirable_ for the Tasks Emoji Format, since it is often difficult/slow to manually produce the Emoji required to indicate the start of a task field.
However, this has little benefit for the Dataview Task Format; Dataview task fields can only appear within brackets `[]` or parens `()`. 
This PR was implemented with a higher-order function that decorates a suggestion function (see function `onlySuggestIfBracketOpen`). Unit tests were added for the …
> fix: Only show dataview suggestions when there is an open bracket preceding the cursor position.

- src/Suggestor/EditorSuggestorPopup.ts
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.ts
I want to change the behaviour of `EditorSuggestor.onTrigger()` to stop the Auto Suggest menu popping up in inconvenient locations like in the middle of a checkbox, or the start of the line.
Before doing so, this PR adds tests for the existing logic, by separating it out to a new function `canSuggestForLine()`, which is in `Suggestor.ts` so that it can be called from test code.
See above.
- By adding tests
- By running the changed code in the Tasks-Demo test vault, to confirm that the behaviour is unchanged.
> test: Add tests for logic in EditorSuggestor.onTrigger()

- src/TaskLineRenderer.ts
Pure refactor, Arlo's commit notation used, continuation on #2226 .
Make simpler code - unify same cases and ease new date introduction mentioned in #2226 (Now there is just one line needed: `case newDate:`.
See whether making PR's with this new notation will be easier for the maintainer to review.
Breaking code at `-` steps to have failing tests. Unit testing.
> refactor: simplify `getTaskComponentClass()`

- src/Suggestor/EditorSuggestorPopup.ts
- src/Suggestor/Suggestor.ts
- src/Task.ts
- tests/Suggestor/Suggestor.test.ts
I have found that Auto Suggest has a tendency to pop up in situations where it will never be valid, leading to task lines like:
```text
📅 - [ ] 
-📅  [ ] 
- [ 📅 ] 
```
This change means that Auto Suggest will now only pop up when the cursor is beyond one space after the `]` character.
If you imagine that the `|` in the following is the location of the cursor, the auto-suggest menu will no longer pop up in these situations:
```
- [ |] 
1. [ ]|
```
It will still pop up in these situations:
```
1. [ ] |
```
To make Auto Suggest a bit more specific.
- By adding tests.
- Manual testing in the demo vault
> fix: Prevent auto-suggest appearing before the end of the checkbox

- src/QueryRenderer.ts
- src/TaskLayout.ts
- tests/TaskLayout.test.ts
Separate management of `shownTaskLayoutComponents` & `hiddenTaskLayoutComponents` and the generation of hidden CSS classes in `taskListHiddenClasses`.
Continue #2226 towards an abstraction in `TaskLayout`.
Unit tests. Some commits tested by breaking code.
> refactor: separate concerns in `TaskLayout.ApplyOptions()`

- tests/EditTask.test.ts
- This mainly eliminates some duplicated code in `EditTask.test.ts`
- It also extracts some named methods to make the more complex code a bit clearer, by at least naming the behaviour
This is in preparation for improving test coverage of `EditTask.ts`
By repeatedly running the existing tests.
It only changed test code, so no manual testing is required.
> test: Refactoring to simplify EditTask.test.ts

- src/Commands/CreateOrEditTaskParser.ts
- tests/Commands/CreateOrEditTaskParser.test.ts
- tests/EditTask.test.Exhaustive_editing_Edit_and_save_All_inputs.approved.txt
When a task line has been parsed, check whether the created date shall be appended to it.
In https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2025#issuecomment-1616420079 you wrote:
> So the fix will be to add some code at line 29 that says
> 
> * if it was a task already - with a checkbox
> * and if the description is empty,
> * and it does not already have a creation date....
> * then add the creation date before returning the task on line 31.
Fixes #2025 
New unit tests added.
Smoke test in demo vault:
Global Filter set to `#task`, Add creation date option enabled. On each of the following lines execute `Create or Edit task` command, put something (`blablabla`) into description, click apply:
```
-
```
Both the lines gain the global filter, the description that was set and …
> fix: Editing a checkbox line with empty description now adds creation date, if enabled

- src/Commands/CreateOrEditTaskParser.ts
- tests/Commands/CreateOrEditTaskParser.test.ts
- tests/EditTask.test.Exhaustive_editing_Edit_and_save_All_inputs.approved.txt
When editing a task via the 'Edit task modal', if it didn't yet have the global filter, then treat it as a new task and add the Created date, if enabled.
This fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2112
- Added new test which failed before the bug was fixed
- Confirmed that 'exhaustive test' results are correctly updated
- Tested it manually in the sample vault
> fix: 'Create or edit task' now adds Created date if adding global filter

- src/Config/GlobalFilter.ts
- src/Config/SettingsTab.ts
- src/main.ts
- tests/GlobalFilter.test.ts
- tests/Task.test.ts
- tests/TaskLineRenderer.test.ts
Refactor `GlobalFilter` to not access or update `Settings`.
This is a step on the way to making `GlobalFilter` behave like `GlobalQuery`.
/CC @ilandikov for info.
This is part 1 of #2281
- #2281
- Adding tests
- Running all existing tests
- Thorough exploratory testing in the demo vault.
- I will also work through the smoke tests before merging the PR.
> refactor: Separate settings out of GlobalFilter

- src/QueryRenderer.ts
Just a tiny PR to clean the code up. The `taskCount` in the return was never used, so remove it.
Cleaner code.
Smoke tests.
> refactor: remove unused return value in `createTasksList()`

- src/Commands/CreateOrEditTaskParser.ts
- src/Config/GlobalFilter.ts
- src/Config/SettingsTab.ts
- src/File.ts
- src/InlineRenderer.ts
- src/Query/Filter/DescriptionField.ts
- src/Suggestor/Suggestor.ts
- src/Task.ts
- src/TaskLineRenderer.ts
- src/lib/QueryRendererHelper.ts
- src/main.ts
- src/ui/EditTask.svelte
- tests/Commands/CreateOrEditTaskParser.test.ts
- tests/Commands/ToggleDone.test.ts
- tests/EditTask.test.ts
- tests/GlobalFilter.test.ts
- tests/Query.test.ts
- tests/Query/Filter/DescriptionField.test.ts
- tests/Query/Filter/TagsField.test.ts
- tests/Suggestor/Suggestor.test.ts
- tests/Task.test.ts
- tests/TaskLineRenderer.test.ts
- tests/lib/QueryRendererHelper.test.ts
- Outside of tests, all access to `GlobalFilter` is now via `GlobalFilter.getInstance()`
- All other data and methods are now non-static
This is a step on the way to making `GlobalFilter` behave like `GlobalQuery`.
/CC @ilandikov for info.
This is part 1 of #2281
> refactor: Add getInstance() to GlobalFilter & make all else non-static

- src/QueryRenderer.ts
- src/lib/QueryRendererHelper.ts
- tests/Query/Explain/DocsSamplesForExplain.test.ts
- tests/TestingTools/ApprovalTestHelpers.ts
- tests/lib/QueryRendererHelper.test.ts
- `explainResults()` now takes a `GlobalFilter` value.
- Tests updated accordingly
I looked at all other uses of `GlobalFilter.getInstance()` to see if they could be converted to take in instance, and none were appropriate.
Fixes  #2281
This is the last step of  #2281
-  #2281
- Ran existing tests
- Ran the smoke tests in a local build
> refactor: Convert one use of GlobalFilter.getInstance() to instance

- docs/Introduction.md
- docs/Queries/Filters.md
- docs/Queries/Grouping.md
- docs/Scripting/Query Properties.md
- docs/Scripting/Task Properties.md
- src/Scripting/TasksFile.ts
- tests/Scripting/QueryProperties.test.query_file_properties.approved.md
- tests/Scripting/QueryProperties.test.ts
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.filename_docs.approved.md
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.file_properties_task.file.filename_results.approved.txt
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
- tests/Scripting/TaskProperties.test.task_file_properties.approved.md
- tests/Scripting/TaskProperties.test.ts
- tests/Scripting/TasksFile.test.ts
Add these new properties:
- `query.file.pathWithoutExtension` 
-  `query.file.filenameWithoutExtension`
- `task.file.pathWithoutExtension`
-  `task.file.filenameWithoutExtension`
Fixes #2287
- #2287
- Built the plugin and did some exploratory testing
> feat: Scripting enables removing file extension from path and filename properties

- docs/Queries/Grouping.md
- src/Query/Filter/BacklinkField.ts
- tests/Query/Filter/BacklinkField.test.ts
`BacklinkField.grouper()` now generates links to the file/section instead of just a group header.
When grouping by backlink, it's better to `hide backlink` since all the backlinks will be same in a given group. However in this way a clickable backlink is not available anymore. This adds a clickable backlink to the group header.
Fixes #1666:
- #1666
Unit tests updated + smoke test:
query file:
````md
```tasks
tags include backlinktest
hide backlink
group by backlink
```
````
task file:
```md
```
Group headers now have links:
Click on every group header and check that it leads to the clicked section. Example for `- [ ] #task #backlinktest h6 under h3`:
> feat: 'group by backlink' headings link to location & show hover previews

- src/InlineRenderer.ts
- src/QueryRenderer.ts
- src/Task.ts
- src/TaskLineRenderer.ts
1. Remove `Task.ts` & `TaskLineRenderer.ts` cyclic dependencies
2. Remove optional in `renderTaskLine()`
Before:
```
1) Config/Settings.ts > Suggestor/Suggestor.ts
2) Task.ts > Config/Settings.ts > Suggestor/Suggestor.ts
3) Task.ts > Config/Settings.ts > Suggestor/Suggestor.ts > TaskSerializer/DefaultTaskSerializer.ts
4) Task.ts > Config/Settings.ts > TaskSerializer/DataviewTaskSerializer.ts
5) Task.ts > DateFallback.ts
6) Task.ts > Scripting/TasksDate.ts
7) Task.ts > TaskLineRenderer.ts > File.ts
8) Task.ts > TaskLineRenderer.ts > File.ts > lib/MockDataCreator.ts
9) Task.ts > TaskLineRenderer.ts
10) Task.ts > TaskLineRenderer.ts > lib/PriorityTools.ts
11) Task.ts > Urgency.ts
12) Cache.ts > TasksEvents.ts
13) Query/FilterParser.ts > Query/Filter/BooleanField.ts
14) Config/SettingsTab.ts …
```
> refactor: remove cyclic dependencies & optional parameter in `TaskLineRenderer.ts`

- src/TaskLineRenderer.ts
Refactor - remove code duplication and extract hard coded values to a dictionary. Continuation of #2235.
Prepare for #2198 and maybe for an abstraction for `LayoutOptions`.
Unit testing.
> refactor: extract data attribute names dictionary from `getComponentDataAttribute()`

- src/QueryRenderer.ts
Change signature of createTaskList:
from
```ts
private async createTasksList({
tasks,
content,
}: {
tasks: Task[];
content: HTMLDivElement;
}): Promise<HTMLUListElement>
```
to 
```ts
private async createTaskList(tasks: Task[], content: HTMLDivElement): Promise<void>
```
Shorter and cleaner code.
Smoke tests (Unit tests are not testing this level).
> refactor: remove destructured object and return in createTaskList()

- src/Config/GlobalQuery.ts
- src/Query/Query.ts
- src/lib/QueryRendererHelper.ts
- tests/Config/DebugSettings.test.ts
- tests/Query.test.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/TextField.test.ts
- tests/TestingTools/ApprovalTestHelpers.ts
- tests/TestingTools/FilterTestHelpers.ts
- tests/lib/QueryRendererHelper.test.ts
Remove destructured types from `Query.constructor()` and other methods:
`new Query({ source }, path);` -> `new Query(source, path);`
Cleaner and shorter code.
Unit tests.
> refactor: remove destructured types in Query.ts

- docs/Queries/Limiting.md
- src/Query/Query.ts
- src/Query/QueryResult.ts
- tests/Query.test.ts
- tests/Query/QueryResult.test.ts
- If there was a limit applied in the search, the results now show the total number of tasks that were found.
- For example, `50 of 686 tasks` instead of `50 tasks`
The original suggestion was to make this an optional feature, but it is so useful, and the time-cost of adding optional features is significant, so I've enabled it automatically.
Also update the user docs.
Fixes #2294:
- #2294
> feat: 'show task count' now shows total, if 'limit' applied

- src/main.ts
Prevent a crash if there is no Tasks plugin `data.json` settings file at startup.
Fixes #2302.
On my Mac.
- Confirmed that Tasks now does start up correctly if there is no settings file.
- Also confirmed if there is a settings file, its values are loaded correctly.
> fix: Prevent crash at startup if user never previously edited settings

- docs/How To/How to get tasks in current file.md
There is a duplicate "path includes" in one of the code blocks in "docs/How To/How to get tasks in current file.md".  This PR removes that duplicate.
When copying the current task code block, no tasks show up. That is because there is a duplicate "path includes".
Copying the code block into my Obsidian vault.
> docs: Remove duplicate "path includes" in current file How To

- docs/Queries/About Queries.md
- docs/Queries/Combining Filters.md
- docs/Queries/Comments.md
- docs/Queries/Line Continuations.md
- src/Query/Query.ts
- src/Query/Scanner.ts
- tests/Query.test.ts
- tests/Scanner.test.ts
This implements line continuation using a trailing backslash, as discussed in #1351. 
```tasks
(priority is highest) OR \
(priority is lowest)
```
It is implemented as a global replace prior to line splitting, so this will work in any filter type. It does not trim whitespace around the newline; this is fine for the common case where the continuation occurs at a word boundary anyways, and could be useful in some edge cases where precise control over the whitespace is required.
The changes are implemented in a new `scan` function, which is responsible for splitting the input string into individual statements for further parsing. This leaves open the possibility for future enhancements to the parsing logic (for instance, if a more powerful parser gets implemented to support automatic line …
> feat: Long query lines can now be split with backslashes

- tests/Scanner.test.ts
This is a follow-up from #2330. See discussion in https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2330#discussion_r1359794459.
It stops IDEs from breaking tests by stripping trailing whitespace from the end of strings in source file `Scanner.test.ts`.
It updates existing tests. So by running them repeatedly.
> test: Prevent IDEs from stripping spaces from test

- docs/Queries/Filters.md
- docs/Queries/Grouping.md
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.heading_docs.approved.md
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.heading_results.approved.txt
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.symbol_docs.approved.md
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.statuses_task.status.symbol_results.approved.txt
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_docs.approved.md
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_results.approved.txt
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
- tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
Make some of the custom filter and custom grouping examples more readable, by wrapping longer lines, and in one case, introducing an inline comment.
- Advertise continuation lines
- Make the longer samples a bit less head-hurty... 🤯
- By running the tests that confirm that the code samples still give the same results
- By viewing the changed documentation files in Obsidian
> docs: Wrap long lines in custom filter and group samples

- docs/Introduction.md
- docs/Queries/Combining Filters.md
- docs/Queries/Comments.md
- docs/Queries/Explaining Queries.md
- docs/Queries/Line Continuations.md
- docs/Scripting/Placeholders.md
- docs/Support and Help/Breaking Changes.md
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.query.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.query.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.query.text
- tests/Query/Explain/DocsSamplesForExplain.test.ts
- Add more description with before-and-after samples
- Document that Line Continuation is a potentially breaking change
Want to release it!
- Editing and viewing the docs in Obsidian
- Most sample text has been generated by tests, so proven to work
Example finished section:
> docs: Finish Line Continuation and Inline Comments docs

- docs/Getting Started/Recurring Tasks.md
This reorders the sections in 'Recurring Tasks' documentation page so that:
- The `Known Issues` section will be included in the [Recurring Tasks section of the Known Limitations page](https://publish.obsidian.md/tasks/Support+and+Help/Known+Limitations#Concepts+Recurring+Tasks) on next publish.
- All the limitations in the Recurring Tasks page are grouped together
Preparation for further improvements in docs of recurring tasks.
- By viewing the pages in Obisidian
> docs: Add Recurring Tasks's 'Known Issues' to 'Known Limitations

- docs/Queries/Grouping.md
The docs refer to `task.file.filename.filenameWithoutExtension`, which is undefined. The correct path is `task.file.filenameWithoutExtension`. 
n/a
Locally.
> docs: Fix typo in grouping.md (filenameWithoutExtension)

- src/Query/Filter/BooleanField.ts
- src/Query/Filter/Filter.ts
- src/Query/SearchInfo.ts
- tests/CustomMatchers/CustomMatchersForFilters.test.ts
- tests/CustomMatchers/CustomMatchersForFilters.ts
- tests/CustomMatchers/jest.custom_matchers.setup.ts
- tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
- tests/Query.test.ts
- tests/Query/Filter/FunctionField.test.ts
- tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
- tests/TestingTools/FilterTestHelpers.ts
`SearchInfo` will soon contain selected data passed in from the Query being executed.
This is the [Parameter Object pattern](https://wiki.c2.com/?ParameterObject): it is a container for information that will be passed down through multiple levels of code, in order to be able to in future pass through more data, without having to update the function signatures of all the layers in between.
**Note:** Lots of the `FilterFunction` use don't need the 2nd parameter added, as they only act on the `Task`.
For now, I've taken the decision to only update the locations that needed to be updated in order to compile, rather than having loads of unused variables.
- I found when working with @DanielTMolloy919 on the dependencies code that we needed to pass `Task[]` down from `Query` to the filter …
> refactor: Introduce (empty) SearchInfo class

- src/Query/Query.ts
- src/Query/SearchInfo.ts
- tests/CustomMatchers/CustomMatchersForFilters.test.ts
- tests/CustomMatchers/CustomMatchersForFilters.ts
- tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
- tests/Query.test.ts
- tests/Query/Filter/FunctionField.test.ts
- tests/Query/SearchInfo.test.ts
- tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
- tests/TestingTools/FilterTestHelpers.ts
Add to `SearchInfo` the tasks being searched.
This will be needed by the work on implementing task dependencies.
- Adding tests and updating existing ones
- Check some of the Tasks code blocks in the demo vault
> recfactor: SearchInfo now contains list of tasks being searched

- docs/Introduction.md
- docs/Queries/Filters.md
- docs/Scripting/Custom Filters.md
- src/Query/Filter/FunctionField.ts
- src/Scripting/TaskExpression.ts
- tests/Query/Filter/FunctionField.test.ts
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.folder_docs.approved.md
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.folder_results.approved.txt
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
- tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts
`filter by function` lines can now use `query.file.path` directly just like `task.file.path`.
In custom filters, there is no longer a requirement to use quotes and placeholders to access query properties.
_Note: I pushed this change on `main` accidentally - so reverted the changes on main, then cherry-picked them on to this branch - to avoid the need to force-push._
To simplify the use of query properties in custom filters code.
- Manually testing in the same vault, with various queries such as:
~~~
```tasks
filter by function task.file.path === query.file.path
```
```tasks
filter by function task.file.folder === query.file.folder
```
~~~
The bits in red on the left have been removed, as `query.file.path`  etc can all now be used as variables …
> feat: Custom filters access Query Properties directly, without Placeholders

- resources/sample_vaults/Tasks-Demo/.gitignore
- src/Config/SettingsTab.ts
- src/StatusRegistryReport.ts
- tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md
- tests/StatusRegistryReport.test.ts
From replying to Tasks Issues and Features, it would be really useful to have a way to visualise a user's status settings, and even have a report of any issues in the settings.
This is what I've done so far:
- Add a button called `Review and check your Statuses` to the Tasks Custom Status settings.
- When clicked, it creates and opens a new markdown file, in the root of the vault.
- For simplicity, the file has a time-stamp in the name, so repeated running generates different files.
- The markdown file shows a Mermaid diagram of the Tasks Statuses actually loaded in the vault.
I plan to add some error checking info in a later PR.
_Note: I'm planning on changing this some more, so am holding off writing the documentation for now._
Fixes #2354 - good enough for a first implementation I …
> feat: Enable visualisation of the Status settings

- src/Config/StatusSettings.ts
- src/StatusRegistryReport.ts
- tests/Config/StatusSettings.test.ts
- tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
- tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md
- tests/StatusRegistryReport.test.StatusRegistryReport_should_tabulate_StatusSettings.approved.md
- tests/StatusRegistryReport.test.ts
The `Review and check your Statuses` button now shows a table of the statuses from the user's Tasks Status settings.
_Note: I'm planning on changing this some more, so am holding off writing the documentation for now._
Builds on https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2383 - showing more information.
A later step may add some error messages/feedback to the table.
- By updating the test for the table output
- By repeated generating of the report in the Tasks-Demo vault.
> feat: Statuses report now shows a Status Settings table

- src/Suggestor/EditorSuggestorPopup.ts
Add a workaround addressing the fact that when the suggestion popup is open, pressing tab doesn't indent todo items.
Thanks to ush on the forums for the [suggestion](https://forum.obsidian.md/t/editorsuggest-eats-tabs-and-other-characters-probably-shouldnt/69728/2?u=camerallan)
fixes #1578 #2187
This fix improves quality of life to users that maintain hierarchical task structures by removing the need to press `esc` to dismiss the popup in order to indent tasks.
- Built the plugin locally and reproduced the issue
- Rebuilt the plugin after applying the fix and was unable to reproduce the issue
- Couldn't see a way to test this without introducing a new test suite
- happy to take pointers though
- This would result in double indentation when pressing tab - not great
- Might be worth waiting …
> fix: Allow indenting tasks while suggest popup present

- tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
- tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
- tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_full_mode.approved.html
- tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_short_mode.approved.html
- tests/TaskLineRenderer.test.ts
Add an HTML mock renderer for the HTML visualisation tests.
Continuation of #2405 
Improve tests for safer refactorings.
Approval tests.
> test: include description and tags in Visualise HTML tests

- docs/Getting Started/Statuses.md
Changed `TODO` to `DONE` in the statuses docs.
I think there was a slight error in the docs because `done` applies to `DONE` and `CANCELLED` instead of `TODO` and `CANCELLED`
This change is required to prevent ambiguity.
This hasn't been tested
> `docs` - changed wrong definition of done

- yarn.lock
Make the latest minor updates to typescript dependencies.
```
bump typescript from 5.1.6 to 5.2.2
bump tslib      from 2.5.2 to 2.6.2
```
(cherry picked from commit e404d1c4822069945a70a5a6f238b3879509d097 ion main n order to create a PR and show the change in the release notes)
Done by running the following, and selecting all eslint lines for updating, then linting, testing, and running the plugin - and smoke testing.
```bash
yarn upgrade-interactive 
```
Trying to keep on top of dependencies.
- Checking that the Edit Task modal still works.
> build(deps): bump typescript and tslib

- src/TaskLayout.ts
- src/TaskLineRenderer.ts
- tests/TaskLineRenderer.test.ts
Following #2403 now the getTaskComponentClass() and getComponentDataAttribute() from TaskLineRenderer.ts shall be refactored.
Move behaviour towards the class that shall have it.
Unit tests.
> refactor: move to FieldLayoutDetail and linline 2 functions

- src/TaskLineRenderer.ts
- tests/TaskLineRenderer.test.ts
Add a container for `FieldLayoutDetails` and get data attributes from it with a dedicated method.
Encapsulate data and behaviour in an error-free way.
Prepare for refactoring of the rendering & layout code to make adding new features easier.
Unit tests added for the new class.
> refactor: add a container for `FieldLayoutDetails` and get data attributes from it

- src/TaskFieldRenderer.ts
- src/TaskLineRenderer.ts
- tests/TaskFieldRenderer.test.ts
- tests/TaskLineRenderer.test.ts
- `TaskFieldRenderer` now adds the data attributes to an `HTMLelement` instead of returning them (At the end of the day, this is what we need the data attributes for)
- Reworked tests to show this behaviour
- `TaskLineRenderer` calls to get the data attributes are shorter, `taskToHtml` more readable and comprehensive
- `AttributeDictionary` now used only in `TaskFieldRenderer.test.ts`
- Simpler code
- Prepare to for further refactoring to make rendering and layout code more flexible towards new features
- Get rid of `DataAttributes` in `src` (Possible in `test` as well, but need to update tests, probably good for another PR)
Modified unit tests.
> refactor: add data attributes in `TaskFieldRenderer` instead of returning them

- src/QueryRenderer.ts
When jumping to a task using the backlink (a feature introduced in version 3.4), then the default behavior of the associated click event should be suppressed.
If the task query appears in a callout, then clicking the backling will also trigger opening the callout for editing and selecting it. This default behavior interfers with our behavior of jumping to the task.
This PR should fix issue #2445.
_Confirmed: Fixes #2445_
- Obsidian 1.5.0 and Tasks 5.1.0
-  using the markdown shown in the issue
- also tested the case when the task and the query are located in different files.
> fix: Prevent default click behavior when jumping to a task

- src/QueryRenderer.ts
- src/lib/QueryRendererHelper.ts
- tests/lib/QueryRendererHelper.test.ts
Work started whilst pairing with @ilandikov
- Extract functions `getDateFieldToPostpone()` and `createPostponedTask()` from the postponing code in `QueryRenderer.ts`, to enable testing
- Added thorough tests of initial `getDateFieldToPostpone()` behaviour
- In order to start adjusting the behaviour, as documented in https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/2452
- Lots of tests added, of the current behaviour
- I have tested the extracting of code from `QueryRenderer.ts` manually, in the demo vault.
> refactor: Extract functions from postpone code, and start testing

- src/QueryRenderer.ts
- src/lib/QueryRendererHelper.ts
- tests/lib/QueryRendererHelper.test.ts
Teach `getDateFieldToPostpone()` to postpone start date, treat it same as scheduled & due date.
Expand postpone feature on happens date (start, due, scheduled).
Modified existing unit tests, exploratory testing with vault from GitHub workflow.
- I guess we will need a separate PR to add the docs for the whole feature
> feat: Enable postponing of start dates

- src/QueryRenderer.ts
- src/Scripting/Postponer.ts
- src/lib/QueryRendererHelper.ts
- tests/Scripting/Postponer.test.ts
- tests/lib/QueryRendererHelper.test.ts
- render postpone button after the edit button
- do not render 'Postpone' next to postpone button
- do not render the postpone button if task has DONE, CANCELLED or NON_TASK
- fix a typo in a notice
Improve postponement rendering & usability
Exploratory test
Note the position of the rendered postpone button on the last task only, absence of the 'Postpone' label and the absence of the postpone button among the first 3 tasks with different statuses (DONE, CANCELLED or NON_TASK)
> feat: postponement usability improvements

- src/Cache.ts
Do not index attachments after plugin has loaded.
Non-markdown files that were added, renamed or deleted after the plugin had loaded were being passed to Cache.indexFile() which was then reading them.
This could cause wasted work, and when deleting non-markdown files, would trigger Tasks search results to be needlessly redrawn.
It also generated warning messages for users who had the console open.
Fixes #2464
Exploratory testing in the Tasks-Demo vault.
> perf: Do not index attachments after plugin has loaded

- src/QueryRenderer.ts
Add missing `async`, `await` and `Promise` keywords, missing comma in a comment.
Have less distractions in WebStorm.
Just checked that there are less warnings =)
_Edit: Also smoke-tested [Tasks-Demo-VerifyCommit-Build3823-Run1](https://github.com/obsidian-tasks-group/obsidian-tasks/suites/18698076888/artifacts/1088288283)._
> refactor: fix async/await warnings in QueryRenderer.ts

- src/QueryRenderer.ts
Some minor refactoring of some symbols and parameter orders in `QueryRenderer.ts`.
Just  to try to make it easier to hold the code in memory, before further work.
- Running the smoke tests in a local build
> refactor: Rename postpone symbols and standardise parameter order

- tests/Scripting/Postponer.test.ts
Add tests to show the current behaviour of `shouldShowPostponeButton()` function depending on dates, present in the task - created, starts, due, scheduled & done.
Prepare to change the behaviour of `shouldShowPostponeButton()` according to https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/2452
Tried to break the new tests by putting wrong expected values =)
> test: add tests for `shouldShowPostponeButton()` against Task dates

- src/Scripting/TasksDate.ts
- tests/Scripting/TasksDate.test.ts
Postponing of future tasks no longer modifies the original date, which broke subsequent postponing operations.
The root cause was that the original task date was accidentally being modified.
Note: there is some further tidying up that can be done, like removing the call to `triggerRequestCacheUpdate()`, and removing debug logging. I'll tidy those up in later steps, so that this change is minimal.
Fixes #2471
- Updating tests that were failing
https://github.com/obsidian-tasks-group/obsidian-tasks/assets/4840096/f50dc4d5-7598-4f7c-9db5-4668d610a26d
> fix: Postponing now works repeatedly

- styles.css
In Tasks search results viewed in Live Preview, lines long enough to wrap  were not aligned correctly
down the left hand side.
The fix was kindly supplied by @mackaaij in #2361.
Fixes #2361.
In the Tasks demo vault.
In the following screenshots, look at the bottom half of the middle column:
See above
> fix: Correctly indent Tasks search results in Live Preview

- src/QueryRenderer.ts
- src/Scripting/Postponer.ts
- tests/Scripting/Postponer.test.ts
Rename variables with the following logic:
- `update` -> `postpone`
- `dateType` -> `dateField`
- `newTasks` -> `postponedTask`
Plus remove one type assertion since it is not needed by design (`HappensDate` type ensures the type).
Improve code readability.
Unit tests. Only automated refactorings used.
> refactor: rename variables in postpone code

- tests/TaskLineRenderer.test.ts
Rework TaskLineRenderer tests:
- Test the rendered `ListItem` directly instead of calling `parentRender.children`
- Remove redundant `mockInnerHtmlRenderer()`
- Split tests of the rendered `ListItem` inner structure and the `ListItem` appended to the parent `UnorderedList`
Simplify TaskLineRenderer tests to later increase coverage and conduct future TaskLineRenderer & TaskLayout refactorings.
Unit tests, breaking tests.
> test: improve TaskLineRenderer tests

- src/ui/EditInstructions/PriorityInstructions.ts
- src/ui/EditInstructions/TaskEditingInstruction.ts
- src/ui/Menus/PriorityMenu.ts
- src/ui/Menus/StatusMenu.ts
- src/ui/Menus/TaskEditingMenu.ts
- tests/ui/EditInstructions/PriorityInstructions.test.ts
- tests/ui/Menus/PriorityMenu.test.ts
Implement a Priorities context menu for editing tasks.
**Note: it is not yet exposed to users.**
Editing instruction classes:
- Introduce new interface `TaskEditingInstruction`: An instruction interface, for editing a Task object.
- Add `SetPriority` which implements `TaskEditingInstruction`
- Add function `allPriorityInstructions()` to provide all the available priority editing instructions
Menu classes:
- Push some code from `StatusMenu` down to new class `TaskEditingMenu`
- Introduce new class `PriorityMenu`. It is very simple, as most of the work is done by `allPriorityInstructions()` and `SetPriority`.
Here is how it might added to the Pencil button in QueryRenderer... the example is taken from the jsdocs:
```diff
import type { TasksEvents } from './TasksEvents';
+import { …
```
> internal: Add Priorities menu (not yet used anywhere in the plugin)

- src/Scripting/Postponer.ts
- tests/Scripting/Postponer.test.ts
Better menu items to postpone future dates.
Improve usability.
New unit tests + exploratory tests.
> fix: better menu items to postpone future dates

- src/Scripting/Postponer.ts
- src/Task.ts
- tests/Scripting/Postponer.test.ts
Any editing of a task that contains an invalid date ends up replacing the date's text with the literal string `invalid date`. This loses information.
So now we do not show postpone button for tasks that contain any invalid date values.
Avoid rewriting invalid dates such as `2023-13-35` with the literal text `invalid date`.
Unit test added + exploratory tests.
> fix: prevent postpone from overwriting invalid dates.

- src/Status.ts
- src/Task.ts
- src/ui/Menus/StatusMenu.ts
- tests/Status.test.ts
- tests/Task.test.ts
The context menu added in #2476 enables a few status transitions that were not previously available to users.
I found in exploratory testing that changing from one DONE status to a different DONE status did unexpected things:
- it created a new recurrence, if the task was recurring
- it updated the Done Date to the current date.
Also, I found that:
- Selecting the status that the task already had caused a new, identical task to be created unnecessarily.
This PR:
- Adds tests for the code used in the new statuses menu.
- These were initially-failing tests for the issues I found in exploratory testing.
- Then fixes the issues
- Adds test of the 'Set Done Date' setting (having spotted a gap in coverage before refactoring)
Enable me to release the feature added in #2476. …
> fix: Bug-fixes and tests for the new Statuses context menu

- src/QueryRenderer.ts
When clicking the "postpone" button (a feature introduced in version 5.3.0), then the default behavior of the associated click event should be suppressed.
If the task query appears in a callout, then clicking the postpone button will also trigger opening the callout for editing. This default behavior appears in addition to the desired behavior of postponing the task and is not expected to happen.
Moreover, when right-clicking the button, in addition to the postpone-context-menu, the default context menu for editing the callout will also appear on top of it. This PR fixes this problem as well. The default menu now only appears when right-clicking the callout outside of the postpone button.
Fixes #2512
- Obsidian 1.5.0 and Tasks 5.3.0
- using the markdown shown in the issue …
> fix: Prevent default action when clicking the postpone button

- src/IQuery.ts
- src/InlineRenderer.ts
- src/Query/Query.ts
- src/QueryLayoutOptions.ts
- src/QueryRenderer.ts
- src/TaskLayout.ts
- src/TaskLineRenderer.ts
- src/TaskSerializer/DataviewTaskSerializer.ts
- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/TaskLayout.test.ts
- tests/TaskLineRenderer.test.ts
Extract QueryLayoutOptions from LayoutOptions.
Starting to think about implementing issues such as #848 #2380 #2198 
Separate concerns between options for task & query rendering.
Unit tests + smoke tests (https://github.com/obsidian-tasks-group/obsidian-tasks/actions/runs/7263529954)
> refactor: extract QueryLayoutOptions from LayoutOptions

- tests/CustomMatchers/CustomMatchersForRendering.ts
- tests/CustomMatchers/jest.custom_matchers.setup.ts
- tests/TaskFieldRenderer.test.ts
- test adding data attributes with only name & only value
- Describe the current behaviour before any changes
- Increase coverage
New unit tests, breaking code
> test: test adding data attributes with only name & only value

- tests/TaskFieldRenderer.test.ts
- use the newly added toHaveDataAttributes() matcher in TaskFieldRenderer tests
Unit tests.
> test: use the toHaveDataAttributes() matcher in TaskFieldRenderer tests

- src/Task.ts
- tests/Commands/ToggleDone.test.ts
I looped through the statuses until a TODO status is found. I realize that there's a possibility of getting stuck in an infinite loop, another approach could be to loop for the length of the registered statuses and fallback if no appropriate status is found.
Issue #2304 
I wrote a test in `Commands/ToggleDone.test.ts` (not sure if this is the appropriate file to add the test to)
> fix: Cycle through statuses until TODO is found when marking recurring tasks as DONE

- src/StatusRegistry.ts
- tests/StatusRegistry.test.ts
More improvements to the selection of status of next task, when a recurring task reaches DONE status:
- fix: If can't find a TODO status for new recurrence, look for IN_PROGRESS
- fix: if no TODO or IN_PROGRESS in chain, return space symbol: '[ ]'
Remove more pitfalls from recurring tasks.
- Existing tests
- New tests
- Smoke tests
> fix: Next recurrent of recurring tasks is now always TODO, IN_PROGRESS or space

- src/StatusRegistry.ts
- tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled-with-unconventional-symbols.approved.detailed.mermaid.md
- tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled.approved.detailed.mermaid.md
Add an extra arrow to the Mermaid status diagrams, if Tasks overrides the status of a new recurrence of a recurring task to force the status type to be `TODO` or `IN_PROGRESS`.
Improve the usefulness of the "Check your Statuses" report.
- Reviewing the updated approval-test output mermaid diagrams in Obsidian
- Exploratory testing: reviewing the "Check your Statuses" in a vault that has statuses where recurrence status now gets overridden...
```mermaid
flowchart LR
classDef TODO        stroke:#f33,stroke-width:3px;
classDef DONE        stroke:#0c0,stroke-width:3px;
classDef IN_PROGRESS stroke:#fa0,stroke-width:3px;
classDef CANCELLED   stroke:#ddd,stroke-width:3px;
classDef NON_TASK    stroke:#99e,stroke-width:3px;
1["'Todo'<br>[ ] -> [/]<br>(TODO)"]:::TODO
2["'Done'<br>[x] -> …
```
> feat: Show non-standard recurrence transitions in Mermaid diagrams

- docs/Introduction.md
- docs/Queries/Explaining Queries.md
- docs/Queries/Line Continuations.md
- docs/Queries/Regular Expressions.md
- docs/Scripting/Placeholders.md
- src/Query/Filter/Field.ts
- src/Query/Filter/FunctionField.ts
- src/Query/Filter/MultiTextField.ts
- src/Query/Filter/UrgencyField.ts
- src/Query/Grouper.ts
- src/Query/Query.ts
- tests/Config/DebugSettings.test.ts
- tests/Query.test.ts
- tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_filters-date-examples.approved.explanation.text
- tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-week-month-quarter-year.approved.explanation.text
- tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-weekday.approved.explanation.text
- tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
- tests/TaskGroups.test.ts
- tests/lib/QueryRendererHelper.test.ts
1. Make `explain` list the Query's `group by` instructions.
2. Update the documentation
The white-spacing is not super consistent with other instructions. Sometimes there are two blanks instead of one - but I will tidy that up later on. The main thing is that the information is present now.
Fixes #2105.
This is part of preparation for #2074 - I want to be able to show what `group by` instructions are in use, and test the removal of them via something like `clear group by`.
- Via tests
- Via exploratory testing
> feat: Make 'explain' show 'group by' commands

- docs/Queries/Explaining Queries.md
- src/Query/Explain/Explainer.ts
- tests/Config/DebugSettings.test.ts
- tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
- tests/Query/Explain/Explainer.test.ts
- tests/lib/QueryRendererHelper.test.ts
Tidy up the blank lines in `explain` output:
- Remove some duplicate blank lines
- Add some missing blank lines
See differences in the test output.
Make the code easier to maintain, before adding some more explanations.
> fix: Tidy up blank lines in 'explain' output

- docs/Queries/Explaining Queries.md
- docs/Queries/Line Continuations.md
- docs/Queries/Regular Expressions.md
- docs/Scripting/Placeholders.md
- src/Query/Explain/Explainer.ts
- src/Query/Filter/Filter.ts
- src/lib/QueryRendererHelper.ts
- tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text
- tests/Query/Explain/Explainer.test.ts
- tests/Query/Filter/Filter.test.ts
- tests/lib/QueryRendererHelper.test.ts
Use indentation in the `explain` output, so that it is easier to see which instructions are from the Global Query, and which from the Tasks Query Block.
I've been finding that it's quite hard to see the end of the Global Query explanation and the start of the Tasks Query Block explanation in my main vault.
- Updating and adding automated tests
- Exploratory testing in the demo vault.
```text
Explanation of the global query:
heading includes tasks
No grouping instructions supplied.
At most 50 tasks.
Explanation of this Tasks code block query:
not done
due next week =>
due date is between:
2022-10-24 (Monday 24th October 2022) and
2022-10-30 (Sunday 30th October 2022) inclusive
No grouping instructions supplied.
```
```text
Explanation of the global query:
heading includes tasks
No grouping …
```
> feat: Use indentation to separate global & code block query explanation

- tests/TaskLineRenderer.test.ts
LayoutOptions are now tested with a hardcoded task. With this PR the test task is taken from `TaskBuilder.createFullyPopulatedTask()` and the task line parameter is removed from the test helper.
- If a new task field is added
- It will be seen in the tests (Task field added in `TaskBuilder.createFullyPopulatedTask()` with `// NEW_TASK_FIELD_EDIT_REQUIRED`), so the tests are stronger
- Remove the need to update each test
- For instance, the `CreatedDate` field is missing in some tests...
- Remove redundant data between tests (the task line)
Breaking unit tests.
> test: test `LayoutOptions` with the full task from `TaskBuilder`

- tests/CustomMatchers/CustomMatchersForRendering.ts
- tests/CustomMatchers/jest.custom_matchers.setup.ts
- tests/TaskLineRenderer.test.ts
- add custom matchers for rendering tests
- reformulate test descriptions
- one test is now marked as failing. Now that data attributes are checked as a string, a bug is shown:
- actual: data attribute with an empty value is added
- expected: absence of the data attribute
- make the test functions obvious for understanding
- return meaningful messages in case of errors
Please mind the increased number of lines, the tests will be refactored further, this is a (small-er) step towards that and the volume will decrease.
Unit test, breaking code.
Without matchers:
Matchers now return informative message:
> test: improve rendering tests with matchers

- src/TaskFieldRenderer.ts
- tests/TaskFieldRenderer.test.ts
- tests/TaskLineRenderer.test.ts
After refactoring tests, a bug has been revealed (it was present before, but unseen due to the way the tests were done).
Current behaviour: data attributes with empty values are added.
Fixed behaviour:  data attributes with empty values are not added.
Fix bugs =)
Unit tests.
> refactor: do not add data attribute when it's value is empty

- src/TaskFieldRenderer.ts
- src/TaskLineRenderer.ts
- tests/TaskFieldRenderer.test.ts
`TaskFieldRenderer` has a `className()` method acting like a data getter (get a component's class). The data is used later to add to an `HTMLElement`. This PR replaces it with a `addClassName()` method that add the class to the target `HTMLElement`.
Previously `className()` was written in mind with usage in tests as well (As a provider of data). However #2545 removed the relation between the data in `TaskFieldRenderer` and the data in the tests.
- have testable behaviour instead of data in `TaskFieldRendrer`
- hide implementation details of adding classes inside `TaskFieldRenderer`
- have uniform behaviour in `TaskFieldRenderer`: `addClassName()`, `addDataAttribute()`, ...
New unit tests, breaking the code.
> refactor: replace `className()` method with `addClassName()`

- src/IQuery.ts
- src/InlineRenderer.ts
- src/Layout/TaskLayoutOptions.ts
- src/Query/Query.ts
- src/QueryRenderer.ts
- src/TaskLayout.ts
- src/TaskLineRenderer.ts
- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/Layout/TaskLayoutOptions.test.ts
- tests/TaskLayout.test.ts
- tests/TaskLineRenderer.test.ts
Rewrite `TaskLayoutOptions` to have a container the data as a dictionary.
Done as a pairing session with @claremacrae.
By the end of this refactoring:
* `TaskLayoutOptions` has moved:
* from
* `src/TaskLayout.ts`
* to:
* `src/Layout/TaskLayoutOptions.ts`
* It now encapsulates some behaviours associated with showing and hiding components, both in serialising/deserialising task lines, and in rendering tasks:
* Instead of being a collection of unrelated `boolean` values, it now stores a container of `boolean` values, which are looked up with a `TaskLayoutComponent` value
* this makes it much more convenient to use in the various bits of code that loop over collections of `TaskLayoutComponent` values
* This new encapsulation has simplified the implementation of `TaskLayout` nicely, removing …
> refactor: rewrite TaskLayoutOptions to key on TaskLayoutComponent

- src/Layout/TaskLayoutOptions.ts
- src/TaskLayout.ts
- tests/TaskLayout.test.ts
Following the previous refactoring:
- rename `defaultLayout` to `taskLayoutComponents`
- remove unused methods in `TaskLayout`
- group similar code around
Code readability and clarity.
Unit tests.
> refactor: cleanup `TaskLayout.ts`

- resources/sample_vaults/Tasks-Demo/Functions/Custom Sorting.md
- src/Query/Filter/FunctionField.ts
- src/Query/Query.ts
- src/lib/TypeDetection.ts
- tests/Query/Filter/FunctionField.test.ts
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.folder_results.approved.txt
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.file_properties_task.file.root_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.filename_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.folder_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.path_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.root_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.heading_docs.approved.md
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.heading_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.ts
- tests/TestHelpers.ts
- tests/lib/TypeDetection.test.ts
This is the second half of implementing `sort by function`.
All that remains now is to add support for using `query.file.path` and related in the scoring functions.
This adds:
- thorough testing of `sort by function`
- error-checking, with error messages shown to users in Tasks search results
- A sample file in the vault that shows the error message displayed for various problem uses of `sort by function`.
- sorting of `TasksDate` and `Moment` via `sort by function` is now consistent with the behaviour of `sort by due` and friends, that is, undated tasks go after all tasks with dates
- type safety of sort keys:
- `undefined`, arrays and `NaN` values cannot be used as sort keys
- `null` can be compared with any supported key type
- otherwise, for safety, values of different types cannot be …
> feat: Complete implementation of 'sort by function'

- docs/Queries/Sorting.md
- docs/Support and Help/Breaking Changes.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Invalid dates with Sorting and Grouping.md
- src/lib/DateTools.ts
- tests/lib/DateTools.test.ts
- `sort by due` - and sort by other date fields - now puts tasks with an invalid date before the valid ones, so invalid dates are more visible in long lists.
- update documentation to record this change
I'm treating this as a **breaking change** because it does change search results, although I am confident it is an improvement.
Fix #2589.
- Updating existing tests
> fix!!: Sort invalid dates before valid ones in query results

- docs/Queries/Grouping.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Invalid dates with Sorting and Grouping.md
- src/Query/Filter/DateField.ts
- tests/Query/Filter/CancelledDateField.test.ts
- tests/Query/Filter/CreatedDateField.test.ts
- tests/Query/Filter/DoneDateField.test.ts
- tests/Query/Filter/DueDateField.test.ts
- tests/Query/Filter/HappensDateField.test.ts
- tests/Query/Filter/ScheduledDateField.test.ts
- tests/Query/Filter/StartDateField.test.ts
Make invalid dates more prominent in `group by due` and friends.
Fixes #2591.
> fix: `group by [date]` now `Invalid [date] date` as first heading

- docs/Queries/Sorting.md
- docs/Scripting/Custom Sorting.md
- resources/sample_vaults/Tasks-Demo/Functions/Custom Sorting.md
- src/Query/Filter/FunctionField.ts
- tests/Query/Filter/FunctionField.test.ts
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.folder_docs.approved.md
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.folder_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.other_properties_task.isDone_docs.approved.md
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.other_properties_task.isDone_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.other_properties_task.isRecurring_docs.approved.md
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.other_properties_task.isRecurring_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.ts
This makes the results easier to reason about, and easier to document.
Change `sort by function` for `boolean` expressions so that tasks are now sorted in the order:
1.  tasks giving expression value `true` come first
2. then all the tasks giving expression value `false` are listed.
Previously I opted to sort the opposite way round, but this turned out to be confusing in use.
One had to know to use either of these:
```
sort by function ! task.isRecurring
sort by function reverse task.isRecurring
```
Now this works:
```
sort by function task.isRecurring
```
It feels logical to me that the tasks that match the `boolean` expression are the ones that are shown first.
This is another part of fixing #1479 - and trying to get the work I did in #2577 ready for release.
It will also make the docs …
> fix: 'sort by function' now sorts 'true' before 'false'

- docs/Getting Started/Priority.md
- docs/Introduction.md
- docs/Queries/Sorting.md
- docs/Support and Help/Breaking Changes.md
- src/Query/Sort.ts
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.other_properties_task.isDone_results.approved.txt
- tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.statuses_task.status.nextSymbol_results.approved.txt
- tests/Sort.test.Sort_save_default_sort_order.approved.text
- tests/Sort.test.Sort_visualise_default_sort_order.approved.txt
- tests/Sort.test.ts
- Document the default sort order
- Fix problem that old, high-priority `DONE` tasks were often sorted before current `IN_PROGRESS` and `DONE` tasks.
I've documented this as a fix that is potentially a breaking change, just because it is so fundamental.
But it's clearly an improvement.
Fixes #439
- Via approval tests to visualise the change in behaviour.
- Exploratory testing.
Here is a screenshot of the changes in sort order for a sample selection of tasks in the tests.
In the new order, the tasks are clearly sorted in order `IN_PROGRESS`, `TODO`, `DONE`, `CANCELLED` then `NON_TASK`.
> fix!!: Make default sort order sort first by status type

- src/Layout/LayoutHelpers.ts
- src/Layout/QueryLayout.ts
- src/Layout/TaskLayout.ts
- src/Renderer/QueryRenderer.ts
- tests/Layout/TaskLayout.test.ts
Rename some variables and move code around. Only automated refactorings.
Improve code readability, some clean-up had to be after #2610
Unit tests.
> refactor: `TaskLayout`& `QueryLayout` renames

- docs/Introduction.md
- docs/Queries/Grouping.md
- docs/Scripting/Query Properties.md
- src/Query/SearchInfo.ts
- src/Scripting/QueryContext.ts
- tests/Scripting/QueryContext.test.ts
- tests/Scripting/QueryProperties.test.query_search_properties.approved.md
- tests/Scripting/QueryProperties.test.ts
- tests/Scripting/ScriptingTestHelpers.ts
- Add new query property `query.allTasks`
- Update documentation
This will be needed for custom filters, sorting and grouping with task-dependency-related properties.
- Added new test
> feat: Expose `query.allTasks` in scripting

- src/Layout/TaskLayoutOptions.ts
- src/Query/Query.ts
- src/Renderer/TaskLineRenderer.ts
- src/TaskSerializer/DataviewTaskSerializer.ts
- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/Layout/TaskLayoutOptions.test.ts
- tests/Renderer/TaskFieldRenderer.test.ts
- tests/Renderer/TaskLineRenderer.test.ts
- convert `TaskLayoutOptions` to `enum`
- remove a place to edit when adding new `Task` field (`// NEW_TASK_FIELD_EDIT_REQUIRED`)
- replace `Task` fields `string` values with references to `enum`
- create a single container for `TaskLayoutOptions` value
- strengthen the code by having links to values instead of values
- decrease number of places to edit when adding new `Task` field (`// NEW_TASK_FIELD_EDIT_REQUIRED`)
Unit tests.
> refactor: convert `TaskLayoutOptions` to `enum`

- src/Renderer/QueryRenderer.ts
- styles.css
The context menu for the "postpone" button stopped working on iOS in v6 of Obsidian Tasks.
Also, when using "long press" to evoke the context menu, various side effects could be triggered on iOS even in versions before, like selecting text or showing a default browser callout.
The bug seems to be caused by using an anchor element with a href in v6 instead of a button element, so that it could be styled the same way as the edit button.
The following changes have been made to fix the issue:
- removed the `href` attribute from the anchor tag
- set user-select  CSS  property to none to prevent the button from being selectable
- set touch-callout CSS  property to none to prevent the buttons from showing a default callout
- called `event.stopPropagation()` to prevent further handling of the …
> fix: Make context menu for Postpone button work on iOS

- src/Obsidian/File.ts
Fix async awaits in File.ts. This has been suspected to be a problem for some time but we didn't have a way to test it.
It turned out to fix #2638.
Fixes #2638.
Exploratory testing and running relevant smoke tests.
> fix: enable edit task modal to save multiple tasks

- src/TaskSerializer/DataviewTaskSerializer.ts
- tests/TaskSerializer/DataviewTaskSerializer.test.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
Several fixes to the parsing of ids and dependsOn values in dataview format.
- `dependsOn` is now read
- `dependsOn` now allows capitals in IDs
- `id` now allows capitals in IDs
This makes these fields consistent with the parsing of Tasks Emoji format.
Fixes #2667, and some other issues found when writing tests
- Adding new tests, which initially failed
- Exploratory testing, including confirming that the sample markdown in #2667 now works.
- _This was a fix to a not-yet released feature._
> fix: Dataview-format parses 'Task.id' and 'Task.dependsOn' same as emoji

- docs/Editing/Auto-Suggest.md
- src/Suggestor/EditorSuggestorPopup.ts
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.ts
I have optimized the function of auto-suggest in dataview task format, in dataview task format
1. removed the extra space when accepting the suggestion.
2. modified the effect of accepting the 'Enter' suggestion, now it will make the cursor jump out of the current task property.
3. fixed the duplicate words in the priority suggestion.
1. when I accept the day suggestion, it will add a extra space after date, see gif below
2. when I accept the 'Enter' suggestion, it will break my current task property and split the `]` to next line. see gif below
3. below is duplicate words bug in the priority suggestion when in dataview task format
4. My pull request solve the 3 issue above, which is shown below:
For I only modify the auto-suggest action, I just test all type of suggestions, include …
> fix: Improve auto-suggest for dataview task format

- src/Task/OnCompletion.ts
- src/Task/Task.ts
- tests/Task/OnCompletion.test.ts
Since migrating functionality out of `Tasks.ts` and into `OnCompletion.test.ts` during pairing session, I've fixed code and existing tests.
Also renamed existing tests to (hopefully) make their purposes clearer.
Added failing test for NOT executing _OnCompletion_ feature's actions on already-DONE tasks
Added code to make the above test pass.
Tasks plugin's existing tests are passing, plus those within `OnCompletion.test.ts`.
Changes visible to users:   None as yet.
- [?] My change has _adequate_ [Unit Test coverage](https://publish.obsidian.md/tasks-contributing/Testing/About+Testing).
> refactor:  OnCompletion (preparing to later add Delete Action)

- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
Fix parsing of Priority emoji with Variant Selector 16 appended.
Fixes #2273.
- New tests, initially failing.
- Manual exploratory testing - confirming I could reproduce the problem behaviour before the fix, and that it was then behaving correctly afterwards.
None.
> Fix priority with vs16

- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
Enable Tasks to read dependsOn emoji - ⛔ - that do not have the Variant Selector 16 (VS16) character.
That invisible character was accidentally included in the Tasks plugin source code, meaning Tasks would only parse dependsOn values with that character.
_Note: This does not yet stop Tasks writing out VS16 for this emoji - I will do that as a separate PR as it's quite a large change._
Fix #2693.
- Adding new tests, which initially failed
- Exploratory testing to confirm that I could reproduce the bug before the fix, and that it was fixed afterwars
> fix: Enable Tasks to read "no entry" emoji from Emoji Shortcodes plugin

- docs/Advanced/Styling.md
- docs/Getting Started/Task Dependencies.md
- docs/How To/Find tasks with invalid data.md
- docs/Introduction.md
- docs/Queries/Filters.md
- docs/Reference/Task Formats/Tasks Emoji Format.md
- docs/Scripting/Task Properties.md
- resources/sample_vaults/Tasks-Demo/Formats/Tasks Format.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Dependencies Samples - Recurring Tasks.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Dependencies Samples.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Seeing the Query as HTML/HTML from Query - short mode.html
- resources/sample_vaults/Tasks-Demo/Manual Testing/Seeing the Query as HTML/HTML from Query.html
- resources/sample_vaults/Tasks-Demo/Manual Testing/Seeing the Query as HTML/HTML from Query.md
- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/DocumentationSamples/DependencyDocs/DependencySamples.test.blocking_and_blocked_filters_blocking_and_blocked.approved.md
- tests/DocumentationSamples/ValidateTasks.test.validate-tasks_find-unread-emojis.approved.text
- tests/Query/Filter/BlockingField.test.ts
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
- tests/Renderer/TaskLineRenderer.test.ts
- tests/Scripting/TaskProperties.test.task_other_fields.approved.md
- tests/Task/Task.test.task_dependencies_blocking_and_blocked.approved.txt
- tests/Task/Task.test.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
- tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Dependencies_tasksPluginEmoji-include.approved.md
- tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_Dependencies_tasksPluginEmoji-snippet.approved.md
- tests/TestingTools/SampleTasks.ts
- tests/TestingTools/TaskBuilder.test.ts
- tests/ui/DependencyHelpers.test.ts
- tests/ui/EditInstructions/SetTaskDependenciesInstruction.test.ts
Don't add an invisible character (Variant Selector 16) to the end of the ⛔ emoji, for dependsOn values.
And remove all Variant Selector 16 except those that are necessary for tests.
Fix an issue which was discovered when investigating #2693.
- Via automated test
- Via manual exploratory testing
> fix: Stop writing Variant Selector 16 on dependsOn emojis - ⛔

- docs/Getting Started/Getting Started.md
- src/Renderer/TaskLineRenderer.ts
- src/Task/TaskLocation.ts
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_full_mode.approved.html
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_short_mode.approved.html
- tests/Task/TaskLocation.test.ts
Stop Tasks registering callbacks when rendering tasks that have an empty path, meaning they are likely from canvas notes.
Fix #2130.
- Unit tests
> fix: Tasks no longer prevents checking off tasks on Canvas cards

- src/lib/DateTools.ts
- src/ui/EditTask.svelte
Pairing session with @claremacrae 
Move several pure functions from Svelte code to DateTools.ts
Prepare for future refactoring of Edit Task modal.
Unit test + smoke test (open the modal and verify it), breaking code
> refactor: move date functions to DateTools.ts

- docs/Queries/Explaining Queries.md
- docs/Queries/Line Continuations.md
- docs/Scripting/Placeholders.md
- src/Query/Filter/Filter.ts
- src/Query/Statement.ts
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
- tests/Query/Explain/Explainer.test.ts
- tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
- tests/Query/Query.test.ts
- tests/Query/Statement.test.ts
The `explain` instruction now successfully explains Continuations and Placeholders for filter lines.
See #2349 - for which this is a partial solution.
Still to do: explanations of [Continuations](https://publish.obsidian.md/tasks/Queries/Line+Continuations) and [Placeholders](https://publish.obsidian.md/tasks/Scripting/Placeholders) for `sort by function` and `group by function`. 
- New tests
- Lots of exploratory testing
Changes in the documentation:
> feat: 'explain' shows Continuations and Placeholders for filters

- tests/Renderer/TaskLineRenderer.test.ts
- tests/TestingTools/HTMLHelpers.ts
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
- tests/ui/EditTask.test.ts
- tests/ui/__snapshots__/EditTask.test.ts.snap
Add HTML snapshot test to verify/void changes in the Edit Task modal.
Have a "state" test of the task modal. So far we had only "action" tests - task editing (field change -> changed task) & task rendering (task -> field with correct task data).
Snapshot test =)
> test: add Edit Task modal snapshot test

- src/ui/DateEditor.svelte
- src/ui/EditTask.svelte
- Introduce <DateEditor/> Svelte component to reduce repetition in `EditTask.svelte`
- Reduce repetition
- Enable future usability improvements to date editing
- Unit tests
- Exploratory tests
> refactor: create DateEditor Svelte component

- docs/Queries/Explaining Queries.md
- src/Query/Filter/BooleanField.ts
- src/Query/Filter/Filter.ts
- tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_explain.approved.txt
- tests/Query/Filter/BooleanField.test.ts
Fix the `explain` output for filters inside Boolean expressions, where the filter's explanation was more than a single line.
Previously, the source line was not displayed in that situation, and now it is.
Fix #2707
- Fix the failing test that I added in 0328f4926ee31e9c011c1dae01955d5600e005e0 to demonstrate this bug.
- Update the results of a few existing tests.
- Exploratory testing.
> fix: 'explain' omitted the instruction line in some Boolean expressions

- src/Commands/CreateOrEditTaskParser.ts
- src/Commands/ToggleDone.ts
- src/Obsidian/Cache.ts
- src/Obsidian/InlineRenderer.ts
- src/Obsidian/LivePreviewExtension.ts
- src/Task/DateFallback.ts
- src/Task/Task.ts
- src/Task/TaskLocation.ts
- tests/Query/Query.test.ts
- tests/Statuses/StatusRegistry.test.ts
- tests/Task/DateFallback.test.ts
- tests/Task/Task.test.ts
- tests/Task/TaskLocation.test.ts
- tests/TestingTools/FilterTestHelpers.ts
- tests/TestingTools/TaskBuilder.ts
- tests/TestingTools/TestHelpers.ts
Preparing for https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/232#discussioncomment-8477015
Unit tests + manual test in demo vault
> refactor: move `TasksFile` object to `TaskLocation`

- src/Query/Filter/BooleanDelimiters.ts
- src/Query/Filter/BooleanField.ts
- src/lib/RegExpTools.ts
- tests/Query/Filter/BooleanDelimiters.test.ts
- tests/Query/Filter/BooleanField.test.ts
- tests/lib/RegExpTools.test.ts
A pure refactoring:
- Add class `BooleanDelimiters` that will grow to manage tracking of `(...)` and `"..."` in Boolean instructions
- `BooleanField` now has a constructor which uses `BooleanDelimiters.allSupportedDelimiters()`
- Add `checkRegExpsIdentical()` to aid refactoring regular expressions
- Add multiple tests to `BooleanField.test.ts`
Preparing to work on:
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1308
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1500
- Unit tests
> Refactor booleans step1

- src/Query/Filter/BooleanDelimiters.ts
- src/Query/Filter/BooleanField.ts
- tests/Query/Filter/BooleanDelimiters.test.ts
- tests/Query/Filter/BooleanField.test.ts
This fixes an unreported bug that whilst single-case Boolean filters like this worked:
```
(description includes abc)
```
ones like this did not:
```
"description includes abc"
```
When I fixed #1170, I only fixed it for `(...)` and not for `"..."`.
- Improves the fix for #1170
- And I needed to make the behaviour of `()` and `""` consistent in this area, to simplify later steps in improving Boolean filtering code.
- Unit tests
> fix: allow Boolean filters such as "description includes abc"

- src/Query/Filter/BooleanPreprocessor.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_preprocess_-_split_line.approved.txt
- tests/Query/Filter/BooleanField.test.ts
- tests/Query/Filter/BooleanPreprocessor.test.ts
- TDD the creation of `BooleanPreprocessor.splitLine()`
I'm calling this a refactoring as the code is not yet used in the plugin, so there is no visible change in behaviour.
Working towards fixing:
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1308
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1500
- Automated tests only, as code is not yet used in the plugin
> refactor: Start new code for preprocessing Boolean instructions

- src/Query/Filter/BooleanDelimiters.ts
- src/Query/Filter/BooleanPreprocessor.ts
- tests/Query/Filter/BooleanDelimiters.test.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_preprocess_-_rewrite.approved.txt
- tests/Query/Filter/BooleanField.test.ts
- tests/Query/Filter/BooleanPreprocessor.test.ts
*Note: this is labelled as a refactor as the new code is not yet used in the Tasks plugin.*
This extends `BooleanPreprocessor` to add a more sophisticated implementation for preprocessing Boolean/combined filters.
- Add `BooleanPreprocessorResult
- Add `BooleanPreprocessor.preprocessExpression()`
This change - and especially the new method `isAFilter()` - is the result of several weeks and many, many hours of trying to maintain existing working searches, whilst also adding support for filters that contain the following characters:
- `(`
- `)`
- `"`
The one current caveat with this implementation is that it does not work for filters the **end** with any of the characters `()"`, as they are swallowed up and treated as delimiters.
So for example, this filter:
```
(description includes …
```
> refactor: Implement new preprocessor for Boolean searches

- src/Query/Filter/BooleanField.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_explain.approved.txt
- tests/Query/Filter/BooleanField.test.ts
Major fix of Boolean filters, to allow use of `(`, `)` and `"` in filters within Boolean expressions.
The one current caveat with this implementation is that it still does not work for filters the **end** with any of the characters `()"`, as they are swallowed up and treated as delimiters.
So for example, this filter:
```
(description includes "maybe")
```
is interpreted as this simplified line - note the stray `"`:
```
(f1")
```
where `f1` is this - note the missing `"`:
```
description includes "maybe
```
`filter by function` instructions are very likely to end with `)`, due to the expression often ending with a function call.
Available workarounds:
- add a trailing `;` at the end of any `filter by …
> fix: allow filters with ( ) and " delimiters in Boolean filters

- src/Query/Filter/BooleanField.ts
- src/Query/Filter/BooleanPreprocessor.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_explain.approved.txt
- tests/Query/Filter/BooleanField.test.ts
Provide meaningful information to help users trouble-shoot any problems with Boolean filters.
(This replaces #2760 which was created before I pushed some changes to `main`)
Try to provide a 'help' message rather than 'error' message.
Based on: <https://twitter.com/travis_simon/status/1069074730211135488>
Before:
```text
malformed boolean query -- Unexpected character: " (check the documentation for guidelines)
```
After:
```text
Could not interpret the following instruction as a Boolean combination:  
(description includes "hello world") OR (description includes "42")  
The error message is:  
malformed boolean query -- Unexpected character: " (check the documentation …
```
> feat: Provide better Boolean help messages

- src/Query/Filter/BooleanDelimiters.ts
- src/Query/Filter/BooleanField.ts
- src/Query/Filter/BooleanPreprocessor.ts
- tests/Query/Filter/BooleanDelimiters.test.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_explain.approved.txt
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_preprocess_-_rewrite.approved.txt
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_preprocess_-_split_line.approved.txt
- tests/Query/Filter/BooleanField.test.ts
- tests/Query/Filter/BooleanFieldVerify.ts
- tests/Query/Filter/BooleanPreprocessor.test.ts
- tests/Query/Query.test.ts
Disallow the mixing of `(...)` and `"..."` delimiters in Boolean queries.
This reduces the number of scenarios in which we will accidentally treat a character in the filter as a delimiter.
Since the documentation discouraged use of " as a delimiter, it is unlikely to break any/many real-world searches - but it is a breaking change.
This mixture used to be allowed:
```text
"not done" AND (is recurring)
```
It now gives the error:
```text
Tasks query: Could not interpret the following instruction as a Boolean combination:
"not done" AND (is recurring)
The error message is:
All filters in a Boolean instruction must be inside one of these pairs of delimiter characters: (...) or "...". Combinations of those …
```
> feat!!: Disallow mixing delimiter types in Boolean queries

- src/Query/Filter/BooleanDelimiters.ts
- src/Query/Filter/BooleanPreprocessor.ts
- tests/Query/Filter/BooleanDelimiters.test.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_explain.approved.txt
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_preprocess_-_rewrite.approved.txt
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_preprocess_-_split_line.approved.txt
- tests/Query/Filter/BooleanField.test.ts
- tests/Query/Filter/BooleanFieldVerify.ts
- tests/Query/Filter/BooleanPreprocessor.test.ts
- tests/Query/Query.test.ts
Support square brackets (`[...]`) and curly braces (`{...}`)  to surround Boolean sub-expressions.
To add some alternatives to `(...)` and `"..."`, for when a required filter ends with either `)` or `"`, which would otherwise be treated as part of the Boolean logic rather than the filter.
Example new lines:
```test
[filter by function task.description.includes('a')] AND [description includes "hello world"]
{filter by function task.description.includes('a')} AND {description includes "hello world"}
```
- *Will be done later*
> feat: Support square brackets and curly braces to surround Boolean sub-expressions

- src/Query/Filter/BooleanPreprocessor.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_explain.approved.txt
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_preprocess_-_rewrite.approved.txt
- tests/Query/Filter/BooleanField.test.ts
- tests/Query/Filter/BooleanPreprocessor.test.ts
Make the parsing of Boolean filters a bit more forgiving, by adding any missing spaces around Boolean operators
This is easy to do now that we have the simplified instruction line.
*Note: I will update the documentation in a separate PR.*
For example this line:
(path includes a)AND NOT(path includes b)
Becomes this:
(f1)AND NOT(f2)
Which Tasks now converts to this, which just works:
(f1) AND NOT (f2)
Previously the above input line gave this error:
```
Tasks query: malformed boolean query -- Unexpected character: A.
A closing parenthesis should be followed by another closing parenthesis or whitespace
(check the documentation for guidelines)
```
- *Will be done later*
> feat: Fix any missing spaces around Boolean operators

- resources/sample_vaults/Tasks-Demo/Filters/Boolean Combinations.md
- src/Query/Filter/BooleanField.ts
- src/Query/Query.ts
- src/Query/Statement.ts
- tests/Query/Filter/BooleanField.test.boolean_query_-_exhaustive_tests_explain.approved.txt
- tests/Query/Query.test.ts
- tests/Query/Statement.test.ts
Provide more meaningful information to help users trouble-shoot any problems with Boolean filters.
1. When there is an error parsing a Boolean filter, show the user which sub-expressions have any problems that need fixing. (See 'Screenshots' heading below...)
2. When there is an error parsing any statement, show any continuation lines, and placeholders, to aid in locating the error in the query.
3. Add some sample problem queries to the test vault, to inspect the results of this PR.
- See `resources/sample_vaults/Tasks-Demo/Filters/Boolean Combinations.md`
- The new descriptive text may be useful in updating the docs for Boolean filters.
Try to make it easier still for users to diagnose errors with:
- …
> feat: Further improve Boolean help messages

- src/ui/EditTask.scss
Pure refactoring - nest CSS classes by their parent
Improve readability and make changes and reasoning about CSS classes in `EditTask.scss` simpler.
Visual test in demo vault.
- CSS not covered by unit tests
> refactor: group CSS classes

- docs/Getting Started/Task Dependencies.md
Fixed one word in the task dependency documentation
Makes documentation more readable.
Documentation change not needing testing.
> fix typo in Task Dependencies.md

- src/ui/EditTask.scss
- Order CSS classes by their appearance in `EditTask.svelte`
- Pure refactoring, no change in behaviour
- Make changes easy in the Edit Task modal
- Prepare to extract repeated behaviour in the Edit Task modal
Visual test in demo vault.
- No unit testing on CSS code
> refactor: reorder CSS classes in `EditTasks.scss`

- src/ui/EditTask.scss
In Priority section:
- Use color from the Obsidian for the checked radio button (Default blue -> Obsidian violet, like the checkbox for "Only future dates")
- Align the grid that positions the priority values with the date sections
Consistent look the edit task modal.
Visual test in demo vault.
Before             |  After
:-------------------------:|:-------------------------:
- no unit test for CSS code
> fix: align the look of `Priority` section in task modal with date sections

- src/ui/EditTask.svelte
The Cancelled and Done date have recently received access keys (`x` and `-`) and they are shown in the Edit Task modal. However when the setting `Provide access keys in dialogs` is disabled, the access keys are still shown in the Edit Task modal. This PR fixes that bug.
Consistency of UI & behaviour.
Manual test in demo vault. An automated unit test can be established, however I'm not sure of its necessity.
Provide... in settings | Before             |  After
:-------------------------:|:-------------------------:|:-------------------------:
ON | ![Снимок экрана 2024-05-02 в 13 39 29](https://github.com/obsidian-tasks-group/obsidian-tasks/assets/93825870/e4c8a12a-fdb5-4c93-90f7-2babad2a3e7e) | ![Снимок экрана 2024-05-02 в 13 40 22](https://github.com/obsidian-tasks-group/obsidian-tasks/ass …
> fix: remove access keys mentions when access key setting is disabled

- src/ui/EditTask.scss
Compilation of cleanup commits:
- Remove unused classes (Absent in HTML/Svelte code)
- Replace `margin` & `line-height` properties with more suitable `grid-*` options
- Remove some unused properties that have no impact on any view
You may notice on the screenshots that the modal became a bit smaller, more compact. This is due to a slight difference in the spacing between the some blocks. So this is not exactly a pure refactoring, however adjusting this spacing was done in a suboptimal way currently (using fixed margins, different ways to render blocks in several places). So I will make that adjustable later on after further refactoring in a compact way.
Prepare for extraction of components from Svelte & CSS code
Visual test in demo vault of each Edit Task modal view (different widths) …
> refactor: clean `EditTask.scss`

- docs/Advanced/Tasks Api.md
- src/Suggestor/EditorSuggestorPopup.ts
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.ts
Kanban v2-beta now uses obsidian's native markdown editor. This means that getting tasks working in Kanban cards is fairly easy. This PR serves as an example of how this could be done. I'm not familiar with this code base, however, so not sure if this is the best way to implement Kanban support. Feel free to close this an implement in a different way if desired.
Folks have asked for the Kanban plugin to support tasks for a long time now, but it was challenging in the past due to the custom markdown editor that was used. I tried to add support 100% in the Kanban plugin, but there are some major hurdles to doing so. Specifically, kanban does not supply the tasklist formatting to the editor so the editor suggest thinks its in a plain markdown string.
I've run `yarn test`. I also tested …
> feat: Allow showing/suppressing the Auto-Suggest in custom editor implementations

- src/Suggestor/Suggestor.ts
- tests/Obsidian/ObsidianSearchFacilities.test.ts
- tests/Suggestor/Suggestor.test.ts
- tests/__mocks__/obsidian.ts
- Replace an Obsidian-specific `string.contains()` with `string.includes()` which is available when run via tests.
- Add some initial tests to capture the behaviour of auto-suggest facilities added in #2771.
- Add a fake implementation of `prepareSimpleSearch()` - with its own tests - so that I could test suggestions made for the dependsOn field.
- Exploratory testing to confirm the actual behaviours of the tests I've added
> test: Add some tests for dependency suggestions

- src/ui/DateEditor.svelte
- src/ui/Dependency.svelte
- src/ui/EditTask.scss
- src/ui/EditTask.svelte
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
- Introduce specific CSS classes where needed
- Rename CSS classes
- Remove unneeded references to CSS classes
- Merge classes with same parents
We are now ready to extract components - we have enough separation between the classes
Make extraction of components from `EditTask.svelte` & `EditTask.scss` easy.
Manual tests in demo vault.
- CSS code is not tested
> refactor: finalise CSS split in `EditTask.scss

- src/Scripting/Postponer.ts
- src/lib/StringHelpers.ts
- src/ui/DateEditor.svelte
- src/ui/Dependency.svelte
- src/ui/EditTask.scss
- src/ui/EditTask.svelte
- src/ui/EditTaskHelpers.ts
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
- tests/ui/EditTaskHelpers.test.ts
Sorry for a big PR =) I can split it into several ones if needed.
- remove CSS class `accesskey-first` and unify access key declaration with `accesskey` class
- remove HTML elements declaring access keys from the modal without access keys
- Somehow they were still in the `<label>` elements O_o
- They were not present in `<input>` elements which inhibited the access keys
- extract `editTaskLabelContent()` function to generate the label content
- use it everywhere except priority (there the content is different and linked with CSS styles, so no gain for now) 
- for dependencies and dates, move `<label>` to `<Dependency>` and `<DateEditor>` component respectively
- Move HTML code generation inside the components (for `<Dependency>` and `<DateEditor>`)
- Prepare to extract Svelte components …
> refactor: extract label generation for Edit Task modal

- src/Suggestor/Suggestor.ts
- src/TaskSerializer/DataviewTaskSerializer.ts
- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/Suggestor/Suggestor.test.ts
I'm using the new auto-suggest for ID and dependsOn in my own vault, and it's incredibly valuable.
Before release, I wanted to add tests to make sure I understand the code.
Along the way, I improved a couple of behaviours:
- 99129ea218f5b4771259aa5e3b66663fa18cf6ee - allow additional dependencies after ids with hyphen and underscore
- bcee94a9e5eaa32a3dd2068de56824bb2878c3d2 - correct the search for blocking tasks to use exact id match, not substring
Getting this facility ready for release
- Manual exploratory testing
> fix: Test and improve behaviour of auto-suggest with dependencies

- docs/Editing/Auto-Suggest.md
- docs/Getting Started/Task Dependencies.md
- docs/Support and Help/Known Limitations.md
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.ts
This temporarily disables the auto-suggestion of `id` and `dependsOn` fields that was added in #2771.
I'm keen to release the new features for the Kanban plugin, and auto-suggestion of `id` and `dependsOn` needs a bit more time to get it ready for release, so I am temporarily disabling it...
I had first thought that I might just release it as-is, with notes in the docs about limitations,  but it [sometimes break existing IDs for users with Obsidian Sync](https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2823) was sadly a show-stopper for me.
I've been testing that code in my own fork on my main vault, and the facility is going to be really, really useful.
When adding tests for it, I found and fixed a couple of small issues - see:
- …
> fix: Disable auto-suggest for dependencies to allow 7.2.0 release

- src/ui/EditTask.scss
- src/ui/EditTask.svelte
- src/ui/StatusEditor.svelte
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
- extract `StatusEditor` component from Edit Task modal
- have reusable components
- simplify cluttered Edit Task modal code
- unit tests
- manual test in demo vault (open the task modal, change status, apply it, verify the change in the task line)
> refactor: extract `StatusEditor` component from Edit Task modal

- src/ui/EditTask.svelte
- remove `_onPriorityKeyup()` (Dead code)
- remove dead code
- manual test in demo vault - try setting priority with mouse and access keys
> refactor: remove _onPriorityKeyup()

- src/ui/Dependency.scss
The change is seen only on the dark theme.
Before
After (Note the background under the "x" is gone)
On the clear theme the is no change in color, only the shape slightly changed. After:
- have a prettier task modal =)
- manual test in demo valuet
(I don't consider this a big enough change to update the modal screenshot)
> fix: remove background under the dependency delete button

- package.json
- resources/sample_vaults/Tasks-Demo/Test Data/one_task.md
- src/Obsidian/Cache.ts
- tests/Obsidian/Cache.test.ts
- tests/Obsidian/__test_data__/one_task.ts
- add way to test `Cache.getTasksFromFileContent()`
- add framework to extract data from Obsidian in oder to create test data
- prepare for parent-child relationship tests
- new unit tests
> test: test `Cache.getTasksFromFileContent()`

- .github/workflows/update-docs-markdown.yml
- change the OS in the `update-docs-markdown.yml` from win to ubuntu
I tried exploring the root cause of the failure but had no success. However I just trying changing the OS and the action was running well =)
I run the workflow on a branch where the workflow was successfully run before and see it fail now (Just go to your fork and try running the action in question on any branch where a run was successful, for example something done in April this year)
Previously (May 15) good result from workflow 
https://github.com/ilandikov/obsidian-tasks/actions/runs/9094786277/attempts/1
Today's bad result from the workflow on the same state
https://github.com/ilandikov/obsidian-tasks/actions/runs/9094786277/attempts/2
Today's good result of the workflow in my fork on this branch …
> chore: run `update-docs-markdown.yml` on ubuntu

- src/ui/EditTask.scss
- align the view of date editors, dependency editors and the status editor
Better looking Edit Task modal =)
Smoke test in demo vault
| Before | After |
|-------|-----|
|  <img width="613" alt="Снимок экрана 2024-05-30 в 14 02 58" src="https://github.com/obsidian-tasks-group/obsidian-tasks/assets/93825870/c998fd0e-6ef1-41b6-a9c7-ec7a01243aab">| <img width="614" alt="Снимок экрана 2024-05-30 в 14 03 55" src="https://github.com/obsidian-tasks-group/obsidian-tasks/assets/93825870/d6721c35-73e0-4eb1-966a-c34cd2b732b7"> |
- CSS code not covered
> fix: Correctly align 'Before ...' & 'After ...' in Edit Task modal

- src/ui/EditableTask.ts
- tests/ui/EditTaskHelpers.test.ts
- Make `EditableTask.constructor()` private
- Rewrite tests using `EditableTask.fromTask()` factory
(There is also possibility is to make the constructor accept the `(task: Task, allTasks: Task[])` parameters, in other words, make the factory be the constructor. But I don't know if there is a value in that so I propose to leave that story here for now =))
Creation of `EditableTask` is done in the code from a `Task` object, so a constructor with every field being open shall not be exposed, which is the case in the tests, what makes them farer from the real use-case.
This is actually simpler for tests since the `TaskBuilder` is leveraged.
- unit tests
> refactor:  make `EditableTask` constructor private

- src/ui/EditTask.svelte
- src/ui/EditableTask.ts
- tests/ui/EditTaskHelpers.test.ts
- tests/ui/EditableTask.test.ts
- remove `addGlobalFilterOnSave` and `originalBlocking` from `EditableTask` methods' input and output
- move them to `private readonly` fields of `EditableTask` class
- encapsulate behaviour that does not need to be exposed
- Unit tests
> refactor: Improve encapsulation of behaviour in `EditableTask` class

- src/ui/EditTaskHelpers.ts
- src/ui/EditableTask.ts
- src/ui/RecurrenceEditor.svelte
- tests/ui/EditTaskHelpers.test.ts
- tests/ui/EditableTask.test.ts
- move `parseAndValidateRecurrence()` free function to `EditableTask` class method
- improve this method tests (create `EditableTask` instance at every test, see last commit)
This is the last PR in `EditableTask`-related refactorings, I think this is better than 'good enough` so we can live with this for a while =)
- group behaviour in the class
- unit tests
> refactor: move `parseAndValidateRecurrence()` to `EditableTask`

- src/Obsidian/Cache.ts
- src/Task/ListItem.ts
- src/Task/Task.ts
- tests/Task/ListItem.test.ts
- Remove `children` parameter from `ListItem.constructor`
- Assign `children` inside the constructor
- Add tests and jsdocs showing the creation of `Task` & `ListItem` parent-child hierarchies
- Improve usage of parent-child relationship code
- unit tests
> refactor: encapsulate adding children in `ListItem` constructor

- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_listitem_task.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_listitem_task_siblings.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_task_2listitem_3task.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_task_listitem.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_task_listitem_mixed_grandchildren.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_task_listitem_task.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_task_mixed_children.md
- src/Obsidian/Cache.ts
- tests/Obsidian/Cache.test.ts
- tests/Obsidian/__test_data__/inheritance_listitem_task.ts
- tests/Obsidian/__test_data__/inheritance_listitem_task_siblings.ts
- tests/Obsidian/__test_data__/inheritance_task_2listitem_3task.ts
- tests/Obsidian/__test_data__/inheritance_task_listitem.ts
- tests/Obsidian/__test_data__/inheritance_task_listitem_mixed_grandchildren.ts
- tests/Obsidian/__test_data__/inheritance_task_listitem_task.ts
- tests/Obsidian/__test_data__/inheritance_task_mixed_children.ts
- store list item objects when reading .md files
Store list items and tasks hierarchy
Unit tests
> refactor: Store `ListItems`

- docs/Editing/Auto-Suggest.md
- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
- tests/Suggestor/Suggestor.test.ts
- Issue/discussion: Agreed by @claremacrae in https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2885#issuecomment-2156029598
The Default Value of the Settings Option "Maximum Number of auto-suggestion to show" was increased.
Increased the default value for better visibility. (At least for the Default Task Attributes)
This adjustment will provide new users with a comprehensive overview, thereby preventing confusion on what options exists in the Future.
Additionally, the settings upper limit was increased to 20, as the Max Number of Normal Task Property Suggestions is 13, which didn't …
> feat: Increase Default Max Auto Suggestion Number to 20

- src/Task/Recurrence.ts
- tests/Task/Task.test.ts
- Issue/discussion: #2867
Prevent unintended mutation of 'today' that broke the saved done date.
The underlying cause of this us that `today.startOf('day')` was being called in `nextReferenceDateFromToday()` - which was adjust the reference date passed in, in the case that the next recurrence was a non-existent date and so needed to be adjusted.
Fixes #2867
- Adding some tests - and then later removing them, when I discovered that the problem could be found with existing test cases
- Repeating the 'steps to reproduce' in #2867, to confirm it really is fixed.
> fix: recurrence with 'when done' could give wrong 'done' date

- tests/Api/executeToggleTaskDoneCommand.test.ts
- tests/Commands/ToggleDone.test.ts
- tests/Task/Urgency.test.ts
- Increase test robustness by resetting dates even after failing tests
- unit tests
> test: ensure dates reset

- docs/Queries/Grouping.md
The explanation for `group by function task.due.fromNow.groupText` in Queries/Grouping says:
"It **users** an empty string (so no heading) if there is no due date"
which seems to be a typo
Fixed a minor typo.
> docs: fixed a minor typo

- src/Renderer/QueryRenderer.ts
Fixes #2941
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2941
Add missing call to `QueryRenderChild.load()` - see [Component.load()](https://docs.obsidian.md/Reference/TypeScript+API/Component/load) in the Obsidian developer docs.
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2941
- In the test vault supplied in https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2941
- By running all the Tasks smoke tests and confirming they pass
> fix: Tasks search results now render correctly in Tabs plugin

- resources/sample_vaults/Tasks-Demo/How To/Find tasks in notes with particular tag.md
- src/Scripting/TasksFile.ts
- tests/Scripting/TasksFile.test.ts
- tests/__mocks__/obsidian.ts
- A small fix to an unreleased feature
- See https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2480
In `src/`:
- fix: Prevent `task.frontmatter.tags` being null if no tags in frontmatter
- Remove `TasksFile.frontmatterTags`
- Improve JSDocs of `TasksFile.ts`
In `tests/`:
- Add safety checks to the mock functions `getAllTags()` and `parseFrontMatterTags()`
- Add more tests, just exploring the behaviour
In sample vault:
- Update sample code that demoed use of now-deleted `task.file.frontmatterTags`
More progress on https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2480
- Exploratory testing in demo vault
> fix: Prevent task.frontmatter.tags being null if no tags in frontmatter

- LICENSE
- esbuild.config.mjs
- manifest.json
- package.json
Ilyas (@ilandikov) has been contributing a lot to Tasks for well over a year now.
This adds him as the second author, by agreement with @schemar, the original author.
It updates the Copyright names too.
See also:
- https://github.com/obsidianmd/obsidian-releases/pull/3914.
See above.
Untested.
> chore: Add Ilyas Landikov as co-author of Tasks

- resources/sample_vaults/Tasks-Demo/How To/Access properties in frontmatter.md
- resources/sample_vaults/Tasks-Demo/How To/Find tasks in notes with particular tag.md
- resources/sample_vaults/Tasks-Demo/_meta/templater_scripts/convert_test_data_markdown_to_js.js
- src/Scripting/TasksFile.ts
- tests/Obsidian/AllCacheSampleData.ts
- tests/Obsidian/Cache.test.ts
- tests/Scripting/TasksFile.test.ts
- tests/TestingTools/MockDataHelpers.ts
- tests/ui/EditableTask.test.ts
Fix:
- `TasksFile` now ensures that `task.frontmatter.tags` always exists, so 'no frontmatter' behaves the same as 'has frontmatter but no tags'
Tests:
- Make it easy to write tests of the behaviour with all the sample CachedMetadata saved data:
- Add new file `tests/Obsidian/AllCacheSampleData.ts`, which exports a function `allCacheSampleData()`
- Then make `resources/sample_vaults/Tasks-Demo/_meta/templater_scripts/convert_test_data_markdown_to_js.js` to also update the above file when new sample files are added
- Add systematic tests to `tests/Obsidian/Cache.test.ts`, showing the invariants of the code reading CachedMetadata, including the frontmatter
- This will be useful when writing documentation
- I am not super happy with the test names …
> fix: Prevent task.frontmatter.tags being null if no frontmatter

- contributing/Testing/About Testing.md
- contributing/Testing/Using Obsidian API in tests.md
- tests/Obsidian/Cache.test.ts
Done by pairing with @claremacrae
> contrib: add documentation on testing code that uses Obsidian API

- src/Task/Recurrence.ts
- extract `nextOccurrence()` method and reuse it
- contrary to what you mentioned in the previous PR, I had to extract a wider method since there will be a check whether `this.scheduledDate`/`this.dueDate`/`this.startDate` is `null` and the `if {}` will be in the caller and in the body of the method
- better code
- unit tests
> refactor: extract `nextOccurrence()` method and reuse it

- resources/sample_vaults/Tasks-Demo/.obsidian/types.json
- resources/sample_vaults/Tasks-Demo/Test Data/yaml_all_property_types_empty.md
- resources/sample_vaults/Tasks-Demo/Test Data/yaml_all_property_types_populated.md
- tests/Obsidian/Cache.test.ts
- tests/Obsidian/SimulatedFile.ts
- tests/Obsidian/__test_data__/yaml_all_property_types_empty.ts
- tests/Obsidian/__test_data__/yaml_all_property_types_populated.ts
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.obsidian_properties_task.file.frontmatter_docs.approved.md
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.obsidian_properties_task.file.frontmatter_results.approved.txt
- tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.obsidian_properties_task.file.frontmatter_docs.approved.md
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.obsidian_properties_task.file.frontmatter_results.approved.txt
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
- tests/Scripting/TasksFile.test.TasksFile_-_reading_frontmatter_should_read_yaml_all_property_types_empty.approved.json
- tests/Scripting/TasksFile.test.TasksFile_-_reading_frontmatter_should_read_yaml_all_property_types_populated.approved.json
- tests/Scripting/TasksFile.test.ts
- add test showing current behaviour of access to `task.file.frontmatter`
- prepare release with FrontMatter access
- approval test
> test: demo property custom searches

- src/Task/Recurrence.ts
- move `referenceDate` field from `Recurrence` to `Occurrence` class
- separate concerns (Reference date is related to `Occurrence`)
- unit tests
> refactor: move `referenceDate` field to `Occurrence` class

- src/Task/Recurrence.ts
- tests/Task/Recurrence.test.ts
- Move `Occurrence`-related behaviour to `Occurrence` class
- Separate concerns
- unit tests
> refactor: create `nextOccurrence` and `nextOccurrenceDate` methods in `Occurrence`

- resources/sample_vaults/Tasks-Demo/Test Data/yaml_capitalised_property_name.md
- src/Scripting/TasksFile.ts
- tests/Obsidian/AllCacheSampleData.ts
- tests/Obsidian/__test_data__/yaml_capitalised_property_name.ts
- tests/Scripting/TasksFile.test.ts
- Issue/discussion: #2480 
- done by pairing with @claremacrae 
- add `task.file.hasProperty()` and `task.file.property()`
- RELEASE =)
- save users from having to understand when to use `null` or `undefined` with properties
- save @claremacrae from having to document when to use `null` or `undefined` with properties
- new unit tests
- exploratory testing in live vault
- todo for @claremacrae  =)
> feat: releasable code for accessing properties via `task.file`

- src/Scripting/TasksFile.ts
- src/Task/Task.ts
- tests/Scripting/TasksFile.test.ts
- tests/Task/Task.test.ts
- tests/TestingTools/TaskBuilder.test.ts
- tests/TestingTools/TaskBuilder.ts
`Task` objects are now updated if the frontmatter in the file containing them is edited.
This fixes an unreleased bug, that editing properties/frontmatter did not update Tasks query results. This matters now that  properties/frontmatter can be used in Tasks queries.
The steps to reproduce the bug are:
1. Install development version of Tasks plugin
2. Create a note called `test`
3. Paste in this content:
````
---
custom_number_prop: 42
---
```tasks
path includes {{query.file.path}}
group by function task.file.property('custom_number_prop')
```
````
4. Preview the results. It should show this:
5. Use the 'File properties' panel to edit the property value from 42 to 43
**Expected result**
Group heading changes to 43:
**Actual result**
Display is …
> fix: Editing properties/frontmatter now updates Query results

- src/Obsidian/Cache.ts
- src/Task/DateFallback.ts
- tests/Task/DateFallback.test.ts
Fix an unreported bug (in unreleased code)...
The actual fix is c09a8846f562cbf3131f2390763b33c2febd9412 - the rest is refactoring, initially to make the fix easy, and then to tidy it up a bit, with suggestions from @ilandikov.
Steps to reproduce:
1. Install the latest development build, for example from commit b42ead68505f99e6543c1f27d6e4e63d9d1a2d69
2. Create a new note called `test 2024-01-23`
3. Paste in this content:
~~~
---
custom_number_prop: 422
---
~~~
4. Create a note called `test query`
5. Paste in this content:
~~~
```tasks
description includes Hellox
group by path
group by function \
`custom_number_prop: ==${task.file.property('custom_number_prop')}==`
group by scheduled
```
~~~
6. View `test query` in Reading Mode. It should look …
> fix: Tasks in renamed files forgot about any properties/frontmatter values in the file

- src/Task/OnCompletion.ts
- src/TaskSerializer/DefaultTaskSerializer.ts
- src/ui/EditableTask.ts
- tests/Task/OnCompletion.test.ts
- tests/Task/Task.test.ts
- tests/TaskSerializer/DataviewTaskSerializer.test.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
- tests/TestingTools/SampleTasks.ts
- tests/TestingTools/TaskBuilder.ts
- tests/ui/EditTask.test.ts
- Refactor the On Completion code to make wider use of the `OnCompletion` enum.
- Move the code for parsing On Completion values from `DefaultTaskSerializer.ts` to `OnCompletion.ts` so that all edits for new or changed options are in the same file.
- Add new test to ensure that the EditTask modal retains any `OnCompletion` value (it cannot yet edit the value)
Getting ready to release the work done in:
- #2840
> refactor: Small improvements to the 'On Completion' implementation

- src/Obsidian/InlineRenderer.ts
- src/Task/OnCompletion.ts
- Issue/discussion: #1395
Numbered sub-tasks (and plain list items) are now rendered in reading mode.
Fixes #1395
- Exploratory testing (there are no unit tests).
~~~
- Item a 📅 2024-03-08
- Item b 📅 2024-03-08
1. Item a 📅 2024-03-08
1. Item b 📅 2024-03-08
1. [ ] #task Item c 📅 2024-03-08
1. [ ] #task Item d 📅 2024-03-08
1. [ ] #task Item c 📅 2024-03-08
1. [ ] #task Item d 📅 2024-03-08
~~~
1. All screenshots are in Default theme.
2. The only enabled snippet draws a blue border around Tasks code blocks.
3. The odd overlapping of checkbox and list item number happens in Restricted mode (all plugins off) so is not a Tasks issue.
- I checked, and could not find any mention of this bug in the documentation.
> fix: Render numbered sub-tasks and list items in Reading view

- docs/Getting Started/On Completion.md
- docs/Reference/Task Formats/Dataview Format.md
- docs/Reference/Task Formats/Tasks Emoji Format.md
- src/Task/OnCompletion.ts
- tests/Task/OnCompletion.test.ts
- tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_dataview-include.approved.md
- tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_dataview-snippet.approved.md
- tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_tasksPluginEmoji-include.approved.md
- tests/TaskSerializer/DocsSamplesForTaskFormats.test.Serializer_OnCompletion_tasksPluginEmoji-snippet.approved.md
- tests/TestingTools/SampleTasks.ts
- Issue/discussion: #1647
Previous references to 'ignore' in the On Completion docs were confusion - see the warning I have now deleted.
This now adds an explicit 'keep' option, which behaves the same as no 'On Completion' option having been provided.
It basically enables the documentation to be honest and accurate now.
- New unit tests
- Exploratory testing in the test vault
> feat: Add 'keep' option to 'On Completion'

- src/Renderer/QueryRenderer.ts
- src/Renderer/QueryResultsRenderer.ts
- add `QueryResultsRenderer` class
- move some methods from `QueryRenderer`
- prepare to test rendering of sub-tasks
- manual exploratory testing
> refactor: add `QueryResultsRenderer` class

- docs/Editing/Auto-Suggest.md
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.ts
Fix some unreported inconsistencies in AutoSuggest behaviour, discovered whilst adding support for auto-suggest on a new field.
- fix: Better dataview space & cursor in recurrence suggestions
- fix: Remove the need to type a space after 'id' and 'depends on' selected
- fix: Better dataview space & cursor in 'generate unique id' result
See the "Screenshots" section below for demos of each change.
I want to extract some helper functions in `Suggestor.ts` as it is so repetitive - in doing so, I found some inconsistencies in the code, which explain some inconsistencies in the behaviour.
In the following text, the `|` represents the cursor position after the change.
```
```
```
```
```
```
```
```
> fix: Various improvements to cursor positions in Auto-Suggest

- src/Suggestor/Suggestor.ts
Introduce `SuggestorParameters` parameter object to many functions in `Suggestor.ts`.
As a next step, I want to refactor `Suggestor.ts` to reduce some repetition.
- Existing automated tests
> refactor: introduce parameter object to functions in Suggestor.ts

- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_correct_options_for_partial_due_date_lines.approved.txt
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_correct_options_for_partial_due_date_lines.approved.txt
Like <https://github.com/obsidian-tasks-group/obsidian-tasks/pull/3020> but for date suggestions where the user typed their own date value, such as '21 oct' or '1 year'.
More improvements to the Auto Suggest code before adding support for On Completion.
In the following text, the `|` represents the cursor position after the change.
Before:
```
```
After
```
```
> fix: Better dataview space & cursor in date suggestions

- src/Renderer/QueryRenderer.ts
- src/Renderer/QueryResultsRenderer.ts
- `QueryRenderChild` now inherits `MarkdownRendererChild`
- `QueryResultsRenderer` has now no inheritance
- prepare `QueryResultsRenderer` for testing
- Smoke test in demo vault (make a minimal tasks query and verify it is rendered)
> refactor: remove `QueryResultsRenderer` inheritance

- docs/Editing/Auto-Suggest.md
- docs/Getting Started/On Completion.md
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
- tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json
- tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
- tests/Suggestor/Suggestor.test.ts
- Issue/discussion: #2840
- Teach Auto Suggest to support the 'On Completion' feature.
- Update docs accordingly
Getting ready to release #2840
> feat: Teach Auto Suggest to support  "On Completion"

- esbuild.config.mjs
- package.json
- src/DateTime/DateFieldTypes.ts
- src/DateTime/Postponer.ts
- src/Renderer/Renderer.scss
- src/Renderer/TaskLineRenderer.ts
- src/styles.scss
- src/ui/EditInstructions/DateInstructions.ts
- src/ui/Menus/DatePicker.ts
- src/ui/Menus/PostponeMenu.ts
- tests/DateTime/Postponer.test.ts
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
- tests/ui/EditInstructions/DateInstructions.test.ts
- yarn.lock
- Issue/discussion: #2649
**User visible changes:**
- In Reading Mode and in Tasks Query Results, now you can click on a task date field, and a date editor will pop up.
- It will show the current date.
- Selecting any other date will apply that date to the task immediately (there is no save button).
- Clicking outside the date picker will close it.
**Behind the scenes:**
- flatpickr: <https://github.com/flatpickr/flatpickr>
- Add dependency on this library. It's also used by the Kanban plugin, I see.
- Add its licence to the distributed `main.js`.
- Main new source files:
- `src/ui/EditInstructions/DateInstructions.ts` with tests
- This implements `TaskEditingInstruction`.
- `src/ui/Menus/DatePicker.ts`
- Wrapper around `flatpickr`
- Do we want …
> feat: Add date picker in Reading mode and Tasks Query results

- src/Renderer/QueryRenderer.ts
- src/Renderer/QueryResultsRenderer.ts
- src/Renderer/TaskLineRenderer.ts
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_fully_populated_task.approved.html
- tests/Renderer/QueryResultsRenderer.test.ts
Refactor `QueryResultsRenderer` to enable us to save the generated HTML with approval tests.
This replicates edits made previously to allow `TaskLineRenderer` to be tested:
- Replace use of Obsidian convenience methods (such as `createDiv()`) with the native equivalents, so that the code can be called via tests
- Allow `obsidianComponent` to be `null`.
- To be able to write tests of rendering nested task lines and list items.
- With a new test
- Running the existing smoke tests (done by @claremacrae)
> refactor:  test QueryResultsRenderer

- src/ui/DateEditor.svelte
- src/ui/EditTask.scss
- src/ui/Menus/DatePicker.ts
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
- Improves the appearance of an unreleased feature
In testing the date picker in the Edit Task modal on my phone, I realised I hadn't implemented adjusting of the layout for smaller screen sizes, so this fixes that.
It also makes the icon a slightly more muted colour, and tidies up the code a little.
Exploratory testing, with videos made for comparison.
Only on desktop so far.
https://github.com/user-attachments/assets/d6bb38bc-46f2-4ac9-9a69-8e4520a56eb4
> fix: Improve Edit Task modal calendar 'button' layout

- .github/workflows/verify.yml
- resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
- Add smoke tests for date picker and date context menu
- Fix the sample vaults created by GitHub Actions - problem caused by:
- https://github.com/actions/upload-artifact/issues/602
I needed to test the new date picker and context menu on iPhone and iPad.
In doing so, I found that the test vault artefact no longer included the `.obsidian/` folder!
See `Tasks-Demo-VerifyCommit-Build4986-Run1.zip` in [this build](https://github.com/obsidian-tasks-group/obsidian-tasks/actions/runs/10708099778). 
Running the new smoke tests on iPad and iPhone.
> vault: Add smoke tests for date picker and date context menu

- src/Obsidian/Cache.ts
- src/main.ts
- Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2152
Load Vault and subscribe to changes when workspace is ready. 
After turning on logging and debugging the plugins startup, especially the Cache creation i noticed the following effects:
- Files are checked twice: Once by loadVault and once by subscribeToVault.
- Whereas loadVault is fast, subscribeToVault added significantly delays
- subscribeToVault (https://docs.obsidian.md/Reference/TypeScript+API/Vault/on('create')) registers for create events where for every file available the event is triggered when called in the plugins onload routine
- https://docs.obsidian.md/Reference/TypeScript+API/Vault/on('create') added significant delays in the Tasks plugin even if the event handler is an …
> fix: load cache when workspace is ready

- resources/sample_vaults/Tasks-Demo/Functions/Custom Filters - Demo.md
- src/Query/Query.ts
- tests/Query/Query.test.ts
When an exception is thrown whilst filtering tasks, include the problem statement in the error text.
I've noticed a growing number of users using `filter by function`, often for simple cases that can be done using built-in instructions.
Try to make it easier for users to figure out which instruction is causing the problem - and to aid in user support too.
Make it easier to work out which instruction caused "Search failed" messages in queries that have more than one filter.
This is especially relevant when there are multiple `filter by function` statements in a Query.
- Updating existing test
- Adding new content to the test vault, to see the changed behaviour
> fix: Make 'filter by function' show statement in error messages

- src/ui/Menus/PostponeMenu.ts
- tests/ui/Menus/PostponeMenu.test.ts
- Discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/2452#discussioncomment-10595027
- the postpone menu has first 2 items with fixed dates - today and tomorrow. In case they match the already set date that will be postponed, add a check sign on that menu item.
- better postpone menu
- unit test with postpone menu output
> feat: check postpone item if its date matches the one in the task

- src/ui/Menus/PostponeMenu.ts
- do nothing when the task date to postpone and the postponed date match (this is a case when a date field is postponed to a date that is already set in the postpone menu)
- Fixes #2816 
- manual test in demo vault:
- set scheduled date to today
- right click on postpone menu, today's date is checked
- click on today's date
- verify that right click on postpone still works
- verify that left click on postpone still works
- repeat the test with tomorrow date
- nope, manual test
> fix: postpone to current date keeps postpone button active

- src/ui/StatusEditor.svelte
- tests/ui/EditTask.test.ts
- Done/Cancelled date have to be kept if they are already present in the respective date editor while the status is set to Done/Cancelled respectively. 
_Don't overwrite a user-entered Done date if changing status to DONE_
_Don't overwrite a user-entered Cancelled date if changing status to CANCELLED_
- Fixes #3085 
- new unit tests added
> fix: retain manually added Done & Cancelled dates in modal

- src/ui/EditableTask.ts
- tests/ui/EditTask.test.ts
When changing status type to CANCELLED, use the Cancelled Date as `today` instead of the `Done Date`.
Fixes #3089
- #3089
- running existing tests
- this actually fixed two of the existing tests, not just the one that linked to the issue being fixed here
- manual exploratory testing
> fix: Edit Task modal now retains edits to Cancelled date

- src/Config/StatusSettings.ts
- src/Statuses/Status.ts
- src/Statuses/StatusRegistry.ts
- tests/DocumentationSamples/DocsSamplesForStatuses.test.ts
- tests/Query/Filter/BlockingField.test.ts
- tests/Query/Filter/FunctionField.test.ts
- tests/Query/Filter/StatusField.test.ts
- tests/Query/Filter/StatusTypeField.test.ts
- tests/Scripting/TaskProperties.test.ts
- tests/Statuses/Status.test.ts
- tests/Statuses/StatusRegistry.test.ts
- tests/Task/OnCompletion.test.ts
- tests/Task/Task.test.ts
- tests/TestingTools/SampleTasks.ts
- tests/TestingTools/TaskBuilder.ts
- tests/ui/EditInstructions/StatusInstructions.test.ts
- tests/ui/Menus/StatusMenu.test.ts
- `Status.make*()` are same as the existing `Status.*` calls (`*` is any status), so
- Replace `Status.make*()` status methods with existing `Status.*` static class fields
- For other statuses, refactor `Status.make*()` method calls to `Status.*` static class fields
For reference: existing `Status.*` static class fields were calling `Status.make*()` methods, so the behaviour was same.
_Note from @claremacrae: the behaviour differed in how many `Status` instances were created, however._
- remove code duplication and use shorter calls to `Status` static methods
- better code
- unit tests
> refactor: Replace Status factory functions with static objects

- docs/Getting Started/Statuses/Status Types.md
- src/Query/Filter/StatusField.ts
- tests/DocumentationSamples/DocsSamplesForStatuses.test.Status_Transitions_status-types.approved.md
- tests/Query/Filter/StatusField.test.ts
- Issue/discussion: #3030
- Make `group by status` and `sort by status` use StatusType, instead of just caring whether the status symbol was a space or not.
- This means that the `group by status` behaviour now matches that stated in the documentation.
- `sort by status` docs was never very specific, but the behaviour is an improvement, and still fits with the docs.
- Fix #3030 
- Manual testing in demo vault
- Just the updating of a snippet
> fix: Improve usefulness of 'group by status' and 'sort by status'

- src/Config/SettingsTab.ts
There has been an un-reported bug for a long time, that the open/closed state of the collapse buttons on the Core Status and Custom Status sections of the Tasks Settings were not restored when the settings were re-opened, either in the same session, or when restarting Obsidian.
This fixes that bug. The collapse state is now correctly preserved.
To hide away the details of Status settings once they are correctly set up.
Lots of exploratory testing, including deleting the settings file and ensuring that the Status sections are sill expanded by  default.
See above.
> fix: Restore 'collapsed' state of Status setting sections

- src/Renderer/QueryResultsRenderer.ts
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_parent-child_items.approved.html
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_parent-child_items_reverse_sorted.approved.html
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_should_render_tasks_without_their_parents.approved.html
- tests/Renderer/QueryResultsRenderer.test.ts
- Issue/discussion: #60 
- task query results now render all child list items and tasks of the tasks that match the search
- this is an experimental feature that needs more testing to ensure that it really does show every matching task
- #60 
- new unit tests
- exploratory testing
> feat: add experimental rendering of child tasks and list items

- resources/sample_vaults/Tasks-Demo/Manual Testing/Callouts and Block Quotes.md
- src/Renderer/QueryResultsRenderer.ts
- src/Task/ListItem.ts
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_parent-child_items.approved.html
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_parent-child_items_reverse_sorted.approved.html
- tests/Task/ListItem.test.ts
- render the proper description of list items without the list bullet, number, etc.
- #60 
- unit tests
- exploratory testing
> fix: sub-list items now render OK - no bullet, number, callout/blockquote etc

- src/Obsidian/Cache.ts
- src/Task/ListItem.ts
- src/Task/Task.ts
- tests/Task/ListItem.test.ts
- tests/Task/ListItemHelpers.ts
- tests/Task/Task.test.ts
- make cache update when there are differences in child list items
- make Task check child list items
- #60 
- unit tests
- manual test in local vault
> fix: rerender search results when child list items are edited

- resources/sample_vaults/Tasks-Demo/Other Plugins/Dataview/Parent-Child relationships - Searches - Tasks.md
- src/Layout/QueryLayoutOptions.ts
- src/Query/Query.ts
- src/Renderer/QueryResultsRenderer.ts
- tests/Query/Query.test.ts
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_parent-child_items_hidden.approved.html
- tests/Renderer/QueryResultsRenderer.test.ts
- Issue/discussion: #60
_**Warning: These instructions may be removed or renamed, and are not (yet) intended for end-user use.**_
Add two new **experimental** - and undocumented instructions:
```
show tree
hide tree
```
`show tree ` causes Tasks to render nested tasks and list items, and is off by default.
I am not sure whether `hide tree` is really the right vocabulary for this long-term, but it is definitely better than `hide children` which was the first thing I tried.
More work on:
- #60
This will allow me to continue making Tasks releases whilst we improve the rendering of nested lines.
- Exploratory tests
> feat: Add experimental 'show/hide tree' instruction - disabled by default

- src/Task/Recurrence.ts
`moment().local(true)` incorrectly handles the early hours of the day on which DST is entered into. This PR is a workaround for that bug by doing the conversion at noon instead of midnight. Additionally it also replaces the incorrect use of `window.moment` with `window.moment.utc` when the intending to work with UTC time.
Fixes #2309
Tested the individual functions used with example inputs in a node interpreter.
> fix: recur correctly at start of Daylight Savings Time

- src/Obsidian/LivePreviewExtension.ts
- Issue/discussion: #3043
This fixes #3043 by removing some code which appears no longer to be necessary, and which caused '🏁 delete' in Live Preview to render the new task as DONE, even though in the markdown it was correctly TODO.
This is a revert of the behaviour added in 73d910490e1882dfb2d22ea0f53bfec42b357c96
- #3043
In the test vault:
- By running through the smoke tests in Live Preview to make sure they still work
- By running through the reproduction I added in https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3043#issuecomment-2393969888
> fix: 'on completion' delete now renders correctly in Live Preview

- resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
- src/Obsidian/LivePreviewExtension.ts
- Issue/discussion: #3148
My fix for #3043 - in #3145 - inadvertently broke the more common case of toggling non-recurring tasks in Live Preview mode.
This change:
- Reverts #3145
- And then refines the logic in the original code for the addition of 'on completion: delete', to fix the check-box state after direct toggling of non-recurring tasks in Live Preview
- Adds some smoke tests to ensure that the behaviour in Live Preview is tested and remains working.
Fixes #3148.
- New smoke tests
- Tested with values of the  'Recurring tasks' order setting
- Tested with a 3-state status set - TODO -> IN_PROGRESS -> DONE
- Exploratory testing in the test vault
> fix: Correct the direct toggling of non-recurring tasks in Live Preview

- src/Obsidian/Cache.ts
This essentially moves the code from PR #1524 to an outer scope, so that it is also applied in the new parsing code for creating ListItem objects.
- See https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3156
I discovered previously that, at startup, Obsidian's cached data could sometimes refer to no-longer-existent lines, which previously resulted in Tasks trying to create a task object from invalid data.
The same issue has occurred with creating `ListItem` objects - reported by 3 users here in GitHub, and 2 in Discord (which may or may not be the same people).
I've logged reproduction steps in https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3156#issuecomment-2444696600
This fix essentially moves the code from PR #1524 to an outer scope, …
> fix: ! Prevent Tasks getting stuck 'Loading Tasks...' (again)

- src/ui/DateEditor.svelte
- tests/ui/DateEditor.test.ts
- tests/ui/DateEditorWrapper.svelte
- tests/ui/EditTask.test.ts
- tests/ui/RenderingTestHelpers.ts
- Make `DateEditor.parsedDate` available for testing
- Create `DateEditorWrapper` component to test the `DateEditor`
- Add tests showing current behaviour
- Prepare to TDD date picker's behaviour
- Unit tests
> refactor: test `DateEditor` svelte component

- src/Query/Scanner.ts
- tests/Query/Query.test.ts
- tests/Query/Scanner.test.ts
- Fixes #3137
This works around an issue found with Obsidian 1.7.4, that in Live Preview, Obsidian eats the final end-of-line character in code blocks.
In the Tasks plugin, the line continuation code depended on there being a final end-of-line character at the end of the query text in order to allow users to place dangling `\` markers on the last line in the query.
That problem was logged in #3137.
This change ensures that there is always a last end-of-line character at the end of every query, regardless of its location. This will be useful if/when Tasks allows users to run searches via its API - as requested in #2459.
Fixez #3137.
- With new tests
- And exploratory testing
I used this test file:
~~~
```tasks
limit 10
ignore global query
explain
( path includes …
```
> fix: '\' at end of last line in query no longer discards the instruction

- src/TaskSerializer/DataviewTaskSerializer.ts
- src/lib/PriorityTools.ts
- src/ui/EditableTask.ts
- tests/lib/PriorityTools.test.ts
This is a 2 months old PR I forgot to submit =) If you find these changes unnecessary, feel free to reject the PR.
- I noticed some repetitive code (string -> priority conversion) and an excessive types used around that (`EditableTaskPriority`) so I decided to refactor that
- Less repetition in code
- Unit tests added
> refactor: add `PriorityTools.priorityValue()`

- src/ui/DateEditor.svelte
- src/ui/EditTask.scss
- tests/ui/DateEditor.test.ts
- tests/ui/DateEditorWrapper.svelte
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html
- tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
- tests/ui/EditTask.test.ts
- tests/ui/RenderingTestHelpers.ts
- Issue/discussion:
- #2649
- #2190 
- add date picker for the dates in the Edit Task modal
- fix helper function testing that an element has been rendered (`getAndCheckRenderedElement()`)
- Quicker way to select dates in the Edit Task modal
- Unit tests
- Exploratory testing 
https://github.com/user-attachments/assets/94921f53-5e3f-49b9-aa94-9926402277b6
> feat: Add date-picker to the Edit Task modal

- resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
- src/Renderer/TaskLineRenderer.ts
- src/ui/Menus/DatePicker.ts
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_fully_populated_task.approved.html
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html
- tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html
- Issue/discussion: #2649
Add a **calendar date-picker** when user left-clicks on date values in **Reading Mode** and **Tasks search results**.
Fix #2649.
- Running the newly reinstated smoke tests for editing of dates
- I've been using virtually identical code in my own vault for months. This code differs in having new Clear and Today buttons, and working correctly on mobile.
Demo:
https://github.com/user-attachments/assets/0e386af5-8db5-40c7-87ff-466608855753
> feat: Add date-picker to Reading Mode and Tasks query results

- src/Obsidian/TaskModal.ts
- src/ui/EditTask.svelte
- tests/ui/EditTask.test.ts
Remove unused Flatpickr-related code from the Edit Task modal...
This code was all remnants of my unreleased earlier ChatGPT-driven attempt at adding a date-picker calendar widget to the Edit Task modal.
That code could have been disabled in #3067, and was finally totally redundant after #3169.
Clean up code.
- Manual exploratory testing in the demo vault.
- Diffing the new code with the versions prior to adding use of Flatpickr, to confirm I really have removed everything.
> refactor: Remove unused Flatpickr code from Edit Task modal

- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
Multiple spaces are now allowed between `🏁` and its value.
I found this whilst doing preparatory refactoring to fix #3179.
Also, adjust test to confirm that parsing of `on completion` field is case-insensitive.
Fix unreported bug that the Tasks Emoji format did not allow more than one space between the emoji and value.
- `🏁 delete` worked
- `🏁  delete` was not parsed, and was considered part of the task description 
- Added failing test to show the problem
- Did exploratory testing to confirm it's fixed
> fix: - Allow multiple spaces after onCompletion emoji

- src/TaskSerializer/DefaultTaskSerializer.ts
- tests/TaskSerializer/DefaultTaskSerializer.test.ts
- Issue/discussion: #3179
Tasks can now cope with any emojis being followed by VS16 Variation Selectors, not just priorities and depends-on.
Fix #3179
> fix: Handle any hidden VS16 character on all emojis

- resources/sample_vaults/Tasks-Demo/Test Data/link_in_task_html.md
- resources/sample_vaults/Tasks-Demo/Test Data/link_in_task_markdown_link.md
- resources/sample_vaults/Tasks-Demo/Test Data/link_in_task_wikilink.md
- resources/sample_vaults/Tasks-Demo/Test Data/links_everywhere.md
- tests/Obsidian/AllCacheSampleData.ts
- tests/Obsidian/Cache.test.ts
- tests/Obsidian/__test_data__/link_in_task_html.json
- tests/Obsidian/__test_data__/link_in_task_markdown_link.json
- tests/Obsidian/__test_data__/link_in_task_wikilink.json
- tests/Obsidian/__test_data__/links_everywhere.json
Prompted by a question on [Discord](https://discord.com/channels/686053708261228577/1257646566999588874/1309337875594084353), this saves some some exploratory tests that I wrote, to see how to access internal links in:
- frontmatter
- file bodies
- task lines
There are some comments saying how I might eventually release this to users.
The interesting file is `tests/Obsidian/Cache.test.ts`.
Related requests:
- <https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1461>
- <https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1812>
- <https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/173>
- <https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/728>
- <https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/725>
- …
> test: Add some example code to explore accessing links

- docs/Advanced/Styling.md
- docs/snippets-embedded-in-multiple-pages/Sample HTML - Full mode.md
- docs/snippets-embedded-in-multiple-pages/Sample HTML - Short mode.md
- package.json
Collapse two long HTML code samples in to callouts, so they do not swamp the `Styling` page.
Make the `Styling` page slightly less daunting.
Viewing in Obsidian/
After:
Before!
> docs: Collapse some long HTML samples in callouts

- src/Query/Explain/Explainer.ts
- src/Query/Group/Grouper.ts
- src/Query/Query.ts
- src/Query/Sort/Sorter.ts
- tests/Query/Explain/Explainer.test.ts
- tests/Query/Group/Grouper.test.ts
- tests/Query/Sort/Sorter.test.ts
- Issue/discussion: <https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2349>
The explanations of `sort by` and `group by` now reveal any **placeholders** and **continuation lines**, making it easier to understand the underlying query.
Note that there is one change in behaviour, revealed by a probable typo in an old test...
This:
```
sort by priority()
```
Used to be explained as:
```
sort by priority
```
And is now explained as:
```
sort by priority()
```
I was not immediately able to see the cause of the change. But decided to accept it, as it makes the `explain` output better match the underlying text - and also if any users share explanations in GitHub or Discord, the extra characters will at least be visible.
Fix …
> feat: 'explain' shows effect of Line Continuations & Placeholders

- resources/sample_vaults/Tasks-Demo/Test Data/multiple_headings.md
- src/Obsidian/Cache.ts
- src/Obsidian/FileParser.ts
- src/Task/TaskLocation.ts
- tests/Obsidian/FileParser.test.ts
- tests/Obsidian/SimulatedFile.ts
- tests/Obsidian/__test_data__/multiple_headings.json
- Convert `parseFileContent()` in to a class `FileParser`.
-  By making some parameters fields, I can start extracting methods that have a reasonable number of parameters themselves.
- Initially, the big win is the extraction of `FileParser.parseFileContent()`, which greatly reduced the complexity of `FileParser.parseLine()`
Note that some of the new fields may turn out to be redundant - but I wanted to merge progress so far, why the diffs are still moderately readable.
Note that because of a change in indentation in some of this code, the diffs are easier to read in this Web UI if enabling GitHub's **'Hide whitespace'** option:
Preparing to fix:
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3170
> refactor: Introduce FileParser class

- docs/Advanced/Daily Agenda.md
- src/lib/TemplatingPluginTools.ts
- tests/lib/TemplatingPluginTools.test.TemplatingPluginTools_date_templating_error_sample_for_docs.approved.text
I just discovered that the URL in some help text was wrong...
The URL in this Tasks error message gave a 404:
The file name was ommitted.
The correct URL is:
https://publish.obsidian.md/tasks/Advanced/Daily+Agenda#Instruction+contains+unexpanded+template+text
Prevent a 404...
By checking the new URL...
> docs: Fix URL in the help message for unexpanded template text

- src/Renderer/QueryResultsRenderer.ts
- src/Task/ListItem.ts
- src/Task/Task.ts
- tests/Task/ListItem.test.ts
- tests/Task/Task.test.ts
This fixes a problem that @ilandikov and I had, where we wanted to move `findClosestParentTask()` from `QueryResultsRenderer.ts` to `ListItem.ts`, but when we did so, the Tasks plugin crashed on start-up.
It is more convenient to be able to to write `listItem.findClosestParentTask()` and that now works.
I thought that the `isTask` accessor would be needed to make this work, but in fact it wasn't needed. However, it may still be useful eventually in custom filters and groups.
Move code to a more logical place.
- Running the plugin and confirming that Tasks renderers `Parent-Child relationships - Searches - Tasks.md` correctly
> refactor: Add ListItem methods findClosestParentTask() and isTask()

- resources/sample_vaults/Tasks-Demo/Test Data/query_using_properties.md
- src/Query/Query.ts
- src/Renderer/QueryRenderer.ts
- tests/Obsidian/__test_data__/query_using_properties.json
- tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
- tests/Query/Query.test.ts
This fixes one of the limitations from PR #3242 - the following now works:
> Only single-line properties work. Multiple-line properties give an error message 'do not understand query'.
Note that continuation lines are not supported in multi-line properties, when they are used in placeholders.
Getting closer to releasing access to `query.file.property()` and `query.file.hasProperty()` to users...
See:
- #3083
- #3154
- Extra automated tests
Consider the following demo sample markdown note.
I have 3 Tasks searches, and they differ only in the `happens` date filter: I have a bunch of standard instructions that I want to use in all 3 searches.
Now, I can put all my standard instructions in a multi-line `common_instructions` …
> fix: Allow multi-line properties in {{query.file.property('...')}}

- src/Commands/ToggleDone.ts
- tests/Commands/ToggleDone.test.ts
- Issue/discussion: Fixes #3256
Fix a traceback error discovered earlier today:
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3256
- Adding failing tests - then fixing them
- Confirming fix by exploratory testing
> fix: Remove console error when line is deleted by 'Toggle task done' command

- src/ui/Menus/DatePicker.ts
- Fixes #3239
The new date picker is an awesome, super useful addition. But the way it was introduced, it was hard-coded for the week to start on Monday, which is not the case for many users. This fix tries to query the system's locale for the correct day of the week, and uses Monday only if no such information is available.
As described above.
Fixes #3239.
Tested on the latest Obsidian Desktop and Android app.
> fix: date picker in Reading mode & searches honours first day of week

- docs/Getting Started/Obsidian Properties.md
- docs/Scripting/Query Properties.md
- src/Renderer/QueryRenderer.ts
- src/Renderer/QueryResultsRenderer.ts
- tests/Renderer/QueryResultsRenderer.test.ts
- tests/Scripting/QueryProperties.test.query_file_properties.approved.md
- tests/Scripting/QueryProperties.test.ts
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3154
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3083
**Summary**: This is all about making the following features releasable, by fixing bugs in the initial implementation and adding documentation:
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3154
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3083
**Detail**:
1. When the user **edits any Obsidian properties in the query file**, refresh the query, in case any frontmatter properties were used in the query
2. When the user **moves or renames the file containing the query**, refresh the query, in case the query's path used in the query, such as via …
> Fix detect query property edits

- src/ui/Dependency.svelte
- src/ui/EditTask.svelte
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2214
“Create or edit Task" Modal input, there was a conflict between the Enter key event used to confirm IME conversions and the Enter key event used to create tasks, causing unintended behavior.
This has been corrected so that the Enter key is not used to create a task when the IME conversion is confirmed.
Manually tested the following
- When using IME, the task is not created when the conversion is confirmed with the Enter key. When the Enter key is pressed again, the task is created.
- When IME is not used, the task is created when the Enter key is pressed.
**before fix**
https://github.com/user-attachments/assets/b7b2b078-cf09-4048-a69e-11e2dc169e7b
**after fix** …
> fix: Handle Enter key event for IME inputs

- src/i18n/locales/en.json
- src/i18n/locales/zh_cn.json
Translate the untranslated entries into Chinese and adjust the original Chinese translations.
for i18n
Standard i18n translation methods should not break the code, so no actual testing was done.
> i18n: Enhance Chinese Translation

- docs/Queries/Layout.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_non_task_child.md
- src/Obsidian/FileParser.ts
- src/Task/ListItem.ts
- src/Task/TaskRegularExpressions.ts
- tests/Obsidian/AllCacheSampleData.ts
- tests/Obsidian/Cache.test.ts
- tests/Obsidian/__test_data__/inheritance_non_task_child.json
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_should_render_non_task_check_box_when_global_filter_is_enabled.approved.html
- tests/Renderer/QueryResultsRenderer.test.ts
- tests/Task/ListItem.test.ts
- tests/ui/EditableTask.test.ts
- some progress on addressing #3170
- `ListItem` now optionally stores a status character
- see #3170
- unit tests
With this markdown - and a global filter `#task`:
~~~
-  [ ] #task task parent
- list item child
```tasks
filename includes {{query.file.filename}}
show tree
```
~~~
> fix: render non-task list items in tree

- docs/Queries/Explaining Queries.md
- docs/Queries/Line Continuations.md
- docs/Queries/Regular Expressions.md
- docs/Scripting/Placeholders.md
- src/Query/Explain/Explainer.ts
- tests/Config/DebugSettings.test.ts
- tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text
- tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text
- tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_filters-date-examples.approved.explanation.text
- tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-week-month-quarter-year.approved.explanation.text
- tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-weekday.approved.explanation.text
- tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt
- tests/Query/Query.test.ts
- tests/Query/QueryRendererHelper.test.ts
- Issue/discussion: _no direct request - but I have noticed since the addition of "Query File Defaults" that `explain` output is becoming very cluttered_
Remove this output from `explain` output:
```
No grouping instructions supplied.
```
And this:
```
No sorting instructions supplied.
```
Where there is both a "Global Query" and "Query File Defaults", that text could appear 3 times in `explain` output, making it just very cluttered, I found.
- Updating existing automated tests
> feat: Simplify 'explain' text

- src/Obsidian/FileParser.ts
- src/Task/ListItem.ts
- src/Task/Task.ts
- tests/Obsidian/Cache.test.ts
- tests/Task/ListItem.test.ts
- tests/Task/ListItemHelpers.ts
- tests/Task/Task.test.ts
- add `TaskLocation` to `ListItem` (`TaskLocation` not removed from `Task`)
- prepare to add event listener to non-task list items with checkbox that would check/uncheck them
- unit tests
> refactor: add `TaskLocation` to `ListItem`

- lefthook.yml
Make the `lefthook` checks run all tests and lint all files, as appropriate, when `*.svelte` and `tests/Obsidian/__test_data__/*.json` are committed.
I have been unable to find a way to run the tests selectively, so have opted for just running all tests when those files are edited.
I wrote the technique up here:
- [Jest's --findRelatedTests doesn't notice JSON files](https://stackoverflow.com/a/79437866/104370)
@ilandikov and I have both been tripped up by the pre-commit checks:
- not finding errors in .svelte files
- not running tests if .svelte or test data .json files are edited
By trying to commit broken files, and confirming that the commit failed.
> chore: Run pre-commit checks on .svelte and json test data files

- src/Task/ListItem.ts
- src/Task/Task.ts
- tests/Task/ListItem.test.ts
- move `TaskLocation`-related getters from `Task` to `LIstItem`
- make `ListItem.identicalTo()` test `taskLocation` property
- #3170 
- new & existing unit test
> refactor: make ListItem class more similar to Task

- .gitattributes
- .vscode/extensions.json
- .vscode/settings.json
- contributing/Building/Setting up build environment.md
- package.json
General improvements for contributors using windows and vscode.
- Fixes an issue where a test fails due to line endings being converted to CLRF by default with git on windows.
- Includes more recommended vscode extensions technologies used by this project.
- Updates the minimum node version and documentation, since node 16 no longer works with this project.
[This test](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/0644864a853171e6ba10d02dbeeebd1686bcb42a/tests/Integration/ESBuildConfig.test.ts#L42) is currently broken when the repo is cloned on windows, due to …
> contrib, chore: Improvements to setting up a build environment, mostly for vscode and windows.

- docs/Queries/Layout.md
- resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md
- resources/sample_vaults/Tasks-Demo/Test Data/inheritance_non_task_child.md
- src/Obsidian/File.ts
- src/Renderer/QueryResultsRenderer.ts
- src/lib/LogTasksHelper.ts
- src/lib/MockDataCreator.ts
- tests/Obsidian/Cache.test.ts
- tests/Obsidian/__test_data__/inheritance_non_task_child.json
- tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_should_render_non_task_check_box_when_global_filter_is_enabled.approved.html
- Fixes #3170
- in task query results with `show tree`, child checkbox lines without the global filter now get displayed with a checkbox and these are toggle able using same behaviour as obsidian
- fix #3170 
- unit tests + new manual smoke test
With this markdown - and a global filter `#task`:
~~~
-  [ ] #task task parent
- list item child
```tasks
filename includes {{query.file.filename}}
show tree
```
~~~
> fix: Toggle non-task checkbox lines in tree view

- resources/sample_vaults/Tasks-Demo/Functions/Custom Filters With Complex Caching.md
- resources/sample_vaults/Tasks-Demo/Functions/Custom Filters With Simple Caching.md
- src/Query/SearchInfo.ts
- src/Scripting/QueryContext.ts
- tests/Query/SearchInfo.test.ts
- tests/Scripting/QueryContext.test.ts
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/3332
**WARNING: this mechanism may be changed or removed at any time: it is not recommended for use by users at this stage.**
This is an **experimental** PR, with work-in-progress, to see if I can speed up custom instructions that use `query.allTasks` to iterate over all tasks in the vault.
- It provides a mechanism to cache calculated values at the start of the search, rather than re-calculating them for all tasks, once-per-task.
- I like the mechanism, but it requires too much JavaScript knowledge for me to be comfortable yet, …
> spike: Experimentally cache data from query.allTasks calculations

- docs/Editing/Editing Dates.md
- src/ui/Menus/DatePicker.ts
- Revert some debug logging I added on `main`
- Reinstate date picker on iPhone - week starts on Monday.
- Document that the Reading Mode/Results date-picker remains hard-coded to start on Mondays, on iPhone and probably iPad too.
Note that the date picker in Reading Mode and Tasks query Results remains hard-coded to start on Monday, because it turned out that the code added in #3259 to address #3239 works well on Android, but gave an error on iPhone (and probably iPad too).
Thanks to @esm7 for suggesting the fix.
This fixes #3341.
On my iPhone 13 Pro Max - with iOS 17.1.1.
> fix: Reinstate date picker on iPhone - week starts on Monday

- docs/Getting Started/Task Dependencies.md
- Fixes #3360
Fix "Unsupported markdown: list" errors on mermaid diagrams in the "Tasks Dependencies" page.
Diagrams on the 'Task Dependencies' page were broken by Obsidian's update to Mermaid 11.
Fixes #3360
Fix #3360 by escaping the markdown list character in Mermaid diagrams.
This works around the following Mermaid issue:
- <https://github.com/mermaid-js/mermaid/issues/6099>
- Viewing the edited docs in Obsidian 1.8.9.
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/3ae7339b-94de-4cb4-817b-e576b6b795c3) | ![image](https://github.com/user-attachments/assets/e6dc6eba-c214-40f6-9a32-67157147d5fd) |
> docs: Fix "Unsupported markdown: list" mermaid diagram errors

- docs/Queries/Explaining Queries.md
- src/Query/Explain/Explainer.ts
- src/Query/Query.ts
- tests/Query/Explain/DocsSamplesForExplain.test.explain_query_file_defaults_explanation.approved.explanation.text
- tests/Query/Explain/Explainer.test.ts
- tests/Query/QueryRendererHelper.test.ts
- Issue/discussion: #2093
Include all the [Layout](https://publish.obsidian.md/tasks/Queries/Layout) instructions in `explain` output.
Fixes #2093.
> feat: Include layout instructions in 'explain' output

- docs/Queries/Global Query.md
- src/Config/GlobalQuery.ts
- src/Query/Explain/Explainer.ts
- src/Query/Query.ts
- src/Query/QueryRendererHelper.ts
- tests/Config/GlobalQuery.test.ts
- tests/Query/Explain/Explainer.test.ts
- tests/Query/QueryRendererHelper.test.ts
Make 'ignore global query' visible in `explain` output when it used outside of the Global Query.
Also explicitly confirm that the `explain` instruction is not explained, as it clutters up the docs and would not add any extra useful information.
Make the `explain` output cover all instructions.
- New tests
Sample note:
~~~
---
TQ_extra_instructions: |-
ignore global query
happens before today
---
```tasks
explain
ignore global query
limit 1
```
~~~
Gives this:
> feat: Explain 'ignore global filter'

- src/Obsidian/InlineRenderer.ts
- src/Renderer/QueryRenderer.ts
- src/main.ts
Tasks code block has to be executed AFTER the layout is ready but the handler might need to be registered BEFORE that.
This enables Tasks to show results forany Queries in Callouts in Live Preview, when already opened at start-up.
Fixed #3366
Manual testing locally
> fix: register handlers before the layout is ready

- src/Obsidian/FileParser.ts
- src/Task/ListItem.ts
- src/Task/Task.ts
- tests/Task/ListItem.test.ts
- tests/Task/ListItemHelpers.ts
- tests/TestingTools/TaskBuilder.test.ts
- Add `ListItem.fromListItemLine()` method, similar to `Task.fromLine()`
- Use `ListItem.fromListItemLine()` instead of the constructor
- Use destructured parameter in `ListItem` constructor similar to `Task`
- Make `ListItem` shape and patters similar to `Task`
This is in preparation for allowing `ListItem.fromListItemLine()` to return `null` if given a non-list-item line.
- Unit tests
> refactor: `ListItem` construction

- src/Scripting/TasksFile.ts
- src/Task/ListItem.ts
- src/Task/Task.ts
- src/Task/TaskLocation.ts
- tests/Scripting/TasksFile.test.ts
- tests/Task/ListItem.test.ts
- tests/Task/TaskLocation.test.ts
Thanks to @ilandikov for pairing on this to help me get it to the finishing line.
1. Clearly divide up the responsibilities for checking whether 2 objects have identical content.
2. Remove from `Task` and fields that are now also present in `ListItem`.
With the addition of `ListItem`, we had ended up with some overlap in the responsibilities of:
- `ListItem.identicalTo()`
- `Task.identicalTo()`
This PR adds equivalent methods to `TasksFile` and `TaskLocation`, so that each layer is responsible for checking its own fields.
Automated tests.
> refactor: Provide consistent identicalTo() methods

- src/Obsidian/FileParser.ts
- src/Task/ListItem.ts
- src/Task/Task.ts
- tests/Task/ListItem.test.ts
`ListItem.fromListItemLine()` now returns `null` if the given line is not a list item.
This makes it consistent with the corresponding method on `Task` and fixes a failing test.
- Part of a series of clean-up steps after the initial fixing of #3170.
Unit tests.
> refactor: Finish implementing ListItem.fromListItemLine()

- src/Renderer/QueryResultsRenderer.ts
- src/Renderer/TaskLineRenderer.ts
Move some code that in #3338 was copied from `TaskLineRenderer` back to that file.
There is still code duplication, but at least it is all in one file now.
With unit tests.
> refactor: Move code for rendering ListItems to TaskLineRenderer

- docs/Editing/Auto-Suggest.md
- src/Suggestor/Suggestor.ts
- tests/Suggestor/Suggestor.test.ts
- Issue/discussion: #1509
If the user has defined the status symbol as `NON_TASK` the line should be ignored by the Tasks auto-suggest feature.
Fix #1509.
- New unit test (and confirmed that this failed before the fix)
> fix: Prevent Auto-Suggest for 'NON_TASK' statuses

- src/Task/ListItem.ts
- tests/Task/ListItem.test.ts
- `ListItem.fromListItemLine()` now correctly returns `null` for non-list item lines
- This completes work done #3374 
- code improvement
- unit tests
> refactor:  `ListItem.fromListItemLine()` now correctly returns `null`

- resources/sample_vaults/Tasks-Demo/Test Data/internal_heading_links.md
- src/Obsidian/InlineRenderer.ts
- src/Renderer/QueryResultsRenderer.ts
- src/Renderer/TaskLineRenderer.ts
- tests/Obsidian/__test_data__/internal_heading_links.json
- tests/Renderer/TaskLineRenderer.test.ts
This refactors the fix for https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3297
The goal was to remove the need to create new `Task` objects during rendering.
- Manual exploratory testing, by adding a Tasks search to:
- `resources/sample_vaults/Tasks-Demo/Test Data/internal_heading_links.md`
> refactor: Remove need to construct temporary Task objects

- docs/Queries/Grouping.md
- docs/Scripting/Custom Grouping.md
- src/Query/Filter/FunctionField.ts
- tests/Query/Filter/FunctionField.test.ts
- tests/Query/Group/TaskGroups.test.ts
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.urgency_docs.approved.md
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.other_properties_task.urgency_results.approved.txt
- tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts
- Issue/discussion: #3371
If custom group labels are floating point numbers, round them to a fixed 5 decimal places, to prevent observed problems of the sort order appearing random, if floating point group labels have different numbers of decimal places.
Fix #3371:
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3371
- New tests
> fix: Stable `group by function task.urgency` order

- src/Obsidian/Cache.ts
- Relates to #3283
This adds a small delay between successive redraws of Tasks search results.
This speeds up situations where more than one file containing tests is modified within that 0.1 second window, which can happen with things like:
- Changes being synced in from another device
- Bulk edits being made in the vault, for example:
- Renaming a property
- Doing multi-file find-and-replace in a text editor
- Running the Lint plugin on a folder or folders
- A folder being renamed
Previously, Tasks would redraw all open queries on every individual file edit, for files that contain lines it considers to be tasks.
This also eliminates some double redraws that I have not previously been able to track down.
Time …
> fix: Improve performance when multiple files are edited quickly

- resources/sample_vaults/Tasks-Demo/Manual Testing/Task Toggling Scenarios/On Completion Delete.md
- src/Commands/ToggleDone.ts
- src/Obsidian/LivePreviewExtension.ts
- Issue/discussion: #3342
Prevent 'On completion: Delete' leaving blank lines in the file, when completing non-recurring, self-deleting tasks via:
- Live Preview, clicking on the checkbox
- The `Tasks: Toggle task done` command
Fix #3342 
- Exploratory testing, including using content of the file `On Completion Delete.md`
> fix: Stop onCompletion: delete leaving blank lines for non-recurring tasks

- src/Config/Settings.ts
- src/Scripting/QueryContext.ts
- tests/Scripting/Includes.test.ts
- add first version of reusable instructions, not yet ready for public use
- prepare to introduce includes
- #2443 
- #2267 
- unit tests
- exploratory testing
> refactor: prepare includes

- src/Renderer/QueryRenderer.ts
- #3335
- #3428
QueryRenderer now only listens out for renames to the file containing the query, rather than to any file in the vault.
- Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3335
- Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3428
Exploratory testing, using the reproduction steps in the two linked issues.
Cases tested:
- That it no longer updates queries in files other than the one that was renamed
- That it does still update queries in the one that is renamed
> fix: {{query.file...}} no longer broken when renaming other files (#3335, #3428)

- docs/Scripting/Includes.md
- docs/Scripting/Placeholders.md
- src/Query/Query.ts
- tests/Scripting/Includes.test.ts
- Issue/discussion:
- #2443 
- #2267 
- #2443 
- #2267 
- unit tests
- exploratory tests (TODO
> feat: Partial implementation of 'include' instruction

- docs/Queries/Query File Defaults.md
- docs/What is New/Changelog.md
- src/Query/Query.ts
- tests/Query/Query.test.ts
- tests/Scripting/Includes.test.ts
- Issue/discussion: None, but it fixes a limitation that was mentioned in the `TQ_extra_instructions` docs
Fix a documented limitation that instructions in `TQ_extra_instructions` and in multi-line placeholders did not support line continuations.
I am addressing limitations in the forthcoming "includes" feature (that is its current working name - I don't yet know what the finale name will be.)
- Updating existing unit tests
- Manual exploratory testing
Here is an example Markdown file that now works:
~~~
---
task_instructions_with_continuation_line: |-
path \
includes query_using_properties
---
```tasks
explain
{{query.file.property('task_instructions_with_continuation_line')}}
```
~~~
Before, it gave an error:
Now it works:
That used a …
> fix: Support line continuations in TQ_extra_instructions & placeholders

- src/Config/IncludesSettingsService.ts
- src/Config/SettingsTab.ts
- tests/Config/IncludesSettingsService.test.ts
- Refactor a lot of the Includes UI logic out to a new class, `IncludesSettingsService`
- Extract `SettingsTab.saveIncludesSettings()` to remove a lot of repetition.
Goal: Make the Includes settings UI code easier to understand, maintain and test:
- New tests added
- Manual exploratory testing
> Refactor add includes settings service

- resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
- resources/sample_vaults/Tasks-Demo/How To/Reuse instructions across the vault.md
- src/Config/IncludesSettingsService.ts
- src/Config/IncludesSettingsUI.scss
- src/Config/IncludesSettingsUI.ts
- tests/Config/IncludesSettingsService.test.ts
Mostly initially created with Claude.ai - with some help from @ilandikov cleaning up the code somewhat.
- #2443 
- #2267
- **Settings:**
- If two includes have the same name, ignoring surrounding spaces, display them in red
- **Sample vault:**
- Add a few pre-defined instructions ("Includes") to the settings
- Added page for manual testing: `resources/sample_vaults/Tasks-Demo/How To/Reuse instructions across the vault.md`
Wanting to release these features:
- #2443 
- #2267
> feat: Add error-checking of duplicate names of "Includes"

- docs/Queries/Sorting.md
Create a link to Grouping.md from Sorting.md to support readers who want to reverse the order of groups in grouped queries
This change introduces a link between two documentation pages having to do with reversing the sort direction when ordering Tasks or Groups.
In attempting to create a "captain's log" of tasks already done, sorted reverse chronologically, I discovered that `SORT BY` does not effect the order of groups when using a `GROUP BY` clause. I began opening a bug report and, while doing so, discovered Tasks supports reversing the order of groups via the `GROUP BY` clause, rather than the `SORT BY` (which is different than SQL, where I'm more familiar). Rather than opening a bug against `SORT BY`, this PR simply intends on making future readers' lives a …
> docs: Link Sorting.md to related section in Grouping.md

- resources/sample_vaults/Tasks-Demo/How To/Reuse instructions across the vault.md
- src/Config/IncludesSettingsUI.ts
- src/Config/SettingsTab.ts
- src/Obsidian/TasksEvents.ts
- src/Renderer/QueryRenderer.ts
- src/Renderer/QueryResultsRenderer.ts
- src/main.ts
- tests/Renderer/QueryResultsRenderer.test.ts
- #2443 
- #2267
1. This is a major improvement to the usability of the Includes feature:
- Editing its settings now does a debounced refresh of any open search results.
- The debounce time is currently 300ms.
2. It works by adding a new event: `'obsidian-tasks-plugin:reload-open-search-results'`
- This may be useful later, for example in updating search results if the Global Query is edited in settings.
3. It also makes a demo file a bit easier to understand and use:
- `resources/sample_vaults/Tasks-Demo/How To/Reuse instructions across the vault.md`.
Wanting to release these features:
- #2443 
- #2267
- Added a new test for part of the change.
- Lots of manual exploratory testing in the test vault.
> feat: Editing any Includes setting redraws open Tasks searches

- docs/What is New/Changelog.md
- i18next-parser.config.js
- src/i18n/i18n.ts
- src/i18n/locales/de.json
Add German translation of settings UI.
This translation was contributed by @i-am-the-slime - thank you!
Help German users edit their Tasks settings
I got Claude.ai to translate it back to English, and did a quick visual inspection of the differences from the original English strings.
I also built the plugin and set Obsidian to German, to confirm that the settings were displayed in German.
> i18n: Add German translation of settings UI

- src/Config/IncludesSettingsUI.scss
- src/Config/IncludesSettingsUI.ts
- Issue/discussion: Preparing to release features for:
- #2443 
- #2267
Adjust the Includes settings to work on narrow screens.
Trying to get the code releasable for:
- #2443 
- #2267
- By building and running the plugin locally on Mac
- By using device emulation on the Dev tools, using the Theme Design Utility Plugin's 'Toggle mobile emulation' command
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/80ad4702-e642-4f2f-94b5-45b0032b4c82)  |     ![image](https://github.com/user-attachments/assets/b02ae09e-62c0-4835-aee3-61831fb40b29) | 
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/ed6b1957-26b4-4df6-97f9-4002f9e3896c) | …
> fix: Includes settings now work on mobile and narrow windows

- src/Config/IncludesSettingsUI.scss
- src/Config/IncludesSettingsUI.ts
- Issue/discussion: settings for #2443 
- Delete button is now well positioned on all screen sizes (always on the right, even on smaller screen sizes, where the position of the key-value inputs is vertical
- Improve UI for #2443
- Build + manual test in demo vault
- CSS and settings code not covered by tests
> feat: arrange the delete button in the includes settings

- src/Suggestor/EditorSuggestorPopup.ts
- Issue/discussion: #3475
1. Fix issue #3475, that Tasks caused a console error message in the Task Board plugin's 'Add new task' modal
2. Fix related issue, found in testing: 
- If the other plugin does not supply a `TFile` to `onTrigger()`, then confirm that Tasks cannot offer suggestions.
- This enables the Natural Language Dates plugin's `@today` and similar to work inside the Task-Board plugin's `Add new task` modal when Tasks is installed.
Fix #3475.
- By following the reproduction steps in #3475
- By confirming that Auto-Suggest still works in the test vault
- By testing that the Natural Language Dates plugin works inside the Task-Board plugin's 'Add New Task' modal when Tasks is installed, with suggestions enabled.
> fix: Suppress Tasks Auto-Suggest in Task-Board plugin modal (#3475)

- contributing/Architecture Decisions/ADR-001 - Nomenclature for Reusable Instruction Blocks Feature.md
- contributing/Architecture Decisions/About Architecture Decisions.md
- contributing/Welcome.md
- docs/Scripting/Placeholders.md
- docs/Scripting/Presets.md
- resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json
- resources/sample_vaults/Tasks-Demo/How To/Reuse instructions across the vault.md
- src/Config/IncludesSettingsUI.ts
- src/Config/Settings.ts
- src/Config/SettingsTab.ts
- src/Query/Query.ts
- src/Scripting/Includes.ts
- src/Scripting/QueryContext.ts
- tests/Config/Settings.test.ts
- tests/Renderer/QueryResultsRenderer.test.ts
- tests/Scripting/Includes.test.ts
- #2443 
- #2267
Note: I am labelling this a **breaking change** because it does **rename an unreleased feature**.
I believe that I am likely the only person who is using the feature, so in practice it will not require a major-version-number bump.
Done:
1. Write an Architecture Decision Record (ADR) recording the names I considered, and why I chose the name I did.
2. Rename the `include` facility to `preset`, to avoid confusion with the `includes/does not include` text search instructions.
- `include my_lovely_filters` => `preset my_lovely_filters`
- `{{includes.my_lovely_filters}}`=> `{{preset.my_lovely_filters}}`
- Note the change from plural to singular
3. Automatically migrate any `includes` values in the vault's Tasks …
> feat!!: Rename 'include' facility to 'preset'

- src/Scripting/TasksFile.ts
- src/Task/Link.ts
- tests/Task/Link.test.ts
_This replaces the following PR, which I squashed by mistake and so reverted:_
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/3494
- #2443 
- #2267
1. This is a major improvement to the usability of the Includes feature:
- Editing its settings now does a debounced refresh of any open search results.
- The debounce time is currently 300ms.
2. It works by adding a new event: `'obsidian-tasks-plugin:reload-open-search-results'`
- This may be useful later, for example in updating search results if the Global Query is edited in settings.
3. It also makes a demo file a bit easier to understand and use:
- `resources/sample_vaults/Tasks-Demo/How To/Reuse instructions across the vault.md`.
Wanting to release these …
> refactor: Minor refactoring of links code and tests

- src/Config/PresetsSettingsUI.ts
- Issue/discussion: #3510
Make drag-and-drop in the Presets section of settings only act upon the drag handle.
This allows users to click and drag to select text for editing.
Fix #3510.
Manually, in the sample vault.
> fix: Allow text selection with mouse in Preset settings

- .gitignore
- src/Obsidian/InlineRenderer.ts
- src/Renderer/QueryRenderer.ts
- src/Renderer/QueryResultsRenderer.ts
- src/Renderer/TaskLineRenderer.ts
- src/main.ts
- tests/Renderer/QueryResultsRenderer.test.ts
- tests/Renderer/RenderingTestHelpers.ts
- tests/Renderer/TaskLineRenderer.test.ts
- tests/__mocks__/obsidian.ts
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/3151#issuecomment-3014283469
Currently the tasks plugin is using the following API to render markdown: https://docs.obsidian.md/Reference/TypeScript+API/MarkdownRenderer/renderMarkdown
Said API is deprecated in favor of https://docs.obsidian.md/Reference/TypeScript+API/MarkdownRenderer/render
I didn't find any confirmation after a quick search, but my theory of why this fixes the issue with Live Preview attachments preview is that it allows the markdown renderer mechanism to access information related to the app settings, such as the attachments folder for example.
Motivation is to be able to render the attachments I added to my tasks for context, when using …
> fix: Inline attachment previews are now visible in Live Preview and Reading modes

- resources/sample_vaults/Tasks-Demo/How To/Access links.md
- src/Task/Link.ts
- tests/Task/Link.test.ts
I am labelling this as a refactor, because it changes un-released code.
I kept finding this to be rather unreadable - and not intuitive to type:
````text
```tasks
filter by function task.outlinks.some(link => link.isLinkTo(query.file))
```
````
So I have changed it to:
````text
```tasks
filter by function task.outlinks.some(link => link.linksTo(query.file))
```
````
In other words, `isLinkTo()` becomes `linksTo()`
One step closing to releasing searching of links.
> refactor: Rename `Link.isLinkTo()` to `Link.linksTo()`

- docs/Getting Started/Obsidian Properties.md
- docs/Scripting/Task Properties.md
- resources/sample_vaults/Tasks-Demo/Test Data/docs_sample_for_task_properties_reference.md
- tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.DocsSamplesForDefaults_interpret_properties.approved.yaml
- tests/DocumentationSamples/DefaultsDocs/DocsSamplesForDefaults.test.ts
- tests/Obsidian/__test_data__/docs_sample_for_task_properties_reference.json
- tests/Scripting/TaskProperties.test.task_frontmatter_properties.approved.md
- tests/Scripting/TaskProperties.test.ts
It turns out that the requested features in #3580 are already supported.
This writes the tests to prove that, and shows the results in the documentation.
The following documentation pages will be updated, when the user docs are next published:
- https://publish.obsidian.md/tasks/Getting+Started/Obsidian+Properties
- https://publish.obsidian.md/tasks/Scripting/Task+Properties
This also removes the need for a manual step in updating the docs.
Fix #3580.
- Exploratory testing in the sample vault
- Writing tests to demonstrate the behaviour
- The results of those tests are auto-embedded in the documentation.
> docs: Document access to nested and object properties

- src/Scripting/TasksFile.ts
- src/Task/Link.ts
- src/Task/LinkResolver.ts
- src/Task/ListItem.ts
- tests/Scripting/TaskProperties.test.ts
- tests/Task/Link.test.ts
- tests/Task/LinkResolver.test.ts
Done by pairing with @claremacrae.
- `Link` objects now take less memory
- May reduce Obsidian restarts in large vaults on mobile devices
- Unit tests
- Exploratory test in demo vault
> refactor: reduce memory usage with dynamic destination path

- src/Config/SettingsTab.ts
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2684
- redraw automatically debounced search results after global query is edited
- Related to #2684
> feat: redraw search results after global query is edited

- docs/Getting Started/Recurring Tasks.md
This slightly refines the documentation changes made in #3592.
Getting ready for release...
Edited and reviewed in Obsidian.
_Click to expand image..._
> docs: Refine 'Priority of Dates' section for recurring tasks

- src/Config/SettingsTab.ts
- src/Obsidian/Cache.ts
- src/Obsidian/TasksEvents.ts
- src/main.ts
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2684
- redraw automatically debounced search results after global filter is edited
- Related to #2684
> feat: redraw search results after global filter is edited

- src/Renderer/Renderer.scss
- Issue/discussion: #3603
Remove a !important CSS block that is no longer needed.
This was added to fix this issue:
- #2361
Investigation has shown that the underlying issue has been fixed in Obsidian, so the workaround is no longer needed.
Fixes #3603
See all my discussion in #3603 for the testing I did before making this change.
See my screenshots posted in #3603
> fix: Enable themes to modify indentation in Live Preview (#3603)

- tests/Obsidian/SimulatedFile.ts
- tests/Scripting/TasksFile.test.ts
- tests/TestingTools/MockDataHelpers.ts
- tests/TestingTools/MockDataLoader.test.ts
- tests/TestingTools/MockDataLoader.ts
- tests/TestingTools/TaskBuilder.ts
- tests/__mocks__/obsidian.ts
It is no longer necessary to call `setCurrentCacheFile()` in tests.
This makes it possible to write tests that use more than one of the MockData files at once.
This because possible now that we have `MockDataLoader`, and it caches the data that it returns.
Preparation for implementing unit tests for:
- #3627
Lots of work on unit tests.
> test: Remove uses of a singleton in mocked Obsidian functions
