obsidian-tasks-group/obsidian-tasks

README.md
=> Update README.md (typo reagard -> regard)

README.md
=> Update typo from ": Crete or edit"

README.md, src/Query.ts
This adds the simple "is recurring" / "is not recurring" filter to task queries.
I'd love to see this merged and then a separate issue about more complex queries (around "is recurring daily" or "is not recurring on Thursdays") get opened.
Closes #82
=> Add is/is not recurring to query system

src/Query.ts, tests/Query.test.ts
This adds tests for the `happens` filter that was added in #515.
=> Add tests for happens instruction

src/Query.ts, src/QueryRenderer.ts
This will aid testing later, when the `group by` feature is added.
=> Move applyQueryToTasks() from QueryRenderChild to Query

docs/docker_start
This enables docker_start to run on my Mac. See #647.
=> Fix docker image name.

.github/pull_request_template.md
Clarify the definition of refactoring in the PR template.
=> chore: Strengthen the definition of refactoring in PR template

.github/ISSUE_TEMPLATE/issue-template.md, .github/pull_request_template.md, CONTRIBUTING.md, README.md, docs/README.md, docs/_config.yml, docs/advanced/notifications.md, docs/index.md, docs/queries/grouping.md, docs/queries/index.md, manifest.json, src/File.ts, src/Query/Filter/StartDateField.ts, tests/Query.test.ts
@claremacrae after moving the repo to the org, I updated all links in the repo.
=> Move to organization

docs/_sass/custom/custom.scss
Add `_sass/custom/custom.scss`, with content taken from https://github.com/just-the-docs/just-the-docs/issues/681#issuecomment-913238465
This is to fix #734, and improve the styling of block-quotes in the published docs. See screenshots below.
---
None of those. Just a documentation styling change.
None relevant.
=> docs: Add styling for blockquotes, for 'Introduced in' comments

docs/_config.yml, docs/_sass/color_schemes/wider-content.scss, docs/advanced/index.md, docs/quick-reference/index.md
- Add new page with table of all the instructions supported in `tasks` blocks
- Increase the content width of the documentation from 800px to 1000px, to reduce wrapping in cells in the new file
See #685 for previous discussion on this.
By running the docs in docker on my Mac.
Here is where it is linked from:
And here is what it looks like:
=> docs: Add a Quick Reference page to the docs

.github/ISSUE_TEMPLATE/issue-template.md
- Clarify Issue template - it's for issues only, not features.
- Also, comment out the introductory text, so that it is not rendered in the final bug reports.
- To reduce time spent asking for more information in issues, and to try to steer more feature requests from issues to discussions.
It can be tested once it's merged.
=> chore: Clarify Issue template - it's for issues only, not features.

.github/dependabot.yml
Add dependabot.yml to try to automate Dependabot updating of dependency versions.
Save developer time, and ensure we stay up-to-date.
It hasn't yet, but should be executed after it is merged.
=> chore: Add dependabot.yml to automate updates

manifest.json
In https://github.com/obsidianmd/obsidian-releases/pull/984, Martin kindly added my name to the list of authors for this plugin, in the community plugin store.
This PR makes the same change to `manifest.json` in this repo.
=> chore: Add Clare Macrae to author list in manifest.json to match community store

src/Query.ts, src/Query/Filter/DateField.ts, src/Query/Filter/Field.ts, src/Query/Filter/HappensDateField.ts, src/Query/Filter/PriorityField.ts, src/Query/Filter/StatusField.ts, src/Query/Filter/TagsField.ts, src/Query/Filter/TextField.ts, tests/Query.test.ts, tests/Query/Filter/StatusField.test.ts
1. Add `StatusField` class
2. Rework Query to use `StatusField` for `done` and `not done` filters
3. Add `StatusField.test.ts` with simple tests for this new class 
4. Two new methods added to Field, to encapsulate the checking whether lines match regexes, because the `StatusField` class does not support any regex-based instructions, so I needed a way for `StatusField` to indicate it didn't have any regex instructions by returning null. 
More progress on #664 
By running the existing tests, and adding some new ones.
By creating a Pull Request you agree to our [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md). For further guidance on contributing please see [contributing guide](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/m …
=> refactor: Add StatusField class, for handling done/not done filters

src/Query.ts, src/Query/Filter/RecurringField.ts, tests/Query/Filter/RecurringField.test.ts
1. Add `RecurringField ` class
2. Rework Query to use `RecurringField ` for `is recurring` and `is not recurring` filters
3. Add `RecurringField.test.ts` with simple tests for this new class
More progress on #664 
By running the existing tests, and adding some new ones.
=> refactor: Add RecurringField class, for handling recurring/not recurring filters

resources/sample_vaults/Tasks-Demo/Manual Testing/654 - Unable to find section, when title has tag inside.md, resources/sample_vaults/Tasks-Demo/Manual Testing/README - Manual Testing.md, resources/sample_vaults/Tasks-Demo/Manual Testing/README - User Support.md
This adds to the Tasks-Demo vault `654 - Unable to find section, when title has tag inside.md` which contains a heading with a tag in, to demonstrate the problem.
This is a manual test for issue #654 - and the proposed PR for fixing it in #802.
By viewing the page in Obsidian with Tasks 1.8.0, and confirming that the issue exists.
=> test: Add a manual test for issue #654

src/QueryRenderer.ts
A trivial totally automated refactoring, done in WebStorm.
This just ensures that if the heading sanitisation code needs to change again in future, it only needs to change in one place.
It was an automated refactoring, so not expected to fail.
But I did test it by doing a build of the plugin, and testing that it could still find the link in the file I added in #807.
=> refactor: Extract variable in addBacklinks() to simplify code slightly

src/Query/Filter/Filter.ts, src/Query/Filter/FilterInstruction.ts, src/Query/Filter/FilterInstructions.ts, src/Query/Filter/RecurringField.ts, src/Query/Filter/StatusField.ts
- Introduce new classes `FilterInstruction` and `FilterInstructions` to hide away a bunch of boilerplate code in writing task filters.
- See the changes in `RecurringField.ts` and `StatusField.ts` for how much the code has been simplified
=> refactor: Simplify implementations of RecurringField and StatusField

src/Query.ts, src/Query/Filter/ExcludeSubItemsField.ts, tests/Query/Filter/ExcludeSubItemsField.test.ts
1. Add `ExcludeSubItemsField` class
2. Rework Query to use `ExcludeSubItemsField` for ` exclude sub-items` filter
3. Add `ExcludeSubItemsField.test.ts` with simple tests for this new class
More progress on #664 
**This is the last of the filter code in `Query` now split out in to a separate class.**
By running the existing tests, and adding some new ones.
=> refactor: Add ExcludeSubItemsField, for handling 'exclude sub-items' filter

resources/sample_vaults/Tasks-Demo/Manual Testing/654 - Unable to find section, when title has tag inside.md, src/QueryRenderer.ts
Make `QueryRenderer.addBacklinks()` replace all `#` in headings, instead of just the first one.
I tried the suggested `replaceAll()` and got an error that it did not exist. It was easier to convert to use a global regular expression than to mess around with settings in the project.
Fixes #842, which was raised after a question in comments on #802, so that clicking on a backlink navigates to tasks in sections with 2 or more tags in.
By:
1. building the plugin locally
2. deploying it to `resources/sample_vaults/Tasks-Demo/
3. Confirming that navigating to the heading works in `resources/sample_vaults/Tasks-Demo/Manual Testing/654 - Unable to find section, when title has tag inside.md`
By creating a Pull Request you agree to our [Code of …
=> Fix link to headings with 2 tags

src/Urgency.ts
Fix for #832 from @sytone in #799
Authored-by: @sytone 
Tested-by: @AnnaKornfeldSimpson 
All tests pass locally on my machine now. 🎉 Tests also pass on CI.
I agree to the [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md).
=> Urgency DST Fix from @sytone

yarn.lock
Deleted my `node_modules` folder and did `yarn install` - and saved the results.
See https://github.com/obsidian-tasks-group/obsidian-tasks/pull/852#issuecomment-1176763207
=> build: Add boon-js to yarn.lock

src/Query/Filter/BooleanField.ts, tests/Query/Filter/BooleanField.test.ts
Added `tests/Query/Filter/BooleanField.test.ts` with some tests I was writing whilst reviewing #852.
Also fixed a couple of minor typos in BooleanField error messages whilst there.
I wanted tests that were easy to reason about the various boolean operators.
And I wanted to see the as many of the error messages from BooleanField as I could generated.
By running existing and new tests.
=> test: Add BooleanField.test.ts with lower-level tests of BooleanField

src/Cache.ts, src/File.ts, src/LivePreviewExtension.ts, src/Query/Filter/BooleanField.ts, src/Query/Filter/FilterInstruction.ts, src/Query/Filter/FilterInstructions.ts, src/QueryRenderer.ts, src/Suggestor/EditorSuggestorPopup.ts, tests/EditorSuggest.test.ts, tests/Query.test.ts
@esm7 Could you code review this please, when you have a chance? Some of these touch your recent innovations, so I am hoping you can confirm that the imports **are** just being used for types.
An updated version of svelte's provided `tsconfig` turns on a check for imports that are being used only for types not as values. This PR just fixes the spots that were alerted by this rule; it does not contain the updated rule or any dependency changes.
I was checking through updated dev dependencies on my fork and one of the svelte related updates turns on an additional tsconfig rule to `error` for `import` statements that are being used only for typechecking. This seems like a thing worth fixing even without the dependency upgrade, since marking them as `import type` is both more correct and …
=> chore: internal: Fix imports only used for types

docs/queries/combining-filters.md, docs/queries/filters.md, docs/quick-reference/index.md, resources/sample_vaults/Tasks-Demo/Filters/Boolean Combinations.md
Assorted fixes to the documentation and to `Boolean Combinations.md` in the sample vault, from code review of #879.
#879. code review.
Viewing changes in IDE
=> docs: Fixes to Combining Filters docs (code review)

tests/Task.test.ts
Add a unit test for Task.toggle in the "done to undone" direction.
I was trying to figure out how to use Jest's "coverage" tool. Thought I might as well push the unit test I added while doing so. :) 
New test passes locally.
By creating a Pull Request I agree to the [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md).
=> test: Add a unit test for task untoggling

.github/ISSUE_TEMPLATE/issue-template.md, .github/pull_request_template.md, README.md
Fixes a broken link in the README and a couple markdownlint errors found by the upgraded markdownlint in #938 
Edit: This fixes two broken links when Tasks is viewed in the Obsidian Community Plugins browser.
By creating a Pull Request I agree to the [Code of Conduct](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/CODE_OF_CONDUCT.md).
=> fix(README, docs): broken links, markdownlint errors

docs/getting-started/recurring-tasks.md
Document two recurring examples that I wasn't aware of:
`🔁 every month on the last`
`🔁 every February on the last`
It results from [a question in discord](https://discord.com/channels/686053708261228577/965681451297304596/1002240009623052368)
By previewing the updated text in WebStorm
=> docs: Add recurring examples showing last of the month

resources/sample_vaults/Tasks-Demo/Filters/Boolean Combinations.md
`Boolean Combinations.md` is a file in the Tasks-Demo sample vault.
This change adds a little explanation, and links to the full documentation of boolean filters.
The edit was prompted by a review comment by @AnnaKornfeldSimpson :
https://github.com/obsidian-tasks-group/obsidian-tasks/pull/879/files#r918330107
> Link here to the relevant docs page(s)? Or if worried about the link going stale, at least a link to the docs in general?
By previewing the edits in WebStorm.
New text:
=> sample: Add explanatory text in Boolean Combinations.md

package.json
This is a cherry-picked commit made by @AnnaKornfeldSimpson in a now-closed PR - #980.
I didn't want to lose the fix. Thanks Anna!
=> chore: update author name in package.json to match manifest.json

.github/ISSUE_TEMPLATE/bug-report.yaml
Provide a new form for much easier creation of bug reports.
No more reading of markdown comments.
It arose out of user feedback in #787.
It's hard to create issues via the old markdown template. This form is pretty much the same content, but a lot easier to complete.
By previewing the read-only presentation of the form in the Github web ui - see screenshots below.
---
---
=> chore: Provide form for easier bug-reports

.github/ISSUE_TEMPLATE/config.yml
Fix typo in 'Suggest a new feature' url from #987
=> chore: Fix typo in 'Suggest a new feature' url

.github/ISSUE_TEMPLATE/config.yml
Disallow blank issues.
Now we have 'Suggest a new feature' and 'Ask a question' buttons,
and a proper form for 'Bug Report', I don't think there's any need
for creating blank issues.
To encourage the supplying of enough information for bugs to be able to be reproduced and fixed.
It can't be tested until it's merged.
=> chore: Disallow blank issues

.github/PULL_REQUEST_TEMPLATE/pull-request.yaml
Convert the pull request template from Markdown to a form.
The old file is retained for now, for testing and comparison.
To make creating PRs much quicker, easier and more reliable.
It will be tested once merged.
TODO Add screenshot after change merged (and tested)
=> chore: Convert pull request template to a form

.github/pull_request_template.md
- chore: Add more type-of-change options in PRs
- I find myself often making changes not currently listed in the PR template types, so I've added them.
- Also added the Conventional Commit prefixes, to save having to check)
- chore: Add whitespace in PR template for readability
- chore: Add checkboxes to agree to terms in PRs
- chore: Link to documentation & contributing guides
To make it a little easier to create PRs.
By previewing the changed markdown in WebStorm
=> chore: Improve usability and content of PR template

.github/ISSUE_TEMPLATE/config.yml
When users choose what type of issue to create, Feature and Question options now link to previous submissions.
To help users find answers more quickly, and perhaps have a few less duplicated feature requests.
It will be tested once merged.
=> chore: Make it easier to search for existing ideas and questions

resources/sample_vaults/Tasks-Demo/Manual Testing/Callouts and Block Quotes.md
This was useful when manually testing the changes in #953.
It resolves [this comment during code review](https://github.com/obsidian-tasks-group/obsidian-tasks/pull/953/files#r938876581).
By previewing the markdown in Obsidian
=> vault: Add Callouts and Block Quotes.md sample file

docs/queries/filters.md, src/Query/Filter/DescriptionField.ts, src/Query/Filter/HeadingField.ts, src/Query/Filter/PathField.ts, src/Query/Filter/TextField.ts, tests/Query/Filter/DescriptionField.test.ts, tests/Query/Filter/PathField.test.ts
Supplied as an example. No test included. Will circle around to figuring out how to write a test in this repo if there's openness to a PR here.
=> feat: Add regular expression support to text filters

src/Cache.ts
Some tiny refactorings, to allow two variables to be const, to aid code comprehension.
From code review of #1004
By running in my main vault.
=> refactor: simplify Cache.indexFile()

docs/installation/index.md
Post in Obsidian Forums noticed typo in directions on installation page. Fixing.
[Forum post with confusion over typo](https://forum.obsidian.md/t/configuring-tasks-plugin/41860)
Will be tested by GitHub Actions CI
=> fix: Typo fix from Obsidian Forum post

src/Commands/CreateOrEdit.ts, src/Commands/ToggleDone.ts, src/Task.ts
As proposed in [this comment](https://github.com/obsidian-tasks-group/obsidian-tasks/issues/982#issuecomment-1207286916), this change removes all regexes from files in `src/Commands/` which are hard to test because of reliance on the Obsidian API. Relevant regexes are copied to `Task.ts` as discussed in the linked comment, and comments are added/updated to try to make them clear. (There was one regex in ToggleDone that I judged not worth keeping since the comments around it were not correct about Obsidian's behavior. Updated the comments instead.)
Better maintainability.
Fixes #982 
Passes automated tests, and smoke tested on Obsidian stable. This PR does not currently add new automated tests for the regexes, but I would be happy to do that, given some guidance on what to add!
Changes …
=> refactor: Remove regexes from Commands files to Task where they can be tested

docs/queries/regular-expressions.md
Fix a couple of typos in regex docs
Previewed in WebStorm.
=> docs: Fix a couple of typos in regex docs

src/Query/Filter/TagsField.ts
The `tag`/`tags` command now uses the same local-aware case-insensitive string searching as all the other text searches.
The new code now calls [`String.toLocaleLowerCase()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase) instead of `String.toLowerCase()`.
I discovered this inconsistency whilst refactoring `TagsField` to use the same search code as the other Text fields. As this was a change in behaviour, I have separated it out in to its own PR.
By running existing tests.
=> fix: Make tags searches locale-aware

docs/advanced/dataview.md, docs/other-plugins/dataview.md, docs/other-plugins/index.md
Add a short documentation page on Dataview+Tasks compatibility describing only the Dataview settings configuration needed to work best with Tasks, and directing users to Dataview documentation for all other questions.
@claremacrae To match similar docs pages, this probably needs a screenshot of the bottom of the Dataview settings page with the "Automatic Task Completion" and "Use Emoji Shorthand" toggles on. The screenshot should added near the numbered list. Is there any chance you could add this since your vault already has the right theme and font sizes for screenshots? It would be a big help!
Dataview recently released my changes to increase compatibility with Tasks, so this can go live.
Fixes #941 
Previewed the single page locally. Have not tested that the links work.
EDIT: …
=> docs: Add page on dataview settings for compatibility with Tasks

.gitignore, CONTRIBUTING.md
Note: This PR and the second commit should have `Co-authored-by: @claremacrae` but I do not know how to do that!
* chore: add jest coverage folder to gitignore
* chore: Add information on test writing from `@claremacrae` to CONTRIBUTING.md
CONTRIBUTING addition requested here https://github.com/obsidian-tasks-group/obsidian-tasks/pull/1006#issuecomment-1217552453
Tests pass locally. No smoke test needed.
=> chore: update gitignore, CONTRIBUTING.md

src/Query/Filter/BooleanField.ts, src/Query/Filter/DateField.ts, src/Query/Filter/DescriptionField.ts, src/Query/Filter/DoneDateField.ts, src/Query/Filter/DueDateField.ts, src/Query/Filter/ExcludeSubItemsField.ts, src/Query/Filter/Field.ts, src/Query/Filter/HappensDateField.ts, src/Query/Filter/HeadingField.ts, src/Query/Filter/PathField.ts, src/Query/Filter/PriorityField.ts, src/Query/Filter/RecurringField.ts, src/Query/Filter/ScheduledDateField.ts, src/Query/Filter/StartDateField.ts, src/Query/Filter/StatusField.ts, src/Query/Filter/TagsField.ts, src/Query/Filter/TextField.ts
This makes public some selected methods in `Field` and derived classes:
- refactor: Make `fieldName()` public in `Field` and derived classes
- refactor: Make `date()` public in `DateField` and derived classes
- refactor: Make `value()` public in `TextField` and derived classes
- refactor: Make `dates()` public in `HappensDateField`
- To enable re-use of these methods in other code
- To simplify writing of tests for new implementations of `Field`, when in the first instance, it's good to write test the `value()` results for various scenarios. This will likely remove some of the repetition in tests classes derived from `DateField` and `TextField`
- By running all the existing tests at each stage.
- By inspecting all the remaining `protected` methods to make sure that nothing got missed out. …
=> refactor: Make public some selected methods in Field and derived classes

README.md
The name of the Obsidian command is “Toggle checkbox status,” not “Toggle checklist status.”
=> docs: Fix "Toggle checkbox status" command name in README

src/Query/Filter/TagsField.ts
Refactor `TagsField.createFilterOrErrorMessage()` to be more similar to same method in `TextField`.
Preparing to implement #1040 - regex searching of tags
Running existing tests
=> refactor: Prepare for adding regex searching for tags

src/Cache.ts, src/QueryRenderer.ts, src/TasksEvents.ts, src/main.ts
- refactor: Rename `Events.ts` to `TasksEvents.ts`
See #1052 for motivation
- `yarn run lint`
- and running all the tests
=> refactor: Rename Events.ts to TasksEvents.ts

src/Commands/CreateOrEdit.ts, src/Commands/ToggleDone.ts, src/Suggestor/EditorSuggestorPopup.ts, src/Suggestor/Suggestor.ts, src/Task.ts
- refactor: Introduce new class `TaskRegularExpressions` in `Tasks.ts` - and move all `Task`'s regex fields in to this new class
As well as removing a lot of clutter from Task, it also eliminates another category of differences from the tasks-x plugin code - see 
- running `yarn run lint`
- running existing tests
=> refactor: Introduce new class TaskRegularExpressions

src/Commands/CreateOrEdit.ts, src/Query/Filter/StatusField.ts, src/Task.ts, src/ui/EditTask.svelte, tests/Query.test.ts, tests/Query/Filter/StatusField.test.ts, tests/Task.test.ts, tests/TestingTools/TaskBuilder.ts
- `Status.Done` -> `Status.DONE`
- `Status.Todo` -> `Status.TODO`
This is another small move to make the code more consistent with tasks-x, for ease of comparing the code bases.
- running existing tests
- `yarn run lint`
=> refactor: Capitalise the names of values in Status

tests/Query.test.ts
Fixes copy-and-paste error in a test.
By running the tests.
=> test: Verify 'group by recurring' instruction works

.github/ISSUE_TEMPLATE/internal-issue.yaml
Add a new Issue form, 'Internal Issue'.
To make it easy to capture intended improvements to the code and the project, without needing to fill in the blurb required for bug reports.
Sometimes these changes may be visible to users, like if a dependency update is non-trivial. But mostly the will be entirely internal.
It can't be tested until merged.
=> chore: Add a new Issue form, 'Internal Issue'.

src/ui/EditTask.svelte
Add horizontal dividers between each of the date sections in the Create or Edit Task modal.
I found that this enabled me to see the grouping of the widgets more easily at a glance.
I've been wanting to do this for some time. Without these lines, I just saw a wall of widgets.
And as I'm about to redo the screenshot of this modal anyway, now seemed a good time.
In my test vault.
=> ui: Add dividers between date groups in Create or Edit Task

.github/workflows/verify.yml, copy-build-to-sample-vault.sh, scripts/Test-TasksInLocalObsidian.sh
- Add script `scripts/Test-TasksInLocalObsidian.sh` that copies the built plugin in to the `Tasks-Demo` sample vault
- This can be run on developer machines.
- Unlike `scripts/Test-TasksInLocalObsidian.ps1`, it actually copies files, rather than creating soft-links that only work on the developer machine
- Adjust `.github/workflows/verify.yml` to run above script, and then zip the sample vault and upload it as an artefact for download
To make it easier to smoke-test builds, especially dependency changes.
By downloading the built vaults from GitHub.
Example build: https://github.com/obsidian-tasks-group/obsidian-tasks/actions/runs/3146878866
=> chore: Add download of Tasks-Demo vault to Verify Commit CI build

.github/workflows/release.yml
Edits to `.github/workflows/release.yml`
1. Add some whitespace to divide up the sections. (This stripped some trailing whitespace in other lines, during the pre-commit lint step)
1. Make new releases 'draft', so that I can format the release notes before they are published
1. (Hopefully) fix the missing version number in the download .zip file
To remove some manual steps from the release process, to make it easier to release more often.
It will tested during the next release.
=> chore: Streamline the release process

src/Commands/CreateOrEdit.ts, src/Task.ts, tests/Query.test.ts, tests/Task.test.ts, tests/TestingTools/TaskBuilder.ts
Store original Markdown line in Task, where possible
The code is formatted consistently with the originalMarkdown changes that were part of: https://github.com/sytone/obsidian-tasks-x/commit/77270aa8293ae20319cc7ddb3c46166515d0cd3c
Co-Authored-By: @Sytone
This will later be used to add some error-checking to the task-completion code.
- By running all the existing tests
- By writing a new test to confirm that the original line is copied in, when the task is created via `Task.fromLine()`.
=> refactor: Store original Markdown line in Task, where possible

src/Query/Filter/BooleanField.ts, src/Query/Filter/DateField.ts, src/Query/Filter/Filter.ts, src/Query/Filter/FilterInstruction.ts, src/Query/Filter/FilterInstructions.ts, src/Query/Filter/HappensDateField.ts, src/Query/Filter/MultiTextField.ts, src/Query/Filter/PriorityField.ts, src/Query/Filter/TextField.ts, src/Query/Query.ts, tests/CustomMatchers/CustomMatchersForFilters.ts, tests/Query/Filter/PriorityField.test.ts, tests/TestingTools/FilterTestHelpers.ts
Pure automated refactoring, done automatically and safely by WebStorm's refactoring tools.
- Rename Filter type to FilterFunction
- Rename FilterOrErrorMessage.filter to filterFunction
These are in preparation for introducing a Filter class
By running the existing tests.
=> refactor: Rename Filter type to FilterFunction

src/Query/Filter/BooleanField.ts
refactor: `BooleanField` now stores `Filter` instead of `FilterFunction`
This completes the move from storing the FilterFunction predicates to fully storing Filter objects throughout the code.
This will later enable me to store extra info about each of the filters from the tasks block, hopefully culminating in showing explanations of the user's filter instructions.
Running existing tests.
=> refactor: BooleanField now stores Filter instead of FilterFunction

src/Query/Filter/DateField.ts
Refactor `DateField` to use `FilterInstructions`, to remove repetition.
I'm about to add a new date-based instruction to `DateField`, and so wanted to remove the current repetition before adding the new feature.
By running existing tests.
=> refactor: Re-implement date presence & absence with FilterInstructions

CODE_OF_CONDUCT.md, CONTRIBUTING.md, docs/README.md, mdsnippets.json
Add configuration for [mdsnippts](https://github.com/simonCropp/MarkdownSnippets).
Add machine-generated tables of contents to:
- docs/README.md
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
The commands used to update those files where:
```bash
mdsnippets && git add --renormalize . && yarn run lint:markdown
```
1. mdsnippets expands a `toc` line, or updates a toc list of present
2. The git renormalize command is needed because currently mdsnippets converts .md files on Mac to `CRLF` eols
3. The lint:markdown command is to convert the `*` bullets in the toc to `-` ones.
It's much easier to read this documents when you can see in advance what the contents are.
GitHub does now add a drop-down contents list, but it's much more convenient to have the contents shown at the top.
Later on, I will:
- …
=> chore: Use mdsnippets to add table of content to contributor docs

docs/how-to/show-tasks-in-calendar.md
Provide a link to the amazing [Obsidian-Tasks-Calendar](https://github.com/702573N/Obsidian-Tasks-Calendar).
There have been several requests to show tasks in a calendar. @702573N has provided a way to do this - thank you!
By generating the docs locally.
=> docs: Add 'How to show tasks in a calendar' page.

docs/getting-started/dates.md, docs/queries/filters.md
Improve the documentation on finding tasks with invalid dates
Make it easier for users to find invalid dates - and also to safely fix them.
Viewing the docs locally.
=> docs: Improve docs on finding invalid dates

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yaml
This is part of migrating to use Issues instead of Discussions/Ideas to log feature requests.
Credit for the source of the form:
https://github.com/DuongJs/uptime-kuma-GUxd/blob/b22176d218afd1337387bfeef9fd3d3c98358bb1/.github/ISSUE_TEMPLATE/feature_request.yaml
Licence:  MIT
See https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1168
Can't be tested until merged.
=> chore: Add 'Feature Request' issue form

.github/ISSUE_TEMPLATE/feature-request.yaml
Convert duplicate-prevention checks to 2 checkboxes, so it's clear both locations need to be searched.
See https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/1168
Can't be tested until merged.
=> chore: Clearer steps for searching for duplicate issues

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml, docs/index.md
Steps (the individual commits):
-    chore: Sort existing Issues by votes, for better visibility
-    chore: Sort existing Issues by number of comments, for better visibility
-    chore: Suggest using Label filters to help with search
-    chore: Require checking for duplicate issues before new report
-    docs: Point requesters to the new issue forms
-    docs: Improve the support links in docs front page
- Improve the wording of the links
- Fix type on Q&A anchor text
- Add a link to Show and Tell
This improves on #1292 and #1293.
The docs changes were tested in a local docker build of the docs.
The Issue Forms cannot be tested until after the merge.
=> chore: more improvements to feedback forms

src/Config/SettingsTab.ts
Major clarifications to the wording and style of the settings 
Fixes #736
Before:
After:
=> Fix clarify global filter

CONTRIBUTING.md
- Edited CONTRIBUTING.md to list the steps to remember when adding a new search filter.
- To save me and others have to work it out
By viewing in WebStorm
=> chore: Document developer steps to add a new task filter

CONTRIBUTING.md
Update the list of steps for doing a release, to match the current process.
Document improvements made in #1194.
By previewing the changes in WebStorm.
=> docs: Update release steps, for changes made in #1194 - and more detail

resources/sample_vaults/Tasks-Demo/Manual Testing/SlrVb's Alternative Checkboxes.md
Update a path name in tasks block in `resources/sample_vaults/Tasks-Demo/Manual Testing/SlrVb's Alternative Checkboxes.md`
Fixes #1318
In Obsidian
Not applicable
=> vault: Fix testing of task results in 'SlrVb's Alternative Checkboxes.md

src/Query/Query.ts, src/Query/Sort.ts, tests/Query.test.ts, tests/Sort.test.ts
A series of safe refactorings to convert this:
```ts
// In Query.ts
type Sorting = {
property: SortingProperty;
reverse: boolean;
propertyInstance: number;
};
```
in to this:
```ts
// In Sort.ts
export class Sorting {
public readonly property: SortingProperty;
public readonly comparator: Comparator;
public readonly reverse: boolean;
public readonly propertyInstance: number;
constructor(property: SortingProperty, reverse: boolean, propertyInstance: number) {
this.property = property;
this.reverse = reverse;
this.propertyInstance = propertyInstance;
this.comparator = this.makeComparator();
}
public makeComparator() {
const comparator = Sort.comparators[this.property];
return this.reverse ? Sort.makeReversedComparator(comparator) : comparator;
}
}
```
A side-effect is that test code that …
=> refactor: Convert Sorting from alias to class, to store comparator

docs/queries/sorting.md
Group sorting options by area in the docs - because the list had become quite long. The order mirrors that used in grouping.md.
Also changed numbered lists so new items can be added without updating all the later numbers.
Easier maintenance and readability, and nicer diffs.
Plus I am about to add a load more sort options.
Viewing the docs locally.
=> docs: Group sorting options by area

src/Query/Filter/DateField.ts, src/Query/Filter/DescriptionField.ts, src/Query/Filter/Field.ts, src/Query/Filter/HappensDateField.ts, src/Query/Filter/PathField.ts, src/Query/Filter/PriorityField.ts, src/Query/Filter/StatusField.ts, src/Query/Filter/TagsField.ts, src/Query/Filter/TextField.ts, src/Query/Filter/UrgencyField.ts, src/Query/FilterParser.ts, src/Query/Query.ts, src/Query/Sort.ts, src/Query/Sorter.ts, tests/CustomMatchers/CustomMatchersForSorting.ts, tests/Query/Filter/DescriptionField.test.ts, tests/Query/Filter/Field.test.ts, tests/Sort.test.ts
- Rename `Sorting` to `Sorter` - and update various variable names to match
- Rename `Query.parseSortBy2()` to `parseSortBy()` now the original `parseSortBy()` method has gone
- Simplified some code
- Addressed some TODOs left over from recent refactoring of the `sort by` code.
Just tidying up.
Lots of running of tests.
=> refactor: Rename Sorting to Sorter - and minor tidying

src/Query/Filter/TagsField.ts, tests/Query/Filter/TagsField.test.ts
Make 'sort by tag' ignore capitalisation
Fixes #1438.
Updating unit tests.
Once this PR has built the plugin, I will test it manually as well.
**Before**
**After**
=> fix: Make 'sort by tag' ignore capitalisation

src/Commands/CreateOrEditTaskParser.ts, src/Query/Filter/StatusField.ts, src/Status.ts, src/Task.ts, src/TaskLineRenderer.ts, src/ui/EditTask.svelte, tests/Query.test.ts, tests/Query/Filter/StatusField.test.ts, tests/Task.test.ts, tests/TestingTools/TaskBuilder.test.ts, tests/TestingTools/TaskBuilder.ts
Move Status out to its own file.
Preparation for making Status a class.
Running the tests.
=> refactor: Move Status class out to its own file

src/ui/EditTask.svelte
Adds a new Status drop-down in the Edit modal.
Features that will be implemented in future:
- Handling of status characters not known to the Tasks plugin
- Making the 'Completed' checkbox be 'on' if the status character is `X` (capital X)
- When switching between Completed and Not-completed, add or remove the 'Done on' date
- Allow user to edit the 'Done on' date
**Credit**: This is a copy of code in @sytone's fork https://github.com/sytone/obsidian-tasks-x on its `main-tasks-sql` branch.
The revision copied from is:
https://github.com/sytone/obsidian-tasks-x/commit/2c0b659457cc80806ff18585c955496c76861b87
Co-Authored-By: Sytone <1399443+sytone@users.noreply.github.com>
Partial implementation of #1301 - and likely a number of others too.
Before-and-after images:
=> feat: ‘Create or edit Task’ modal supports custom task statuses

README.md
There was some feedback a while ago that the README didn't tell people how to run a search.
And also I noticed that the notes for developers would benefit from a link to CONTRIBUTING.
Just a small improvement.
Viewing it in Obsidian, including the Tasks block.
=> docs: Improve README.md, for new users and devs

src/Config/CustomStatusModal.ts, src/Config/SettingsTab.ts, src/Config/StatusSettingsHelpers.ts
Divide up the long method `SettingsTab.insertTaskStatusSettings()` into smaller functions that are:
- easier to read
- easier to reason about
- possible to re-use (later on)
- possible to write tests for
- possible to machine-generate documentation from (in the case of the Minimal and ITS theme information)
Main changes:
- `CustomStatusModal.statusConfiguration()` added, to simplify code in  `SettingsTab.insertTaskStatusSettings()`
- New file created: `StatusSettingsHelpers.ts` - which contains no Obsidian code.
I want to be able to make some changes to the settings for editing custom task statuses, including re-using some of its code.
I would also like later to write some tests and machine-generate some user documentation about the available statuses.
So I just explored dividing it up in …
=> refactor: Divide up status settings code

src/Commands/ToggleDone.ts, src/Recurrence.ts, src/Status.ts, src/ui/EditTask.svelte
Fix a few warnings.
https://forum.codequalitychallenge.com/t/day-3-get-rid-of-a-warning/1462
By running the plugin locally.
=> refactor: Fix a few warnings

.github/workflows/verify-on-windows.yml
Add GitHub Action to build and test the project on Windows.
It runs weekly via cron, and also on demand.
Mainly I would like to be confident that this project does build on windows, so if anyone comes along and develops a PR on Windows they will start with a working build. 
It ran fine a few months ago. I will test it once merged.
=> chore: New GitHub Action: 'Verify Build on Windows'

src/Cache.ts
1. Prevent Tasks getting stuck 'Loading Tasks...'
2. Also add a help message to users if other file-reading issues occur in future, so that if there are similar problems again, we should get useful bug reports.
Obsidian CachedMetadata was telling us that there is a task on lineNumber, but there are not that many lines in the file.
This was the underlying cause of all the 'Stuck on "Loading Tasks..."' messages, as it resulted in the line 'undefined' being parsed.
Somehow the file had been shortened whilst Obsidian was closed, meaning that when Obsidian started up, it got the new file content, but still had the old cached data about locations of list items in the file.
By luck, in a couple of hours of experimenting with the Obsidian startup code, adding more and more debug output, I was …
=> fix: Prevent Tasks getting stuck 'Loading Tasks...'

docs/getting-started/statuses.md, docs/how-to/set-up-custom-statuses.md, tests/DocsSamplesForStatuses.test.DefaultStatuses_core-statuses.approved.md, tests/DocsSamplesForStatuses.test.DefaultStatuses_important-cycle.approved.md, tests/DocsSamplesForStatuses.test.DefaultStatuses_its-theme-supported-statuses.approved.md, tests/DocsSamplesForStatuses.test.DefaultStatuses_minimal-supported-statuses.approved.md, tests/DocsSamplesForStatuses.test.Status_Transitions status-types.approved.md, tests/DocsSamplesForStatuses.test.ts
First attempt at writing up how status types currently behave.
This was partly so I can see how the different status types work in various searches.
With approval tests.
And viewing the generated docs locally.
This is how the added text renders:
=> docs: Start documenting status types

LICENSE, esbuild.config.mjs
Add my name to the author list in `main.js`.
For consistency with the community store.
By doing a build
- It will appear at the top of downloaded main.js files
Not applicable
=> chore: Update author list in main.js to match community store

src/Config/CustomStatusModal.ts, src/Config/SettingsTab.ts, src/Query/Filter/DateField.ts, src/Query/Filter/HappensDateField.ts, src/Recurrence.ts, src/StatusRegistry.ts, src/Task.ts, src/lib/DateTools.ts, tests/CustomMatchers/CustomMatchersForSorting.ts, tests/StatusRegistry.test.ts, tests/lib/DateTools.test.ts
Cyclic dependencies before:
```text
Processed 85 files (1s) (11 warnings)
1) Config/Settings.ts > Config/StatusSettings.ts > StatusRegistry.ts > Task.ts
2) Config/Settings.ts > Config/StatusSettings.ts > StatusRegistry.ts > Task.ts > DateFallback.ts
3) Task.ts > DateFallback.ts
4) Task.ts > Query/Filter/DateField.ts > Query/Filter/Field.ts > Query/Filter/Filter.ts
5) Task.ts > Query/Filter/DateField.ts > Query/Filter/Field.ts > Query/Grouper.ts
6) Task.ts > Query/Filter/DateField.ts > Query/Filter/Field.ts > Query/Sorter.ts
7) Task.ts > Query/Filter/DateField.ts
8) StatusRegistry.ts > Task.ts
9) Config/Settings.ts > Config/StatusSettings.ts > StatusRegistry.ts > Task.ts > TaskLineRenderer.ts
10) Config/Settings.ts > Config/StatusSettings.ts > StatusRegistry.ts > Task.ts > …
```
=> refactor: Reduce cyclic dependencies

src/ui/EditTask.svelte
_(This replaces #1643, which I created from the wrong branch.)_
I started looking at making the Done date editable in `EditTask.svelte` and quickly found that there was a lot of duplication of `chrono.parseDate()` calls, and also that the structure of the HTML block was hard to skim-read.
So I extracted two new methods to localise the different `chrono.parseDate()` calls, and eventually managed to give all the date-parsing helper functions meaningful names.
There are now 3 date functions that differ only subtly in behaviour, but at least those bodies of code are now only in one place instead of 3 or 4.
I also added some divider comments in the HTML to show the structure of it...
This showed that I put the Status dropdown in the wrong/no div... As this is a pure refactor, I have not …
=> refactor: Remove repetition in Task modal

src/ui/EditTask.svelte, styles.css
This change prevents the user from submitting the task edit modal form unless all data in the form is valid.
This is done by disabling the "Apply" button.
User feedback is provided with a red outline of inputs that contain invalid data.
The "Apply" button has a lower opacity if disabled.
goes after #1640. ensures the user makes no accidental changes to tasks.
I've tested locally on both desktop and mobile. This change should affect only the modal.
I'm using a theme called Cyberton so that's why it looks different :)
=> feat: Add validation to edit tasks modal

src/Query/Filter/DateField.ts, src/Query/Filter/DoneDateField.ts, src/Query/Filter/DueDateField.ts, src/Query/Filter/HappensDateField.ts, src/Query/Filter/ScheduledDateField.ts, src/Query/Filter/StartDateField.ts
`DateField` and classes extending it have duplicated code related to regular expressions used to build filters from the query. This PR is removing those redundancies and concentrates the logic in `DateField` class.
No new functionalities have been introduced.
There will be a need to introduce a change in the logic in DateField class however doing that requires first to refactor its code. Needed for https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1613
Regular unit tests.
=> refactor: regexp code in DateField and inherited classes

src/File.ts
Show a notice to user if there are any problems toggling a task.
Previously, problems were only shown in the console, which most users won't see.
To make any issues visible to users.
I will be eliminating a lot of the problem cases soon.
Locally, in the test vault.
=> feat: Show notice if there's a problem toggling task

resources/sample_vaults/Tasks-Demo/.obsidian/snippets/tasks-code-block-blue-border.css, resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin - Debug View.md, resources/sample_vaults/Tasks-Demo/Manual Testing/Task Toggling Scenarios/1680 - Reading Mode line numbers not updated on editing.md, resources/sample_vaults/Tasks-Demo/Manual Testing/Task Toggling Scenarios/Embed File in to Note - File to Embed.md, resources/sample_vaults/Tasks-Demo/Manual Testing/Task Toggling Scenarios/Embed File in to Note.md, resources/sample_vaults/Tasks-Demo/Manual Testing/Task Toggling Scenarios/Embed Task in to Note.md, resources/sample_vaults/Tasks-Demo/Manual Testing/Task Toggling Scenarios/Reading Mode line numbers in blockquotes.md, resources/sample_vaults/Tasks-Demo/Manual Testing/Task Toggling Scenarios/Reading Mode line numbers in callouts.md
Add files to `Tasks-Demo` vault:
- `.obsidian/snippets/tasks-code-block-blue-border.css`
- So it's easy to visually distinguish tasks in Tasks code blocks from other tasks
- `Manual Testing/Smoke Testing the Tasks Plugin - Debug View.md`
- So it's easy to see the detailed data in Tasks objects during smoke testing
And these, each of which is for testing a single task-toggling scenario:
- `Manual Testing/Task Toggling Scenarios/1680 - Reading Mode line numbers not updated on editing.md`
- `Manual Testing/Task Toggling Scenarios/Embed File in to Note.md`
- `Manual Testing/Task Toggling Scenarios/Embed File in to Note - File to Embed.md`
- `Manual Testing/Task Toggling Scenarios/Embed Task in to Note.md`
- `Manual Testing/Task Toggling Scenarios/Reading Mode line numbers in blockquotes.md`
- …
=> vault: Enable detailed manual testing of toggling

docs/getting-started/create-or-edit-task.md
Fix a broken link I created in #1752
In a docker build of the docs.
=> docs: Fix a broken link I created in #1752

docs/queries/examples.md
Following #1734 , add some examples in the doc.
=> docs: add date range examples

jest.config.js, package.json, svelte.config.js, tests/EditTask.test.ts, yarn.lock
This PR adds 3 dev dependencies  and some configuration to enable unit tests for Svelte components. 
It also adds 2 example tests for the `EditForm` component.
Tests referencing any code with a direct or indirect dependency on `EditForm` wouldn't compile.
Unit tests.
=> chore: Configure jest to work with Svelte components.

src/ui/EditTask.svelte, styles.css
Adds some usability improvements to the EditTask form:
- changes input field for `Description` to resizable `TextArea`, with line breaks disabled and current Enter behavior restored through custom event handler. Paste and drop events are also handled to remove any line breaks.
- adds access key `u` to `Status`
- disables submitting the form if the `Description` is empty
Fixes #1761
Improve usability of EditTask form.
Test vault.
=> feat: ‘Create or edit Task’ Modal usability improvements

contributing/Building/About Building.md, contributing/Building/Developing with WebStorm.md
I recently learned how to make WebStorm ignore `main.js` in the root of the repo, which really speeds up refactorings.
So I decided to write down the other things I do, to streamline Tasks development with WebStorm.
As above.
Viewing the page in Obsidian locally.
=> contrib: Add tips for developing Tasks with WebStorm

contributing/Documentation/Linking to other pages in the docs.md, docs/.obsidian/snippets/publish-simulation.css, docs/Advanced/Daily Agenda.md, docs/Advanced/Notifications.md, docs/Advanced/Quickadd.md, docs/Advanced/Styling.md, docs/Advanced/Tasks Api.md, docs/How To/How to get tasks in current file.md, docs/How To/How to style backlinks.md, docs/How To/Show tasks in a calendar.md, docs/How To/Style custom statuses.md, docs/Other Plugins/Dataview.md, docs/publish.css
In 60a0ce65a52ed4ae714a6ef37f8ca64a7d17a43f I added some tags to some pages, to provide clickable links to related pages.
In this PR:
-  I give navigation tags some styling
- and update the Contributing guide to [show how to use tags for navigation](https://publish.obsidian.md/tasks-contributing/Documentation/Linking+to+other+pages+in+the+docs)
Quicker navigation
Viewing the published docs
=> docs: Use tags to link to related pages

src/Query/DateParser.ts, src/Query/DateRange.ts, src/Query/Filter/DateField.ts, tests/Query/DateParser.test.ts, tests/Query/DateRange.test.ts
For further development of filters with date range, there is a need to refactor the current code and extract a `DateRange` class for easier manipulation.
Dealing with `[moment.Moment, moment.Moment]` is damaging code readability.
Unit tests. Pure refactor.
=> refactor: date range abstraction

.github/ISSUE_TEMPLATE/bug-report.yaml, docsv2/bug-reports.md
This page could be the foundation for documentation about how to interact with the maintainer of the project.
Not sure the location is good, but maybe the text itself already helps.
I checked in my local Obsidian instance only.
=> docs: Add info about support requirements

src/Query/Filter/FilenameField.ts, src/Query/Filter/HeadingField.ts, src/Query/Filter/MultiTextField.ts, src/Query/Filter/PathField.ts, src/Query/Filter/PriorityField.ts, src/Query/Filter/RecurrenceField.ts, src/Query/Filter/RecurringField.ts, src/Query/Filter/StatusField.ts, src/Query/Filter/TagsField.ts, src/Query/FilterParser.ts, src/Query/Group.ts, src/Query/Grouper.ts, src/Query/Query.ts, tests/DocsSamplesForStatuses.test.ts, tests/Group.test.ts, tests/Query/Filter/FilenameField.test.ts, tests/Query/Filter/HeadingField.test.ts, tests/Query/Filter/PathField.test.ts, tests/Query/Filter/PriorityField.test.ts, tests/Query/Filter/RecurrenceField.test.ts, tests/Query/Filter/RecurringField.test.ts, tests/Query/Filter/StatusField.test.ts, tests/Query/Filter/TagsField.test.ts
Refactor the existing `*Field` classes to use the new grouping abstraction. Continuation of #1870
Part of #920 
=> refactor: existing *Field grouping migration to new grouping

src/QueryRenderer.ts
Just a small refactor noticed during our pairing session.
Breaking the code has shown that there is no unit test for this, so I tested by making a query with 3 different `group by...` instructions in my vault and checked the rendering.
=> refactor: addgroupheading() refactoring

src/Query/TaskGroup.ts, src/Query/TaskGroups.ts
I know we didn’t discuss this and I have another PR open for proposal, still hope it will be fine for you as they don’t overlap.
I’d like to propose this PR as a clean up for the `TaskGroups` constructor class that makes it a bit more clear what is happening.
Nothing new, existing tests shall be enough.
=> refactor: Clean up TaskGroups constructor

docs/Queries/Limiting.md, src/Query/Query.ts, src/Query/TaskGroup.ts, src/Query/TaskGroups.ts, tests/Query.test.ts, tests/TaskGroups.test.ts
Add `limit groups <number>` & `limit groups to <number> tasks` instructions.
Fixes #1674 , implementation of limitation of tasks in groups.
New unit tests added.
=> feat: Add 'limit groups to <number> tasks'

src/Query/Filter/Field.ts, src/Query/Grouper.ts
Trivia: Copy in a couple of tiny additions from my fork, to prevent them from being lost due to conflicts, when I shortly merge `main` in to my personal development branches.
=> jsdoc,comment: Copy 2 tiny additions from my fork

src/InlineRenderer.ts, src/QueryRenderer.ts, src/TaskLineRenderer.ts, tests/TaskLineRenderer.test.ts
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1951.
A log spam that starts in 1.3.0 due to an API change.
Users switching to 1.3.0 will be spammed in their Developer Console with hundreds or thousands of errors.
1. Manual test that the error is gone.
2. A fix to the tests.
=> fix: prevent Obsidian 1.3.0 log spam

package.json, tsconfig.json, yarn.lock
Bump typescript from `4.7.4` to `5.0.4`
And fully update other typescript dependencies.
See the diffs in `package.json` for details of other package version changes.
This replaces dependabot PR #1843.
Also temporarily added the following to `compilerOptions`:
```
"ignoreDeprecations": "5.0"
```
in order to silence these messages:
```
error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
Use 'verbatimModuleSyntax' instead.
error TS5101: Option 'preserveValueImports' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
Use 'verbatimModuleSyntax' instead.
```
Trying to get through a …
=> chore(deps-dev): bump typescript from 4.7.4 to 5.0.4

contributing/Code/How do I use Moment in src.md, contributing/Testing/How do I use Moment in tests.md, src/DateFallback.ts, src/Query/DateParser.ts, src/Query/DateRange.ts, src/Recurrence.ts, src/lib/logging.ts, tests/EditTask.test.ts, tests/Integration/MomentIntegration.test.ts, tests/Query/DateParser.test.ts, tests/Query/DateRange.test.ts, tests/Recurrence.test.ts, tests/Task.test.ts, tests/lib/DateTools.test.ts
This fixes code in `src/` to use `moment` and `Moment` correctly, ensuring that the version provided by Obsidian is used, saving us from bundling it in `main.js`.
It reduces main.js for release by about 60kb:
- `from 442.1kb`
- `to   382.5kb`
I have also added two new pages to the Contributing Guide, recording the correct use of moment:
- https://publish.obsidian.md/tasks-contributing/Code/How+do+I+use+Moment+in+src
- https://publish.obsidian.md/tasks-contributing/Testing/How+do+I+use+Moment+in+tests
This fixes #1849.
- By running the existing tests
=> fix: Stop bundling Moment in release

tests/Query/Filter/BacklinkField.test.ts, tests/Query/Filter/CreatedDateField.test.ts, tests/Query/Filter/DoneDateField.test.ts, tests/Query/Filter/DueDateField.test.ts, tests/Query/Filter/FilenameField.test.ts, tests/Query/Filter/FolderField.test.ts, tests/Query/Filter/HappensDateField.test.ts, tests/Query/Filter/HeadingField.test.ts, tests/Query/Filter/PathField.test.ts, tests/Query/Filter/PriorityField.test.ts, tests/Query/Filter/RecurrenceField.test.ts, tests/Query/Filter/RecurringField.test.ts, tests/Query/Filter/RootField.test.ts, tests/Query/Filter/ScheduledDateField.test.ts, tests/Query/Filter/StartDateField.test.ts, tests/Query/Filter/StatusField.test.ts, tests/Query/Filter/StatusNameField.test.ts, tests/Query/Filter/StatusTypeField.test.ts, tests/Query/Filter/TagsField.test.ts, tests/Query/Filter/UrgencyField.test.ts, tests/TaskSerializer/DocsSamplesForTaskFormats.test.ts, tests/TestHelpers.ts
Test group headings order for fields:
- `Due`
- `Done`
- `Start`
- `Scheduled`
- `Created`
- `Happens`
- `Recurrence`
- `Recurring`
-  `Path`
- `Root`
- `Backlink`
- `Folder`
- `Filename`
- `StatusType`
Following #1999 , add test for the rest of the fields.
=> test: add group sort order tests

src/Config/GlobalFilter.ts, src/TaskLineRenderer.ts, tests/GlobalFilter.test.ts, tests/TaskLineRenderer.test.ts
When Global Filter removal option is enabled, it was removed as a substring for query rendering.
This makes Global Filter being removed as a word.
Fixes #2021 .
Unit test: new test to show the fix added.
Smoke test on the Tasks demo vault (Screenshots below).
Before
After
=> fix: 'remove global filter' broke display of sub-tags of global filter

src/TaskLineRenderer.ts
Call `priorityNameUsingNormal()` instead of clunky `if-else` statements.
Reuse existing methods, remove static values.
Tests in `TaskLineRenderer.test.ts` shall be enough. Tried also to break the code by putting wrong values in `priorityNameUsingNormal()` output (All broken but `Highest` and `Lowest` broken, which makes sense as they have been added recently.
=> refactor: use PriorityTools in TaskLineRenderer.ts

tests/Task.test.ts
Update call from `Settings` to `GlobalFilter` dedicated API.
Use existing API which is used everywhere in the code.
Unit test.
=> test: use call GlobalFilter.set()

docs/Queries/Grouping.md, docs/Scripting/Task Properties.md, src/Task.ts, tests/Scripting/TaskProperties.test.task_other_fields.approved.md, tests/Scripting/TaskProperties.test.ts, tests/Scripting/TaskPropertyExamples.test.custom_grouping_by_task.descriptionWithoutTags_docs.approved.md, tests/Scripting/TaskPropertyExamples.test.custom_grouping_by_task.descriptionWithoutTags_results.approved.txt, tests/Scripting/TaskPropertyExamples.test.custom_grouping_by_task.description_results.approved.txt, tests/Scripting/TaskPropertyExamples.test.ts
This takes advantage of code that @ilandikov created in #2076, and makes it available to users for custom grouping with the property `task.descriptionWithoutTags` such as:
```
group by function task.descriptionWithoutTags
```
I was first going to add this to this docs:
```
group by function task.description.replace(/(^|\s)#[^ !@#$%^&*(),.?":{}|<>]*/g, '')
```
and then decided it was kinder to users to provide `task.descriptionWithoutTags` instead!
- By adding tests (at the `TaskProperties` level, for inclusion in the docs)
- By testing manually in the demo vault
=> feat: Add 'task.descriptionWithoutTags' for 'group by function'

src/Query/Filter/TextField.ts, src/Query/Matchers/IStringMatcher.ts, src/Query/Matchers/RegexMatcher.ts, src/Query/Matchers/SubstringMatcher.ts, tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt, tests/Query/Filter/TextField.test.ts
This adds information to the explanation of `regex matches` and `regex does not match` queries, to show how the regular expression is interpreted.
Example output:
```
description regex matches /^$/ =>
using regex:            '^$' with no flags
description regex matches /#context/pc_photos|#context/pc_clare|#context/pc_macbook/i =>
using regex:            '#context' with no flags
description regex matches /#context\/pc_photos|#context\/pc_clare|#context\/pc_macbook/i =>
using regex:            '#context\/pc_photos|#context\/pc_clare|#context\/pc_macbook' with flag 'i'
description regex matches /[⏫🔼🔽📅⏳🛫🔁]/u =>
using regex:            '[⏫🔼🔽📅⏳🛫🔁]' with no flags
folder regex matches /root/sub-folder/sub-sub-folder/ =>
using regex:       'root' with no flags
folder regex matches …
```
=> feat: explain now shows regex interpretation

src/Task.ts, tests/Query/Filter/TagsField.test.ts, tests/Task.test.ts
Single # symbols in task lines are no longer treated as tags.
Now we require a tag to have at least one character after the #.
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1969
- Adding new tests in Tag-parsing and `group by tag` code. These failed before the bug was fixed.
- Manual exploratory testing in the demo vault.
=> fix: Single # symbol in task line no longer treated as a tag

src/Cache.ts, src/LivePreviewExtension.ts, src/QueryRenderer.ts
This is an interim workaround for https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2160
The following outputs have been disabled. A customisable option will be provided later.
The messages removed are:
```
At least one task, its line number or its heading has changed in ${file.path}: 
riggering a refresh of all active Tasks blocks in Live Preview and Reading mode views.
Render ${this.queryType} called for a block in active file "${this.filePath}",
to select from ${tasks.length} tasks: plugin state: ${state}
${totalTasksCount} of ${tasks.length} tasks displayed in a block in "${this.filePath}"
Live Preview Extension: toggle called. Position: ${position} Line: ${line.text}
```
The [Logstravaganza](https://github.com/czottmann/obsidian-logstravaganza) plugin is useful for user …
=> fix: Remove verbose debug console output

src/TaskLineRenderer.ts
A pure refactoring, guided by @ilandikov.
We experimented with using [Arlo's Commit Notation](https://github.com/LarsEckart/tcr-extension/blob/main/src/test/java/com/larseckart/tcr/ArloGitNotationPromptTest.testVersion2.Mac_OS_X.approved.png) to indicate which changes were:
- `.` pure, automated refactorings, sometimes with a formatting quick fix  - 'probable'
- `-` tested - we did a single step by hand, and confirmed that test coverage would have detected any errors
- `@` other - when we split a switch statement, and there was no automated refactoring to do it.
To make the responsibilities of the code easier to understand.
- By running the tests repeatedly
- And by intentionally breaking the code to ensure that we had test coverage at various stages
=> refactor: split getComponentClassesAndData() in to 2 functions

src/TaskLayout.ts
Remove an unused optional parameter.
Remove unused code.
Unit tests, however can't test unused code.
=> refactor: remove unused parameter from `TaskLayout` constructor

.gitignore, tsconfig.json
Make `tsc` (TypeScript compiler) put any generated files in `generated/` directory, which is now git-ignored.
This either stops, or reduces, WebStorm giving this message as a 'Project Error'
tsconfig.json:
TS5055: Cannot write file '.../obsidian-tasks/tests/global-setup.js' because it would overwrite input file.
(which in turn makes it easier to miss other errors straight away.)
Fixes #1986.
- #1986
By restarting WebStorm and confirming the warning went away.
=> chore: Fix error TS5055: Cannot write file ...tests/global-setup.js

src/Config/Settings.ts
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2278 - which was introduced in #2215.
Fix the increase in cyclic dependencies from 
This fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2278 - see the comments in that issue.
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2278 fixed
With madge. See instructions in the linked issue.
=> refactor: Remove recently-added cyclic dependencies.

package.json
Specify that the plugin only supports node.js 16.x and up
_Edit: It turned out that 17.x isn't supported, so in the end the PR does:_
_"^16.10.0 || >=18.0.0"_
Obsidian tasks does not support older versions of nodejs and the tests do not pass with them. Specify the supported version of node in package.json to ensure that contributors are running with an up to date version of node.js
docs: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
One thing I'm not sure about is if we should set an upper bound, e.g. add `<17.0.0` to the version constraint.
Also I'm not entirely sure how this will affect running the plugin in Obsidian, but I'd expect that the version of node.js used to be greater than 16.x so it should probably be okay.
After pulling the latest changes I had errors …
=> chore: Specify supported node versions in package.json

src/ui/EditTask.svelte
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/1814. Reccurence can silently fail if user has forgotten to add a date to the task
Manual testing of the modal in a test vault
=> fix: Edit Task modal warns if no date set for recurrence

contributing/.obsidian/snippets/publish-simulation.css, contributing/publish.css, docs/.obsidian/snippets/publish-simulation.css, docs/Getting Started/Create or edit Task.md, docs/Getting Started/Getting Started.md, docs/Getting Started/Tags.md, docs/Getting Started/Use Filename as Default Date.md, docs/Introduction.md, docs/Reference/Task Formats/Tasks Emoji Format.md, docs/Support and Help/About Support and Help.md, docs/Support and Help/Known Limitations.md, docs/_meta/templates/we are tracking this in discussion.md, docs/publish.css
- Add a new documentation page `Known Limitations`
- It embeds 'Limitations'-type sections from other pages, to make lists of limitations more discoverable.
- Improve the content in a number of 'Limitations' sections, including:
- Add more sub-headings, so that words like `canvas` and `blockquote` appear in the Search on published docs site
- Add more links to GitHub Issues and Discussions
- Note some more limitations
- Update the `publish.css` and `publish-simulation.css` pages on both docs vaults
- To make embedded content look more like ordinary content.
- Added a new template: `we are tracking this in discussion.md`
- To make Search on the published site find some more common search terms
- To help users find issues earlier
- To enable me to find and link to known issues more quickly, …
=> docs: Add new page 'Known Limitations'

src/Query/Scanner.ts, tests/Scanner.test.ts
A pure refactoring, done by incrementally re-implementing in a temporary new function until the behaviour exactly matched that with the original regex.
In effect, this can be seen as dividing up the previous regular expression in to smaller chunks, so we have more control over the behaviour.
See [this comment](https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2330#discussion_r1359884999).
This is preparation for implementing the original behaviour of recognising double-backslash as special case, without the need for lookbehind regexes, which don't work in Obsidian on iPhones.
Using the existing tests.
=> refactor: Divide up regex in line continuation code

docs/Introduction.md, docs/Support and Help/About Support and Help.md, docs/Support and Help/Breaking Changes.md
Add a new documentation page that links to all the documentation about breaking changes..
Sometimes people report "bugs" that turn out to be because they are using a very old version of tasks - and I have to tell them to check the release notes for all the major versions they will be updating past.
Now I will be able to send them a single link.
Viewing the docs in Obsidian.
=> docs: Add new help page 'Breaking Changes'

docs/Queries/Explaining Queries.md, docs/Scripting/Expressions.md, tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.query.text, tests/Query/Explain/DocsSamplesForExplain.test.ts, tests/Scripting/Expression.test.Expression_returns_and_functions.approved.md, tests/Scripting/Expression.test.ts
Pulling in a few improvements to pre-existing documentation that I made whilst reviewing #2330.
- Improve readability of some long lines in documentation
- Advertise the line continuation characters facility
- The documentation samples are all executed in tests to ensure they are correct
- All changes viewed in Obsidian
=> docs: Advertise line continuation characters in docs

resources/sample_vaults/Tasks-Demo/.obsidian/plugins/obsidian-tasks-plugin/data.json, src/Config/Settings.ts, src/Query/Query.ts, src/lib/logging.ts, src/main.ts
Copy in some logging-related code from #1851.
Credit given to @sytone in each commit.
Wish to start using the logging code in production code.
This connects up the logging work started in #969.
By running the code in my local build.
=> feat: Enable logging configuration

src/Cache.ts, src/Config/Settings.ts, src/File.ts, src/IQuery.ts, src/Query/Query.ts, src/QueryRenderer.ts, src/Task.ts, src/TasksEvents.ts, tests/Config/Settings.test.ts
Add some systematic debug logging of Tasks behaviour.
To turn this debug output on:
1. Run a new build of Tasks
2. Open Tasks Settings - this will add some new settings values to `.obsidian/plugins/obsidian-tasks-plugin/data.json`
3. Quit Obsidian
4. Edit the `loggingOptions` values: change `info` to one of the `ILogLevel` names in [src/lib/logging.ts](https://github.com/obsidian-tasks-group/obsidian-tasks/blob/main/src/lib/logging.ts) - in this case, change to `debug` to turn on the new debug output
5. Restart Obsidian and show the developer console
6. On mobile, the [Logstravaganza](https://github.com/czottmann/obsidian-logstravaganza) plugin may help - it should be enabled before Tasks is turned on.
I am unsure whether to document this, at this stage: it shows up some really obvious …
=> feat: Add optional debug logging of searches and file handling

docs/Getting Started/Statuses/Recurring Tasks and Custom Statuses.md, src/StatusRegistryReport.ts, src/StatusSettingsReport.ts, tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md, tests/StatusSettingsReport.test.StatusSettingsReport_should_include_problems_in_table.approved.md, tests/StatusSettingsReport.test.StatusSettingsReport_should_tabulate_StatusSettings.approved.md, tests/StatusSettingsReport.test.ts
Added an extra column to "Review and check your Statuses" report, that shows things worth investigating.
- To help with user support.
- Manually in the demo vault
- In new tests
This is the report that's generated in Unit Tests, with a variety of problem data cases:
=> feat: "Review and check your Statuses" now shows any problems

docs/Getting Started/Statuses/Example Statuses.md, docs/Getting Started/Statuses/Recurring Tasks and Custom Statuses.md, src/StatusRegistry.ts, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_core-statuses.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_custom-statuses.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled-with-unconventional-symbols.approved.detailed.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_done-toggles-to-cancelled.approved.detailed.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_important-cycle.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_pro-con-cycle.approved.detailed.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_pro-con-cycle.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_todo-in_progress-done.approved.detailed.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_todo-in_progress-done.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.DefaultStatuses_toggle-does-nothing.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_AnuPpuccin_Table.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Aura_Table.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Ebullientworks_Table.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_ITS_Table.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_LYT_Mode_Table.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Minimal_Table.approved.mermaid.md, tests/DocumentationSamples/DocsSamplesForStatuses.test.Theme_Things_Table.approved.mermaid.md, tests/StatusRegistry.test.ts, tests/StatusRegistryReport.test.StatusRegistryReport_should_create_a_report.approved.md
Colour-code the Mermaid status diagrams so they are easier to read.
These colours are also visible in some of the documentation pages now.
See #2386 for details and motivation.
Fixes #2386.
- With existing tests
- By testing in the Demo Vault
I chose the shades of colour so that they look reasonably good in dark mode too:
=> feat: Colour-code the Mermaid status diagrams for readability

tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html, tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html, tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_full_mode.approved.html, tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_short_mode.approved.html, tests/TaskLineRenderer.test.ts
Add test to visualise any changes in task's CSS classes and data attributes.
Improve tests for safer refactorings.
Approval tests.
=> test: add task rendering HTML approval tests

yarn.lock
bump svelte from 3.59.1 to 3.59.2
bump svelte-check from 3.4.6 to 3.6.0
bump svelte-preprocess from 5.0.4 to 5.1.0
Make the latest minor updates to svelte tools.
Done by running the following, and selecting all svelte lines for updating, then linting, testing, and running the plugin.
```bash
yarn upgrade-interactive 
```
Trying to keep on top of dependencies.
- Checking that the Edit Task modal still works.
=> build(deps-dev): bump svelte, svelte-check and svelte-preprocess

yarn.lock
Make the latest minor updates to eslint dependencies.
```
bump @typescript-eslint/eslint-plugin   from 5.59.8 to 5.62.0
bump @typescript-eslint/parser          from 5.59.8 to 5.62.0
bump eslint                             from 8.41.0 to 8.54.0
bump eslint-config-prettier             from 8.8.0 to 8.10.0
bump eslint-plugin-import               from 2.27.5 to 2.29.0
```
Done by running the following, and selecting all eslint lines for updating, then linting, testing, and running the plugin - and smoke testing.
```bash
yarn upgrade-interactive 
```
Trying to keep on top of dependencies.
- Checking that the Edit Task modal still works.
=> build(deps-dev): Various eslint dependencies

yarn.lock
Make the latest minor updates to jest dependencies.
```
bump @testing-library/jest-dom from 5.16.5 to 5.17.0
bump jest-environment-jsdom    from 29.5.0 to 29.7.0
```
Done by running the following, and selecting all jest lines for updating, then linting, testing.
```bash
yarn upgrade-interactive 
```
Trying to keep on top of dependencies.
=> build(deps): bump jest dependencies

src/InlineRenderer.ts, src/QueryRenderer.ts, src/TaskFieldRenderer.ts, src/TaskLineRenderer.ts, tests/TaskFieldRenderer.test.ts, tests/TaskLineRenderer.test.ts
Done by pairing with @claremacrae .
Simplify maintenance and readability.
Existing tests.
=> refactor: improve rendering code quality

docs/Queries/About Queries.md
This PR adds a small section to the documenttion that explains how query options can be added before going into details, and shows that/how task queries can be embedded in callouts.
See #2445. Task queries in callouts are currently not mentioned in the docs except in an outdated section and using Dataview.
=> docs: add example for query options and using callouts

manifest.json
Teach the new [HelpMate plugin](https://github.com/TfTHacker/obsidian42-HelpMate) to find the Tasks user documentation.
Fixes #2462
To activate (once the next version of Tasks is installed):
1. Install and enable HelpMate from the Community plugins store, and open its side-panel
2. Click its Bookmark icon to show the list of help available
3. Click on Tasks
The result:
=> feat: Add Tasks docs to the HelpMate plugin

contributing/Building/Setting up build environment.md
Fixed the following error that I had using Node 14 :
```bash
yarn
yarn install v1.22.21
[1/5] Validating package.json...
error obsidian-tasks@5.2.0: The engine "node" is incompatible with this module. Expected version "^16.10.0 || >=18.0.0". Got "14.21.3"
```
Changed Node version.
Building is using a newer version now.
Well it's text without any links. I don't suppose it needs further testing. Correct me if I'm wrong.
Versioning.
=> contrib: Update Node version in Contributing guide

resources/sample_vaults/Tasks-Demo/.obsidian/community-plugins.json, resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/data.json, resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/main.js, resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/manifest.json, resources/sample_vaults/Tasks-Demo/.obsidian/plugins/helpmate/styles.css
Install the new [HelpMate plugin](https://github.com/TfTHacker/obsidian42-HelpMate) in the Tasks-Demo vault, so the Obsidian and Tasks docs can be viewed inside that Obsidian vault.
For easy access to to the docs.
In the Tasks-Demo vault.
=> vault: Install the HelpMate plugin, to access Tasks help

src/File.ts, src/QueryRenderer.ts, src/Task.ts, src/lib/LogTasksHelper.ts
- Fix the debug output in `File.ts`
- Add consistent debug logging for toggling tasks and writing tasks
To help with debugging #2471
In the Tasks-Demo vault
Example output follows, which was created with these debug settings in `data.json`
```json
"loggingOptions": {
"minLevels": {
"": "info",
"tasks": "debug",
"tasks.Query": "debug",
"tasks.Cache": "debug",
"tasks.Events": "debug",
"tasks.File": "debug",
"tasks.Task": "debug"
}
}
```
=> fix: Debug logging in File.ts works; better logging

docs/Getting Started/Getting Started.md
This disclaimer is trying to state that "Obsidian doesn't read text in comments" => "Tasks Plugin doesn't read tasks in comments", but it's missing a negation.
n/a
It has not. I'm a first-time contributor with no local setup, just offering to fix a small typo.
(using chrome inspect tool)
=> docs: fix typo about comment tasks in getting-started

docs/Getting Started/Dates.md
=> docs: Fix typo

tests/Scripting/Postponer.test.ts, tests/Scripting/TasksDate.test.ts
- Add tests to `Postponer.createPostponedTask()`
- Add tests to `TasksDate.postpone()`
Expand test coverage for safe change of behaviour in the future.
- New unit tests added
=> test: test postponed task and date creation

src/TaskLineRenderer.ts
`document.createElement()` doesn't return falsy values so the check is always true and shall be removed.
Cleaner code.
Unit tests (breaking code).
=> refactor: remove an if that is always true in `TaskLineRenderer.ts`

src/Task.ts, src/TaskLineRenderer.ts
- added context menu appearing after right-click on the checkbox of the task, with all user-specified task statuses possible to choose
- little refactor of the Task.toggle method (by adding handleNewStatus method) so the same code could be used to handle tasks recurrence if the user chooses DONE status
Actually, I'm not sure about this refactor I mentioned - I guess there is some code in "Create or edit Task" modal after clicking "Apply" button that would have this logic of changing the status, maybe that would be better to use here. But I had some problems finding that piece of code.
I didn't wrote unit tests - I don't really see room for unit tests here, as the change is so very small? But I can of course add them if there will be suggestions what really could be unit tested here.
I …
=> feat: add "change task status" context menu

src/TaskLineRenderer.ts, src/ui/Menus/StatusMenu.ts, tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html, tests/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html, tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_full_mode.approved.html, tests/TaskLineRenderer.test.Visualise_HTML_Minimal_task_-_short_mode.approved.html, tests/__mocks__/obsidian.ts, tests/ui/Menus/StatusMenu.test.ts
- Improve the labels shown on the status menu: they now show the symbol
- Add checkmark against the current task status
- Put a tooltip on the task checkbox, to show that there are now right-click options
- Don't edit a task if it already has the current status
- Status menu no longer shows duplicate statuses, and empty statuses (created with 'Add New Task Status' and then not edited)
- Move the status menu code to new class `StatusMenu` in `src/ui/Menus/StatusMenu.ts`
- Add tests for most of the behaviour of the status menu code
- Fix some async/await warnings
- Move code out of TaskLineRenderer, as I want to add more context menus
- Add tests
- New tests
- Extensive exploratory testing
See above.
- Usability improvements
=> feat: Improve usability of Statuses context menu

src/QueryRenderer.ts, src/Scripting/Postponer.ts, tests/Scripting/Postponer.test.ts
In using the Postpone button a lot in my own vault, I really wanted to see the following, before actually postponing:
- the field name that was going to be edited (Due, Scheduled or Start)
- the new date, including the day of the week
So this experiments with new formats.
I also wanted a few more date options.
Here is what I have changed - showing the Before and After:
**Important caveat: after doing this, I realised that the new names only made sense for postponing overdue tasks. For tasks already in the future, the name Postpone is still likely better.**
See above.
Also, I'm really keen to move on and release this feature!
- New and existing tests
- Exploratory testing in the demo vault
- Much day-to-day use in my own main vault.
See above.
- But note that …
=> feature: Experimental changes to (unreleased) Postpone menu options

src/Scripting/Postponer.ts, tests/Scripting/Postponer.test.ts
Postpone scheduled dates from file name.
Fix this bug.
Unit test + exploratory test.
=> fix: can now postpone scheduled dates from file name

tests/TaskLineRenderer.test.ts
Group various tests in separate `describe()` blocks.
No tests were added or removed.
Better structure in test code to see the missing tests/coverage.
Unit tests.
=> test: group TaskLineRenderer tests

tests/TaskLineRenderer.test.ts
- Merge parameters of `testLayoutOptions()` to  have the description and other components in one parameter
Test readability.
- Unit tests.
=> test: improve `testLayoutOptions()` test function to have the expected description in one parameter with other expected components

src/StatusRegistry.ts, src/Task.ts, tests/DocumentationSamples/DocsSamplesForStatuses.test.ts, tests/StatusRegistry.test.StatusRegistry_toggling_recurring_should_make_CANCELLED_next_task_TODO.approved.md, tests/StatusRegistry.test.ts, tests/TestingTools/ApprovalTestHelpers.ts, tests/TestingTools/StatusExamples.ts, tests/TestingTools/StatusesTestHelpers.ts, tests/TestingTools/VerifyStatuses.ts
Move the new code from the following PR from `Task` to `StatusRegistry`:
- #2516
Also: 
- added some comments to explain the new recurrence status logic. The comments were kindly written by @asokawotulo in:
https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2516#discussion_r1434113802
Other changes made, in order to allow re-use of some existing test code:
- Move some existing verify functions to `tests/TestingTools/VerifyStatuses.ts`
- Also added `verifyTaskList()` and `verifyTaskListInReverseOrder()`
- Extract functions and move some code for creating sample status sets to `tests/TestingTools/StatusExamples.ts`
- Move `constructStatuses()` to `tests/TestingTools/StatusesTestHelpers.ts`
I will need to update the [When DONE is not followed by TODO or …
=> refactor: Move new status calculation for recurring tasks to StatusRegistry

docs/Introduction.md, docs/Queries/Explaining Queries.md, docs/Queries/Line Continuations.md, docs/Queries/Regular Expressions.md, docs/Scripting/Placeholders.md, src/Query/Explain/Explainer.ts, src/Query/Filter/Field.ts, src/Query/Filter/TagsField.ts, src/Query/Sorter.ts, tests/Config/DebugSettings.test.ts, tests/Query.test.ts, tests/Query/Explain/DocsSamplesForExplain.test.explain_boolean_combinations.approved.explanation.text, tests/Query/Explain/DocsSamplesForExplain.test.explain_expands_dates.approved.explanation.text, tests/Query/Explain/DocsSamplesForExplain.test.explain_explains_task_block_with_global_query_active.approved.explanation.text, tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_double_slash.approved.explanation.text, tests/Query/Explain/DocsSamplesForExplain.test.explain_line_continuation_-_single_slash.approved.explanation.text, tests/Query/Explain/DocsSamplesForExplain.test.explain_nested_boolean_combinations.approved.explanation.text, tests/Query/Explain/DocsSamplesForExplain.test.explain_placeholders.approved.explanation.text, tests/Query/Explain/DocsSamplesForExplain.test.explain_regular_expression.approved.explanation.text, tests/Query/Explain/Explainer.test.ts, tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_filters-date-examples.approved.explanation.text, tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-week-month-quarter-year.approved.explanation.text, tests/Query/Filter/ReferenceDocs/FilterReference/DateFieldReference.test.explain_date_reference_last-this-next-weekday.approved.explanation.text, tests/Query/Filter/TextField.test.explains_regular_expression_searches_bulk_test.approved.txt, tests/Sort.test.ts, tests/lib/QueryRendererHelper.test.ts
1. Make `explain` list the Query's `sort by` instructions.
2. Update the documentation
Fixes #2106.
This is part of preparation for #2074 - I want to be able to show what `sort by` instructions are in use, and test the removal of them via something like `clear sort by`.
- Via tests
- Via exploratory testing
=> feat: Make 'explain' show 'sort by' commands

tests/TaskLineRenderer.test.ts
Modify tests with `testHiddenComponentClasses()`:
- use `it.each()` to have compact and expressive tests
- use `TaskBuilder.buildFullyPopulatedTask()` to have a standard task (if it gets modified and breaking the tests, it will be seen now)
Have shorter, readable tests in `TaskLineRenderer.test.ts`
Unit tests, breaking tests.
=> test: convert tests with `testHiddenComponentClasses()` to `it.each()` & use test task from `TaskBuilder`

src/TaskModal.ts, styles.css
A few lines of css to make the modal action buttons (submit and cancel) always visible irrespective of height
#2481 - In can be annoying to have to scroll all the way to the bottom of the modal on mobile if you only want to quickly add/edit the description for example. This will be more of an issue when the task dependency inputs in the modal are merged in soon, making the modal even longer.
Manually on mac and iOS
=> feat: Make modal action buttons always visible

resources/sample_vaults/Tasks-Demo/Functions/Custom Sorting.md, src/Query/Filter/FunctionField.ts, src/Query/Query.ts, src/Query/Sort.ts, src/Query/Sorter.ts, tests/CustomMatchers/CustomMatchersForSorting.ts, tests/Query.test.ts, tests/Query/Filter/DescriptionField.test.ts, tests/Query/Filter/FunctionField.test.ts, tests/Query/Filter/TagsField.test.ts, tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.folder_docs.approved.md, tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.file_properties_task.file.folder_results.approved.txt, tests/Scripting/ScriptingReference/CustomSorting/CustomSortingExamples.test.ts, tests/Scripting/ScriptingReference/VerifyFunctionFieldSamples.ts, tests/Sort.test.ts, tests/TestingTools/SortingTestHelpers.ts
Enable `sort by function` lines to use `query.file.path` and other [Query Properties](https://publish.obsidian.md/tasks/Scripting/Query+Properties).
Desperate to get `sort by function` released!
- New tests
- New query added to demo vault to show its use.
=> feat: Enable use of Query Properties like query.file.path in 'sort by function'

docs/Queries/Filters.md, docs/Queries/Grouping.md, docs/Scripting/Custom Filters.md, docs/Scripting/Custom Grouping.md, docs/Scripting/Task Properties.md, resources/sample_vaults/Tasks-Demo/.obsidian/appearance.json, resources/sample_vaults/Tasks-Demo/Manual Testing/Invalid dates with Sorting and Grouping.md, src/Scripting/TasksDate.ts, tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.due.advanced_docs.approved.md, tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.dates_task.due.advanced_results.approved.txt, tests/Scripting/ScriptingReference/CustomFiltering/CustomFilteringExamples.test.ts, tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_docs.approved.md, tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due.advanced_results.approved.txt, tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due_docs.approved.md, tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.dates_task.due_results.approved.txt, tests/Scripting/ScriptingReference/CustomGrouping/CustomGroupingExamples.test.ts, tests/Scripting/TasksDate.test.ts
- Add a 5th category, `Invalid date` to `task.due.category` - it is number 0, so comes before all other dates in `sort by function` and `group by function` with dates.
Fixes #2592.
=> Fix undated tasks categories

docs/Queries/About Queries.md, docs/Queries/Line Continuations.md, docs/Queries/Sorting.md, docs/Scripting/Custom Grouping.md, docs/Scripting/Custom Sorting.md, docs/Scripting/Expressions.md, docs/Scripting/Query Properties.md, docs/Scripting/Task Properties.md, docs/Support and Help/Known Limitations.md
Document `sort by function`.
This completes the work started in #2577.
Viewing the documentation locally in Obsidian.
=> docs: Document custom sorting and `sort by function`

src/ui/Dependency.svelte, src/ui/EditTask.svelte, src/ui/EditableTask.ts, styles.css
- Refactored task dependency input in modal to separate svelte component
- Small simplifications to modal dependency logic
- Renamed dependency style classes to match other modal style names
Code maintainability
Manual testing of logic simplifications
=> refactor: Move task dependency input to svelte component

src/Task/Task.ts, tests/Task/Task.test.task_dependencies_blocking_and_blocked.approved.txt, tests/Task/Task.test.ts
Create methods `Task.isBlocked()` and `Task.isBlocking()`.
These will be the foundations of the dependencies-related filtering code - and will replace the current implementations of these filters:
- `is not blocked`
- `is blocking`
Their logic - see the JSdocs in new methods - arises from a circa 1.5 hour long discussion with @ilandikov yesterday, doing exploratory testing of the current filters, and how they interact with statuses.
Later these methods will be documented for use with custom searches.
A new approval test that allows visualisation of the behaviour.
=> refactor: Create Task.isBlocked() and Task.isBlocking()

.gitattributes
Added 5 file extensions, 1 file extension mask (for all `.git*` config files), and 1 file without an extension (`LICENSE`) to `.gitattributes`.
Clare pre-approved the first 4 lines, but may wish to review the last 3.
=> chore: Added more file extensions and LICENSE file to .gitattributes

tests/ui/EditInstructions/SetTaskDependenciesInstruction.test.ts
TDD `setDependencies()` with @claremacrae for future use.
Add a testable API to replace the current one.
Unit tests.
=> test: add `setDependencies()` for editing dependencies

src/Config/Settings.ts, src/Suggestor/Suggestor.ts, tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json, tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md, tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json, tests/Suggestor/Suggestor.test.ts
- Make the behaviour of the code visible in tests.
- Remove dependence of code on a global setting.
- Reduce repetition in code
Unit tests + exploratory testing.
=> refactor: add tests and refactor auto suggest

src/Task/Task.ts
Series of refactorings to reduce the complexity in `Task.handleNewStatus()`.
Preparation for working on #2654. 
- Unit tests
- Smoke tests
contributing/Documentation/About+Documentation) accordingly.
=> refactor: Reduce complexity in Task.handleNewStatus()

docs/Advanced/Daily Agenda.md
I think this hint would be helpful for some users.
Add an example of workaround that allows user to use default `Daily-notes` plugin.
If there are better ways to give out this information, please feel free to close this PR and create a new one.
It's possible to express "due before date+14d" without using `Calendar` or `Periodic Notes`, and I think it's worth mentioning
(I think it could be a good alternative for those who turns on "Open daily note on startup" option).
Previewed in Obsidian and links tested.
=> docs: Use dates other than 'today' with core Daily Notes core plugin

.eslintrc.js, package.json, src/ui/DateEditor.svelte, src/ui/Dependency.svelte, src/ui/EditTask.svelte, yarn.lock
- Add modules and configuration to make ESLint lint `*.svelte` files
- Lint the existing `.svelte` files
- Get rid of annoying error at the beginning of Svelte files (at `<script lang="ts">`)
- Make code in TypeScript in Svelte files look same as in regular TypeScript files
Not really needed since Svelte files were just listed, however I did a smoke test: edited a task with Edit Task modal and set a couple of dates successfully.
=> chore: lint Svelte files

docs/Introduction.md, docs/Queries/Combining Filters.md, docs/Support and Help/Breaking Changes.md, resources/sample_vaults/Tasks-Demo/Filters/Boolean Combinations.md
Update user documentation for changes in these PRs:
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2758
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2759
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2761
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2762
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2763
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2767
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2770
- Viewing the documentation in Obsidian
- Checking for broken links using the installed plugin
=> docs: Document many improvements to Boolean searches

contributing/Code/About Code.md, contributing/Code/Structure of the code.md
Add a new page to the Contributing site, explaining the `src/` directory structure.
Get stuff out of my head.
Viewed in Obsidian.
See https://publish.obsidian.md/tasks-contributing/Code/Structure+of+the+code
=> contrib: Document the source-code directory structure

src/ui/EditTask.scss
- Improve rendering dates & priority in Edit Task modal under 650px pixel screens
- Better UI on mobile devices
Manual test in demo vault
Screen width | Before             |  After
:-------------------------:|:-------------------------:|:-------------------------:
550px | ![Снимок экрана 2024-05-07 в 14 51 05](https://github.com/obsidian-tasks-group/obsidian-tasks/assets/93825870/56f950fb-c32b-49bb-aa76-8bf8929b6981) | ![Снимок экрана 2024-05-07 в 16 26 06](https://github.com/obsidian-tasks-group/obsidian-tasks/assets/93825870/573aad8c-ca97-4153-8b7c-ef023c08b6c7)
450px | ![Снимок экрана 2024-05-07 в 14 51 23](https://github.com/obsidian-tasks-group/obsidian-tasks/assets/93825870/f6e7c039-b0da-4111-9e7e-520e5feabc8e) | ![Снимок экрана 2024-05-07 в 16 28 …
=> feat: better Edit Modal on smaller screens

src/ui/EditTask.svelte, src/ui/RecurrenceEditor.svelte
- extract `RecurrenceEditor` component
- have reusable components
- simplify cluttered Edit Task modal code
- unit tests
- manual test in demo vault (open the task modal, change recurrence, apply it, verify the change in the task line)
=> refactor: extract `RecurrenceEditor` component

src/ui/EditTaskHelpers.ts, src/ui/RecurrenceEditor.svelte, tests/ui/EditTaskHelpers.test.ts
- discussed this refactoring with @claremacrae (Only change after discussion - added tests to show functionality)
PS while writing the tests I realised I should have written them beforehand...
- better code readability
- code coverage
- new unit tests added
=> refactor: extract, simplify and test `parseAndValidateRecurrence()`

src/Suggestor/EditorSuggestorPopup.ts, tests/Suggestor/Suggestor.test.ts
- Issue/discussion:
- #2850
- This was likely also a contributing factor to:
- #2823
I finally figured out why the adding of an ID to an existing task could cause the duplication of characters at the end of the original task line....
If the line being edited had extra spaces between emojis, then `...toFileLineString()` was shorter than `....originalMarkdown` - so some stray original characters remained at the end of the edited line.
Other small changes:
- There was also a small refactoring in the code I first looked at, whilst trying to understand the fix
- Remove an unnecessary `console.log()` line
See the links above.
Only with exploratory testing - we don't have any automated tests anywhere near this code yet, unfortunately.
I logged the tests I did in this …
=> fix: Prevent duplicate characters at end of line if adding ID via auto-suggest

src/Suggestor/EditorSuggestorPopup.ts
- Issue/discussion: #2825
Prevent unnecessary rewriting of existing task lines. See the bug report for details.
Fixes #2825
Exploratory testing.
=> fix: Don't rewrite any existing ID when adding dependencies

docs/Editing/Auto-Suggest.md, src/Suggestor/Suggestor.ts, tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md, tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
- Issue/discussion: Arises out of https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2828
I am hoping that I am close to fixing the remaining critical issues required for auto-suggest on `id` and `dependsOn` to be good enough for release.
In order to streamline the develop and testing process, and reporting of a further bug just found, I'm re-enabling auto-suggest on dependencies now.
This is a partial revert of #2828.
Some more documentation reverts will be needed later on.
See above.
Manually, in the demo vault.
=> feat: Re-enable auto-suggest for dependencies

src/Obsidian/File.ts, src/Suggestor/EditorSuggestorPopup.ts
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2872
Fixes #2872:
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2872
Much exploratory testing.
=> fix: Prevent Auto-Suggest from making tasks with multiple ids

docs/Editing/Auto-Suggest.md, docs/Getting Started/Task Dependencies.md, docs/Introduction.md, docs/Support and Help/Known Limitations.md, src/Suggestor/Suggestor.ts, tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json, tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md, tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json, tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md, tests/Suggestor/Suggestor.test.ts
- Short the new auto-suggest option names, and make them lower-case
- I've picked `Refactor` as the facility has not yet been released to users
Proof-read and improve the docs for auto-suggest supporting dependencies.
As far as I can tell, this finishes the work done in #2771 🎉 !
By reviewing the docs in Obsidian.
=> docs: Finalise the documentation for Auto-Suggest supporting dependencies

docs/Getting Started/Task Dependencies.md
Update documentation based on 7.4.0 release
- Remove footnote on autosuggest not supporting dependancies due to 7.4.0 supporting autosuggest.
Aligns documentation to released version of the product
=> docs - Update Task Dependencies.md

src/Suggestor/Suggestor.ts, tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_offers_basic_completion_options_for_an_empty_task.approved.json, tests/Suggestor/Suggestor.test.auto-complete_with__dataview__symbols_show_all_suggested_text.approved.md, tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_offers_basic_completion_options_for_an_empty_task.approved.json, tests/Suggestor/Suggestor.test.auto-complete_with__emoji__symbols_show_all_suggested_text.approved.md
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2885
Reverted the Order of Auto Suggest Item too previous Order.
(Just Moved the Task Dependencies Option too the End)
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2885
- Manually in the Vault.
- Additonally Tests covering this have been Altered, too the new/old Ordering.
=> fix: Restore the original order in Auto Suggestions menu

docs-snippets/snippet-callout-titles-bug.md, docs/Getting Started/Getting Started.md, docs/Introduction.md, docs/Support and Help/About Support and Help.md, docs/Support and Help/Missing tasks in callouts with some Obsidian 1.6.x versions.md, docs/Support and Help/Report a Bug.md
- Get what I know about #2890 in to one location, and make it visible to users of the Tasks docs.
- Also help users of other plugins, like dataview.
See #2890
Viewing the content in Obsidian.
Start of new page:
Links to this new page:
=> docs: Write up the Obsidian 1.6.x titled callouts issue

docs/Getting Started/Getting Started.md
Removes a trailing backtick in the first example of [Getting Started](https://publish.obsidian.md/tasks/Getting+Started/Getting+Started) page:
I don't think that was intentional
This has not been tested.
=> docs: Fix first task example in Getting Started

src/Task/Recurrence.ts
- remove nesting in `Recurrence.next()` method
- improve code readability (I found it hard to read while reviewing a PR)
- unit tests
=> refactor: remove nesting in `Recurrence.next()`

src/Suggestor/Suggestor.ts, src/Task/Recurrence.ts, src/TaskSerializer/DefaultTaskSerializer.ts, src/ui/EditableTask.ts, tests/Task/Recurrence.test.ts, tests/TestingTools/RecurrenceBuilder.ts, tests/TestingTools/SampleTasks.ts, tests/TestingTools/TaskBuilder.ts
- Extract occurrence-related data to from `Reccurrence` to `Occurrence` class
- More PRs will follow (I already have the changes in my local repos, submitting slowly)
- Separate concerns in `Recurrence` - the recurring part itself and the dates (occurrence)
- Better code readability
- Unit tests
=> refactor: create `Occurrence` class

src/Task/Recurrence.ts
- start encapsulating `Occurrence`-related behaviour inside that class
- move behaviour from `Recurrence` to `Occurrence` methods `isIdenticalTo()` and `getReferenceDate()`
- Separate concerns between `Recurrence` and `Occurrence` as dates.
- unit tests
=> refactor: move behaviour from `Recurrence` to `Occurrence` methods `isIdenticalTo()` and `getReferenceDate()`

src/Task/Task.ts
- found some hard to read code (nesting, logic) in `Task.ts` and tried to make it more readable. Hope you share the same opinion =)
- Better code
- unit test
=> refactor: simplify `Task.handleNewStatus()`

resources/sample_vaults/Tasks-Demo/Test Data/inheritance_2roots_listitem_listitem_task.md, resources/sample_vaults/Tasks-Demo/Test Data/inheritance_listitem_listitem_task.md, src/Obsidian/Cache.ts, src/Task/ListItem.ts, tests/Obsidian/Cache.test.ts, tests/Obsidian/__test_data__/inheritance_2roots_listitem_listitem_task.ts, tests/Obsidian/__test_data__/inheritance_listitem_listitem_task.ts, tests/Task/ListItem.test.ts
- The feature was not released officially yet, so the bug was not seen
- add `root` and `isRoot` getters to `ListItem` class and test them
- modify test function `printRoots` to use the new methods
- fix bug in `getTasksFromFileContent2()`
- prepare release of parent-child relationship feature
- unit tests
=> fix: collect root `ListItem`s

src/Task/OnCompletion.ts, src/TaskSerializer/DefaultTaskSerializer.ts, tests/Task/OnCompletion.test.ts
- Simplify the tests in `OnCompletion.test.ts`
- Remove two non-obvious dependencies on `OnCompletion.Ignore` being an empty string
- Remove some unreachable error-handling code
- Improve maintainability
- Preparation for release
- Unit tests
=> refactor: Refactor On Completion code and tests

src/DateTime/DateFieldTypes.ts, src/DateTime/Postponer.ts, src/Renderer/TaskLineRenderer.ts, src/ui/EditInstructions/DateInstructions.ts, src/ui/EditInstructions/MenuDividerInstruction.ts, src/ui/Menus/DateMenu.ts, src/ui/Menus/TaskEditingMenu.ts, tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_fully_populated_task.approved.html, tests/Renderer/QueryResultsRenderer.test.ts, tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html, tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html, tests/ui/EditInstructions/DateInstructions.test.ts, tests/ui/EditInstructions/MenuDividerInstruction.test.ts, tests/ui/Menus/DateMenu.test.ts
- Issue/discussion: #2648
Add right-click context menus on all date values in Read Mode and Tasks Query results.
This offers the same date choices as the Postpone menu, except that:
- It acts on the particular date value that the user right-clicks on
- It also works on Done, Created and Cancelled, but offers a selection of recent past dates rather than future dates, as more appropriate for those fields.
Note: documentation is needed, and I will do this before release. For now, I want to test it out further in my own main vault.
Fixes #2648.
- Via new unit tests
- All the new code was written with TDD, so the coverage is good.
- Exploratory testing in the sample vault.
- Plus I have been using an earlier version of this code in my own vault for …
=> feat: Add date context menu in Reading mode and Tasks Query results

src/Obsidian/TaskModal.ts, src/ui/DateEditor.svelte, src/ui/EditTask.scss, src/ui/EditTask.svelte, src/ui/Menus/DatePicker.ts, tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html, tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html, tests/ui/EditTask.test.ts
- Issue/discussion: https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2649
Adds a new date-picker button to the date fields in the Edit Task modal.
This still needs further improvement before release: I don't like the appearance of the new SVG icons very much - but the functionality is really useful, and I want to start making the later changes in smaller PRs.
Fixes https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2649.
- Reviewing the updated HTML approval tests
- Lots of manual exploratory testing in the sample vault.
The new "buttons":
Clicking a button shows a date-picker, preselecting any current value:
Or if no current value, making it easy to select the current date (which today us 24th August):
=> Add modal date picker

src/Obsidian/TaskModal.ts, src/Renderer/TaskLineRenderer.ts, src/ui/DateEditor.svelte, src/ui/EditTask.scss, src/ui/Menus/DatePicker.ts, tests/__mocks__/obsidian.ts, tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html, tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
- Usability fixes to the new calendar button in the Edit Task modal.
- Some refactoring to simplify the code.
Much of this was done whilst pairing with @ilandikov.
Credit to @joethei for the code for adding the icon to the Svelte button - and to @javalent for the original idea in [Discord](https://discord.com/channels/686053708261228577/840286264964022302/902949764209987654).
- Fix accessibility issues of the original SVG-icon-based fake button
- Use a nicer icon on the button
- Exploratory testing in the sample vault
=> fix: Improve Edit Task modal calendar button behaviour

resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md, src/Renderer/TaskLineRenderer.ts, src/ui/DateEditor.svelte, src/ui/EditTask.scss, tests/Renderer/QueryResultsRenderer.test.QueryResultsRenderer_tests_fully_populated_task.approved.html, tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_full_mode.approved.html, tests/Renderer/TaskLineRenderer.test.Visualise_HTML_Full_task_-_short_mode.approved.html, tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot.approved.html, tests/ui/EditTask.test.Edit_Modal_HTML_snapshot_tests_should_match_snapshot_-_without_access_keys.approved.html
- disable and hide all references to the new date picker
- enable release of #3060
=> fix: remove datepicker pending usability fixes

contributing/Testing/About Testing.md, contributing/Testing/Testing and Time Zones.md, resources/sample_vaults/Tasks-Demo/Manual Testing/Time Zones/Pacific-Auckland.md, tests/global-setup.js
After many hours, I've been unable to write an acceptable failing test to show the correctness of #3121.
So I've resorted to write a manual test in the 'Tasks-Demo' vault instead.
The changes are:
- `resources/sample_vaults/Tasks-Demo/Manual Testing/Time Zones/Pacific-Auckland.md`
- Instructions to set the timezone and then run Obsidian and open a file with a task that recurs incorrectly until #3121 is merged.
- `contributing/Testing/Testing and Time Zones.md`
- Make visible the improvements made in this PR
- `tests/global-setup.js`
- How to override the time zone in Jest tests temporarily
To show that the following PR works:
- #3121
- In the test vault
=> vault: Add manual test of recurrence in Pacific/Auckland at DST boundary

src/Renderer/QueryResultsRenderer.ts
- several renames of parameters and variables after tree view has been implemented
- honest code (variable names reflect their contents)
- automated tests only
=> refactor: renames in `QueryResultsRenderer`

docs/Scripting/Task Properties.md
Commit ff8616370012a0023e8dca16b5bed31a7d51c13e moved the location of `TasksDate.ts`. This PR adjusts sources to changes.
=> docs: update `TasksDate` reference

tests/TaskSerializer/DefaultTaskSerializer.test.ts
This is to detect any future unwanted changes, and to visualise wanted changes.
It will be useful for some upcoming refactoring and bug-fixes
Preparation for fixing #3179, and also for fixing an un-reported bug in parsing `on completion`.
By running the new test.
=> test: - Capture string representation of emoji-parsing regexes

manifest.json, package.json, resources/sample_vaults/Tasks-Demo/Manual Testing/Smoke Testing the Tasks Plugin.md, src/Obsidian/TasksEvents.ts, src/Renderer/QueryRenderer.ts, src/Renderer/QueryResultsRenderer.ts, tests/Obsidian/Cache.test.ts, yarn.lock
From the next release, Tasks will require Obsidian 1.4.0 or newer, which was released....
- on July 26, 2023 to Insiders in [Obsidian 1.4.0](https://obsidian.md/changelog/2023-07-26-desktop-v1.4.0/)
- on August 31, 2023 to all users in [Obsidian 1.4.5](https://obsidian.md/changelog/2023-08-31-desktop-v1.4.5/)
I really want to use [Fevol's typings](https://github.com/Fevol/obsidian-typings) to streamline the development process, and it requires Obsidian 1.4.0 or newer, currently.
- Automated testing
- Smoke tests
My more-thorough-than-usual smoke testing exposed #3267, which set back this change by several days!
=> build(deps-dev): bump obsidian API from 1.1.1 to 1.4.0

package.json, yarn.lock
For a better development experience, via more useful comments on the Obsidian API in IDEs.
Add dependency on Fevol's obsidian-typings:
- https://github.com/Fevol/obsidian-typings
For better help about Obsidian API types in IDEs.
- By running the existing tests
It does not change the release process, so no need to run smoke tests.
=> chore: Add development dependency on Fevol's obsidian-typings

src/Query/QueryFileDefaults.ts
Convert a bunch of function calls to a data structure in `QueryFileDefaults.ts`.
I am going to need to add more data, like the types of the properties.
This will allow more code to be generated via data, simplifying maintenance.
Running existing tests.
=> refactor: Improve QueryFileDefaults data maintainability

src/Task/ListItem.ts, tests/Task/ListItem.test.ts
- add `ListItem.toFileLineString()` and `ListItem.checkOrUncheck()`
- work to be continued (failing test present)
- #3170 
- unit tests
=> refactor: check or uncheck list items

src/main.ts
Only execute searches after Obsidian finishes loading.
Benefits:
- This may improve start-up time, when Obsidian opens with notes containing Tasks search results loaded, in Reading mode or Live Preview.
- It fixed use of a "CodeScript Toolkit" startup script inside notes that were already open in Reading mode when Obsidian was starting up.
- It may improve the experience in any vaults that have custom Tasks instructions that load functions from other JavaScript-running plugins
- It ticks off one of the checks in the [Obsidian October O_O 2024 plugin self-critique checklist](https://docs.obsidian.md/oo24/plugin)
Thanks to @mnaoumov for pointing this out.
See above
Launching Obsidian with Tasks searches already open, and confirming the results are still rendered …
=> fix: Only execute searches after Obsidian finishes loading

src/Scripting/ExpandPlaceholders.ts, tests/Query/Query.test.ts, tests/Scripting/ExpandPlaceholders.test.ts
- Issue/discussion: #3249
Instead of using 'null' for invalid values, which is never what the user intended, report an error.
Fix #3249
- Updating existing tests
=> fix: Prevent use of missing properties in placeholders (#3249)

docs/Getting Started/Getting Started.md, resources/sample_vaults/Tasks-Demo/Test Data/numbered_list_items_standard.md, resources/sample_vaults/Tasks-Demo/Test Data/numbered_list_items_with_paren.md, src/Task/TaskRegularExpressions.ts, tests/Obsidian/AllCacheSampleData.ts, tests/Obsidian/Cache.test.ts, tests/Obsidian/__test_data__/numbered_list_items_standard.json, tests/Obsidian/__test_data__/numbered_list_items_with_paren.json, tests/Task/TaskRegularExpressions.test.ts
- Issue/discussion: #3401
In issue #3401, reported earlier today, I learned that it was possible to write numbered list items like this:
```
1) [ ] #task Task 1
1) Sub-item 1
2) [ ] #task Task 2
1) Sub-item 2
```
This teaches Tasks to support that format, and updates the documentation accordingly.
**Note**: In creating tests for this, I discovered an issue with how Obsidian parses nested, numbered list items - they must begin with `1.` or `1)`.
I've logged it in https://forum.obsidian.md/t/incorrect-parsing-of-numbered-list-items-when-first-nested-item-number-is-not-1/98997
Fix #3401
- New unit tests
=> fix: Support Check boxes and List Items in "1)"-style numbered lists

docs/Getting Started/Recurring Tasks.md, src/Config/Settings.ts, src/Config/SettingsTab.ts, src/Task/Occurrence.ts, src/Task/Recurrence.ts, src/Task/Task.ts, src/i18n/locales/en.json, tests/Task/Recurrence.test.ts
- Issue/discussion: . #2751 
I added a new setting option called "Drop scheduled date on recurrence". This setting, when enabled, results in repeated tasks having no scheduled date.
I wasn't sure where to implement the call to `getSettings()` so I made a judgement call and put it there. If you think it fits better somewhere else in the code path, happy to change that. I wasn't really sure, and I figured this was a better approach to give a starting point for discussion than asking a bunch more questions.
#2751
I added one test, it passes. I created a dummy task in the example vault, completed the task with and without …
=> feat: Add option to discard Scheduled date on new recurring tasks

src/Config/Settings.ts, src/Config/SettingsTab.scss, src/Config/SettingsTab.ts, src/Scripting/QueryContext.ts, src/lib/RecordHelpers.ts, tests/Scripting/Includes.test.ts, tests/lib/RecordHelpers.test.ts
- #2443 
- #2267
Primitive initial attempt at a Settings UI to edit re-usable blocks of Tasks instructions.
Things that need improving:
- The layout is really not great - it doesn't use the whole width.
- It is supposed to flex to a single column on small screens but does not
- The 2 edit boxes are not vertically aligned.
- It does not update search results when the user edits any of the includes.
- It does not have any helpful introductory text to explain the feature.
Working towards:
- #2443 
- #2267
I want to use it for a while in my vault, for testing the feature.
Manual exploratory testing.
=> feat: First try at editing named reusable task block statements

src/Config/SettingsTab.scss, src/Config/SettingsTab.ts
- Issue/discussion: None - it's a new, unreleased feature
Improve the layout of new Includes settings area.
Getting the feature a bit closer to release.
Manual exploratory testing.
**Before:**
**After:**
=> fix: Improve the layout of Includes section in settings

src/Config/IncludesSettingsUI.scss
A series of refacotings to improve the structure and maintainability of `IncludesSettingsUI.scss`.
Preparing to make the Includes settings usable on narrow screens.
- By comparing the generated `styles.css` throughout the changes, to ensure no significant changes.
- By opening the Tasks settings in the test vault, and ensuring that editing the Includes section still works.
=> refactor: Improve the maintainability of `IncludesSettingsUI.scss`

src/Config/IncludesSettingsService.ts, src/Config/IncludesSettingsUI.scss, src/Config/IncludesSettingsUI.ts, tests/Config/IncludesSettingsService.test.ts
- #2443 
- #2267
**In Tasks Settings**: Add drag handles to the rows in the Includes settings, so users can re-order items, to keep similar things closer together.
Getting closer to release:
- #2443 
- #2267
- By running the test plugin on Mac, and on iPhone emulator.
=> feat: Allow Includes settings to be re-ordered

tests/Obsidian/__test_data__/jason_properties.json, tests/Obsidian/__test_data__/yaml_tags_had_value_then_was_emptied_by_obsidian.json, tests/Obsidian/__test_data__/yaml_tags_is_empty_list.json, tests/Obsidian/__test_data__/yaml_tags_with_one_value_on_single_line.json, tests/Obsidian/__test_data__/yaml_tags_with_two_values_on_one_line.json, tests/Scripting/TasksFile.test.ts
This saves Obsidian 1.9.4's CachedMetadata, showing what has changed since 1.9.2.
(1.9.3 and 1.9.4 are the same)
See the individual commits for details of the changes observed.
The process to update the saved files is documented in:
https://publish.obsidian.md/tasks-contributing/Testing/Using+Obsidian+API+in+tests
This is research: I need to update this page: [Missing tags, aliases and cssclasses in some Obsidian 1.9.x versions](https://publish.obsidian.md/tasks/Support+and+Help/Missing+tags%2C+aliases+and+cssclasses+in+some+Obsidian+1.9.x+versions)
By running the tests, and updating the one that fails.
=> test: Save the parsing diffs from Obsidian 1.9.2 to 1.9.4

src/Scripting/TasksFile.ts, tests/Obsidian/Cache.test.ts, tests/Scripting/TasksFile.test.ts, tests/Task/Link.test.ts, tests/Task/Link.test.visualise_links_outlinks.approved.md
- Issue/discussion: #3308
require.
- Add `TasksFile.outlinksInProperties` and `TasksFile.outlinksInBody`
- `TasksFile.outlinks` now returns both the above
Trying to get the following ready for initial release:
- https://github.com/obsidian-tasks-group/obsidian-tasks/pull/3466
=> feat: Add `outlinksInProperties` and `outlinksInBody` - `outlinks` returns both

docs/Scripting/Expressions.md, tests/Scripting/Expression.test.Expression_returns_and_functions.approved.md, tests/Scripting/Expression.test.ts
- Issue/discussion: #3625
Document a limitation of expressions that was pointed out in #3625.
Fix #3625
By adding tests to confirm the reported behaviour, and which also generates text that is embedded in the docs.
The green rectangles show the additions to the documentation:
=> docs: String "return" in function returns "undefined" (#3625)
